// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negrita",copy:"Copiar",cut:"Cortar","delete":"Suprimir",indent:"Sangr\u00eda",insertHorizontalRule:"Regla horizontal",insertOrderedList:"Lista numerada",insertUnorderedList:"Lista con vi\u00f1etas",italic:"Cursiva",justifyCenter:"Alinear centro",justifyFull:"Justificar",justifyLeft:"Alinear izquierda",justifyRight:"Alinear derecha",outdent:"Anular sangr\u00eda",paste:"Pegar",redo:"Rehacer",removeFormat:"Eliminar formato",selectAll:"Seleccionar todo",strikethrough:"Tachado",
subscript:"Sub\u00edndice",superscript:"Super\u00edndice",underline:"Subrayado",undo:"Deshacer",unlink:"Eliminar enlace",createLink:"Crear enlace",toggleDir:"Conmutar direcci\u00f3n",insertImage:"Insertar imagen",insertTable:"Insertar/Editar tabla",toggleTableBorder:"Conmutar borde de tabla",deleteTable:"Suprimir tabla",tableProp:"Propiedad de tabla",htmlToggle:"Fuente HTML",foreColor:"Color de primer plano",hiliteColor:"Color de segundo plano",plainFormatBlock:"Estilo de p\u00e1rrafo",formatBlock:"Estilo de p\u00e1rrafo",
fontSize:"Tama\u00f1o de font",fontName:"Nombre de font",tabIndent:"Sangr\u00eda de tabulador",fullScreen:"Conmutar pantalla completa",viewSource:"Ver fuente HTML",print:"Imprimir",newPage:"Nueva p\u00e1gina",systemShortcut:'La acci\u00f3n "${0}" s\u00f3lo est\u00e1 disponible en su navegador mediante un atajo de teclado. Utilice ${1}.',ctrlKey:"control+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"xx-peque\u00f1o",2:"x-peque\u00f1o",3:"peque\u00f1o",4:"medio",5:"grande",
6:"x-grande",7:"xx-grande",fontSize:"Tama\u00f1o",fontName:"Font",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",monospace:"espacio sencillo",cursive:"cursiva",fantasy:"fantas\u00eda",noFormat:"Ninguno",p:"P\u00e1rrafo",h1:"Cabecera",h2:"Subcabecera",h3:"Sub-subcabecera",pre:"Preformateado",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Previsualizaci\u00f3n",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Buscar:",findTooltip:"Especifique el texto que desee buscar",
replaceLabel:"Sustituir por:",replaceTooltip:"Especifique el texto por el que se debe sustituir",findReplace:"Conmutar Buscar/Sustituir",matchCase:"Coincidir may\u00fasculas y min\u00fasculas",matchCaseTooltip:"Coincidir may\u00fasculas y min\u00fasculas",backwards:"Hacia atr\u00e1s",backwardsTooltip:"Buscar texto hacia atr\u00e1s",replaceAllButton:"Sustituir todo",replaceAllButtonTooltip:"Sustituir todo el texto",findButton:"Buscar",findButtonTooltip:"Buscar el texto",replaceButton:"Sustituir",replaceButtonTooltip:"Sustituir el texto",
replaceDialogText:"Se han sustituido ${0} apariciones.",eofDialogText:"\u00daltima aparici\u00f3n ${0}",eofDialogTextFind:"encontrado",eofDialogTextReplace:"sustituido",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Pegar desde Word",instructions:"Pegue el contenido de Word en el siguiente recuadro de texto. Cuando est\u00e9 satisfecho con el contenido que se debe insertar, pulse el bot\u00f3n pegar. Para abortar la inserci\u00f3n de texto, pulse el bot\u00f3n cancelar.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insertar ancla",title:"Propiedades del ancla",anchor:"Nombre:",text:"Descripci\u00f3n:",set:"Establecer",cancel:"Cancelar",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Cita en bloque",_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Seleccionar una plantilla para crear entidades",generalSettings:"Configuraci\u00f3n general",layerSettings:"Configuraciones de la capa",editDescription:"Proporcione texto de visualizaci\u00f3n para el panel de edici\u00f3n",
editDescriptionTip:"Este texto se muestra sobre el selector de plantillas. D\u00e9jelo en blanco si no desea usar ning\u00fan texto.",promptOnSave:"Solicitud para guardar las ediciones no guardadas cuando se cierra el formulario o se cambia al siguiente registro.",promptOnSaveTip:"Muestra una solicitud cuando el usuario hace clic en Cerrar o va al siguiente registro editable si la entidad actual tiene ediciones sin guardar.",promptOnDelete:"Requerir confirmaci\u00f3n al eliminar un registro",promptOnDeleteTip:"Muestra una solicitud cuando el usuario hace clic en Eliminar para confirmar la acci\u00f3n.",
removeOnSave:"Eliminar entidad de la selecci\u00f3n al guardar",removeOnSaveTip:"Opci\u00f3n para eliminar la entidad del conjunto de selecci\u00f3n al guardar el registro. Si es el \u00fanico registro seleccionado, el panel vuelve a cambiar a la p\u00e1gina de plantilla.",useFilterEditor:"Usar filtro de plantilla de entidad",useFilterEditorTip:"Opci\u00f3n para usar el selector de plantillas de filtro que permite ver una plantilla de capa o buscar plantillas por nombre.",listenToGroupFilter:"Aplicar valores de filtro del widget Filtro de grupo a los campos predefinidos",
listenToGroupFilterTip:"Cuando se aplica un filtro en el widget Filtro de grupo, aplica el valor a un campo coincidente de la lista de valores predefinidos.",keepTemplateActive:"Mantener plantilla seleccionada activa",keepTemplateActiveTip:"Cuando se muestra el selector de plantillas, si se seleccion\u00f3 una plantilla previamente, vuelve a seleccionarla.",layerSettingsTable:{allowDelete:"Permitir eliminaci\u00f3n",allowDeleteTip:"Opci\u00f3n que permite al usuario eliminar una entidad; estar\u00e1 deshabilitada si la capa no admite eliminaciones.",
edit:"Editable",editTip:"Opci\u00f3n para incluir la capa en el widget.",label:"Capa",labelTip:"Nombre de la capa definido en el mapa",update:"Deshabilitar edici\u00f3n de geometr\u00eda",updateTip:"Opci\u00f3n para deshabilitar la capacidad de mover la geometr\u00eda una vez insertada o de mover la geometr\u00eda a una entidad ya existente.",allowUpdateOnly:"S\u00f3lo actualizar",allowUpdateOnlyTip:"Opci\u00f3n para permitir \u00fanicamente la modificaci\u00f3n de entidades ya existentes. Est\u00e1 activada de manera predeterminada y se deshabilita si la capa no admite la creaci\u00f3n de nuevas entidades.",
fields:"Campos",fieldsTip:"Modifique los campos que se van a editar y defina atributos inteligentes",description:"Descripci\u00f3n",descriptionTip:"Opci\u00f3n que permite introducir texto para que se muestre en la parte superior de la p\u00e1gina de atributos."},editFieldError:"Las modificaciones de campos y los atributos inteligentes no est\u00e1n disponibles para las capas que no son editables",noConfigedLayersError:"El Editor inteligente requiere una o varias capas editables"},editDescriptionPage:{title:"Definir texto de descripci\u00f3n general de atributo para \x3cb\x3e${layername}\x3c/b\x3e "},
fieldsPage:{title:"Configurar campos para \x3cb\x3e${layername}\x3c/b\x3e",description:"Use la columna Predefinir para permitir que el usuario introduzca un valor antes de crear una nueva entidad. Use el bot\u00f3n de edici\u00f3n de acciones para activar los atributos inteligentes en una capa. Los atributos inteligentes pueden requerir, ocultar o deshabilitar un campo en funci\u00f3n de los valores de otros campos.",fieldsNotes:"* es un campo obligatorio. Si desactiva Vista para este campo y la plantilla de edici\u00f3n no rellena ese valor de campo, no podr\u00e1 guardar un nuevo registro.",
fieldsSettingsTable:{display:"Vista",displayTip:"Determina si el campo no est\u00e1 visible",edit:"Editable",editTip:"Active esta opci\u00f3n si el campo est\u00e1 presente en el formulario de atributos",fieldName:"Nombre",fieldNameTip:"Nombre del campo definido en la base de datos",fieldAlias:"Alias",fieldAliasTip:"Nombre del campo definido en el mapa",canPresetValue:"Predefinido",canPresetValueTip:"Opci\u00f3n para mostrar el campo en la lista de campos predefinidos y permitir que el usuario defina el valor antes de editar.",
actions:"Acciones",actionsTip:"Cambie el orden de los campos o configure atributos inteligentes"},smartAttSupport:"Los atributos inteligentes no se admiten en los campos de base de datos obligatorios"},actionPage:{title:"Configurar las acciones de atributos inteligentes para \x3cb\x3e${fieldname}\x3c/b\x3e",description:"Las acciones est\u00e1n siempre desactivadas a menos que se especifiquen los criterios que har\u00e1n que se activen. Las acciones se procesan en orden y solo se activar\u00e1 una acci\u00f3n por campo. Use el bot\u00f3n de edici\u00f3n de criterios para definir los criterios.",
actionsSettingsTable:{rule:"Acci\u00f3n",ruleTip:"Acci\u00f3n realizada cuando se cumplen los criterios",expression:"Expresi\u00f3n",expressionTip:"Expresi\u00f3n resultante del criterio definido en formato SQL",actions:"Criterios",actionsTip:"Cambie el orden de la regla y defina los criterios cuando se active"},actions:{hide:"Ocultar",required:"Obligatorio",disabled:"Deshabilitado"}},filterPage:{submitHidden:"\u00bfEnviar datos de atributos para este campo aunque est\u00e9 oculto?",title:"Configurar expresi\u00f3n para la regla ${action}",
filterBuilder:"Definir acci\u00f3n en el campo cuando el registro coincida con ${any_or_all} de las expresiones siguientes",noFilterTip:"Con las herramientas siguientes, defina la declaraci\u00f3n para los casos en los que la acci\u00f3n est\u00e9 activa."},_localized:{}}});