// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Halvfet",copy:"Kopiera",cut:"Klipp ut","delete":"Ta bort",indent:"Indrag",insertHorizontalRule:"Horisontell linje",insertOrderedList:"Numrerad lista",insertUnorderedList:"Punktlista",italic:"Kursiv",justifyCenter:"Centrera",justifyFull:"Marginaljustera",justifyLeft:"V\u00e4nsterjustera",justifyRight:"H\u00f6gerjustera",outdent:"Utdrag",paste:"Klistra in",redo:"G\u00f6r om",removeFormat:"Ta bort format",selectAll:"Markera allt",strikethrough:"Genomstruken",
subscript:"Neds\u00e4nkt",superscript:"Upph\u00f6jt",underline:"Understruken",undo:"\u00c5ngra",unlink:"Ta bort l\u00e4nk",createLink:"Skapa l\u00e4nk",toggleDir:"V\u00e4xla riktning",insertImage:"Infoga bild",insertTable:"Infoga/redigera tabell",toggleTableBorder:"V\u00e4xla tabellinjer",deleteTable:"Ta bort tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-k\u00e4llkod",foreColor:"F\u00f6rgrundsf\u00e4rg",hiliteColor:"Bakgrundsf\u00e4rg",plainFormatBlock:"Styckeformat",formatBlock:"Styckeformat",
fontSize:"Teckenstorlek",fontName:"Teckensnitt",tabIndent:"Tabbindrag",fullScreen:"V\u00e4xla helsk\u00e4rm",viewSource:"Visa HTML-kod",print:"Skriv ut",newPage:"Ny sida",systemShortcut:"\u00c5tg\u00e4rden ${0} \u00e4r endast tillg\u00e4nglig i webbl\u00e4saren via ett tangentbordskommando. Anv\u00e4nd ${1}.",ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",fontSize:"Storlek ",fontName:"Teckensnitt",formatBlock:"Format",
serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Inget",p:"Stycke",h1:"Rubrik 1",h2:"Rubrik 2",h3:"Rubrik 3",pre:"F\u00f6rformaterad",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"F\u00f6rhandsgranskning",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f6k: ",findTooltip:"Skriv s\u00f6ktexten",replaceLabel:"Ers\u00e4tt med:",replaceTooltip:"Skriv ers\u00e4ttningstexten",findReplace:"S\u00f6k och ers\u00e4tt",
matchCase:"Matcha gemener/versaler",matchCaseTooltip:"Matcha gemener/versaler",backwards:"Bak\u00e5t",backwardsTooltip:"S\u00f6k bak\u00e5t efter text",replaceAllButton:"Ers\u00e4tt alla",replaceAllButtonTooltip:"Ers\u00e4tt all text",findButton:"S\u00f6k",findButtonTooltip:"S\u00f6k efter texten",replaceButton:"Er\u00e4tt",replaceButtonTooltip:"Ers\u00e4tt texten",replaceDialogText:"${0} f\u00f6rekomster har ersatts.",eofDialogText:"Sista f\u00f6rekomsten ${0}",eofDialogTextFind:"hittades",eofDialogTextReplace:"ersattes",
_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Klistra in fr\u00e5n Word",instructions:"Klistra in inneh\u00e5llet fr\u00e5n Word i textrutan nedan. N\u00e4r du har valt inneh\u00e5ll klickar du p\u00e5 Klistra in. Klicka p\u00e5 Avbryt om du inte vill klistra in text. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Infoga ankare",title:"Ankaregenskaper",anchor:"Namn:",text:"Beskrivning:",set:"Anv\u00e4nd",cancel:"Avbryt",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockcitat",
_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"V\u00e4lj en mall f\u00f6r att skapa geoobjekt",generalSettings:"Allm\u00e4nna inst\u00e4llningar",layerSettings:"Lagerinst\u00e4llningar",editDescription:"Ange visningstext f\u00f6r redigeringspanelen",editDescriptionTip:"Den h\u00e4r texten visas ovanf\u00f6r mallv\u00e4ljaren. L\u00e4mna tomt om ingen text ska visas.",promptOnSave:"Uppmana anv\u00e4ndaren att spara osparade \u00e4ndringar n\u00e4r formul\u00e4ret st\u00e4ngs eller vid \u00f6verg\u00e5ng till n\u00e4sta post.",
promptOnSaveTip:"Visa en uppmaning n\u00e4r anv\u00e4ndaren klickar p\u00e5 St\u00e4ng eller navigerar till n\u00e4sta redigerbara post, om det finns \u00e4ndringar som inte har sparats i det aktuella geoobjektet.",promptOnDelete:"Beg\u00e4r bekr\u00e4ftelse innan en post tas bort.",promptOnDeleteTip:"Visa en uppmaning om att bekr\u00e4fta \u00e5tg\u00e4rden n\u00e4r anv\u00e4ndaren klickat p\u00e5 Ta bort.",removeOnSave:"Ta bort geoobjektet ur urvalet n\u00e4r posten sparas.",removeOnSaveTip:"Alternativ f\u00f6r att ta bort geoobjektet ur urvalsupps\u00e4ttningen n\u00e4r posten sparas. Om det \u00e4r den enda valda posten \u00e5terg\u00e5r panelen till mallsidan.",
useFilterEditor:"Anv\u00e4nd mallfilter f\u00f6r geoobjekt",useFilterEditorTip:"Alternativ f\u00f6r att anv\u00e4nda filtermallv\u00e4ljaren som ger m\u00f6jlighet att visa ett lagers mallar eller s\u00f6ka efter mallar efter namn.",listenToGroupFilter:"Till\u00e4mpa filtreringsv\u00e4rden fr\u00e5n gruppfiltreringswidgeten p\u00e5 f\u00f6rinst\u00e4llda f\u00e4lt",listenToGroupFilterTip:"N\u00e4r ett filter anv\u00e4nds i gruppfiltreringswidgeten till\u00e4mpas v\u00e4rdet p\u00e5 ett matchande f\u00e4lt i listan \u00f6ver f\u00f6rinst\u00e4llda v\u00e4rden.",
keepTemplateActive:"L\u00e5t den markerade mallen vara aktiv",keepTemplateActiveTip:"Om en mall har valts tidigare n\u00e4r mallv\u00e4ljlaren visas, v\u00e4ljer du den.",layerSettingsTable:{allowDelete:"Till\u00e5t borttagning",allowDeleteTip:"Alternativ f\u00f6r att l\u00e5ta anv\u00e4ndaren ta bort ett geoobjekt \u2013 inaktiverat om lagret inte medger borttagning",edit:"Redigerbar",editTip:"Alternativ f\u00f6r att ta med lagret i widgeten",label:"Lager",labelTip:"Lagrets namn som det anges p\u00e5 kartan",
update:"Inaktivera geometriredigering",updateTip:"Alternativ f\u00f6r att inaktivera m\u00f6jligheten att flytta geometrin n\u00e4r den placerats eller geometrin p\u00e5 ett befintligt geoobjekt",allowUpdateOnly:"Endast uppdatering",allowUpdateOnlyTip:"Alternativ f\u00f6r att endast till\u00e5ta \u00e4ndring av befintliga geoobjekt \u2013 markerat som standard och inaktiverat om det inte g\u00e5r att skapa nya geoobjekt i lagret",fields:"F\u00e4lt",fieldsTip:"Modifiera f\u00e4lten som ska redigeras och definiera smarta attribut",
description:"Beskrivning",descriptionTip:"Alternativ f\u00f6r att ange text som ska visas \u00f6verst p\u00e5 attributsidan."},editFieldError:"F\u00e4ltmodifieringar och smarta attribut \u00e4r inte tillg\u00e4ngliga f\u00f6r lager som inte kan redigeras",noConfigedLayersError:"Smart redigerare kr\u00e4ver ett eller flera redigerbara lager"},editDescriptionPage:{title:"Definiera attribut\u00f6versiktstext f\u00f6r \x3cb\x3e${layername}\x3c/b\x3e "},fieldsPage:{title:"Konfigurera f\u00e4lt f\u00f6r \x3cb\x3e${layername}\x3c/b\x3e",
description:"Med kolumnen F\u00f6rvalt kan du l\u00e5ta anv\u00e4ndaren ange ett v\u00e4rde innan ett nytt geoobjekt skapas. Med redigeringsknappen \u00c5tg\u00e4rder kan du aktivera smarta attribut f\u00f6r ett lager. Smarta attribut kan kr\u00e4va, d\u00f6lja eller inaktivera ett f\u00e4lt baserat p\u00e5 v\u00e4rden i andra f\u00e4lt.",fieldsNotes:"* \u00e4r ett obligatoriskt f\u00e4lt. Om du avmarkerar Visa f\u00f6r detta f\u00e4lt, och redigeringsmallen inte fyller i f\u00e4ltv\u00e4rdet, kan du inte spara en ny post.",
fieldsSettingsTable:{display:"Visa",displayTip:"Ange om f\u00e4ltet inte \u00e4r synligt",edit:"Redigerbar",editTip:"Markera om f\u00e4ltet finns i attributformul\u00e4ret",fieldName:"Namn",fieldNameTip:"F\u00e4ltets namn som det anges i geodatabasen",fieldAlias:"Alias",fieldAliasTip:"F\u00e4ltets namn som det anges p\u00e5 kartan",canPresetValue:"F\u00f6rinst\u00e4llning",canPresetValueTip:"Alternativ f\u00f6r att visa f\u00e4ltet i den f\u00f6rinst\u00e4llda f\u00e4ltlistan och l\u00e5ta anv\u00e4ndaren ange v\u00e4rdet f\u00f6re redigering",
actions:"\u00c5tg\u00e4rder",actionsTip:"\u00c4ndra f\u00e4ltens ordning eller g\u00f6r inst\u00e4llningar f\u00f6r smarta attribut"},smartAttSupport:"Smarta attribut kan inte anv\u00e4ndas f\u00f6r obligatoriska databasf\u00e4lt"},actionPage:{title:"Konfigurera smarta attribut\u00e5tg\u00e4rder f\u00f6r \x3cb\x3e${fieldname}\x3c/b\x3e",description:"\u00c5tg\u00e4rderna \u00e4r alltid inaktiva om du inte anger villkor som utl\u00f6ser dem. \u00c5tg\u00e4rderna bearbetas i ordningsf\u00f6ljd och endast en \u00e5tg\u00e4rd kan utl\u00f6sas per f\u00e4lt. Ange villkor med knappen f\u00f6r villkorsredigering.",
actionsSettingsTable:{rule:"\u00c5tg\u00e4rd",ruleTip:"\u00c5tg\u00e4rden utf\u00f6rs n\u00e4r villkoren \u00e4r uppfyllda",expression:"Uttryck",expressionTip:"Resultatuttrycket i SQL-format fr\u00e5n angivna villkor",actions:"Villkor",actionsTip:"\u00c4ndra ordningen i regeln och ange villkor f\u00f6r n\u00e4r den ska utl\u00f6sas"},actions:{hide:"D\u00f6lj",required:"N\u00f6dv\u00e4ndig",disabled:"Inaktiverad"}},filterPage:{submitHidden:"Skicka attributdata f\u00f6r detta f\u00e4lt \u00e4ven om det \u00e4r dolt?",
title:"Konfigurera uttryck f\u00f6r regeln ${action}",filterBuilder:"Ange \u00e5tg\u00e4rd f\u00f6r f\u00e4ltet n\u00e4r posten matchar ${any_or_all} av f\u00f6ljande uttryck",noFilterTip:"Anv\u00e4nd verktygen nedan f\u00f6r att definiera p\u00e5st\u00e5endet f\u00f6r n\u00e4r \u00e5tg\u00e4rden \u00e4r aktiv."},_localized:{}}});