// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Bold",copy:"Copy",cut:"Cut","delete":"Delete",indent:"Indent",insertHorizontalRule:"Horizontal Rule",insertOrderedList:"Numbered List",insertUnorderedList:"Bullet List",italic:"Italic",justifyCenter:"Align Center",justifyFull:"Justify",justifyLeft:"Align Left",justifyRight:"Align Right",outdent:"Outdent",paste:"Paste",redo:"Redo",removeFormat:"Remove Format",selectAll:"Select All",strikethrough:"Strikethrough",subscript:"Subscript",superscript:"Superscript",
underline:"Underline",undo:"Undo",unlink:"Remove Link",createLink:"Create Link",toggleDir:"Toggle Direction",insertImage:"Insert Image",insertTable:"Insert/Edit Table",toggleTableBorder:"Toggle Table Border",deleteTable:"Delete Table",tableProp:"Table Property",htmlToggle:"HTML Source",foreColor:"Foreground Color",hiliteColor:"Background Color",plainFormatBlock:"Paragraph Style",formatBlock:"Paragraph Style",fontSize:"Font Size",fontName:"Font Name",tabIndent:"Tab Indent",fullScreen:"Toggle Full Screen",
viewSource:"View HTML Source",print:"Print",newPage:"New Page",systemShortcut:'The "${0}" action is only available in your browser using a keyboard shortcut. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"xx-small",2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",fontSize:"Size",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"None",
p:"Paragraph",h1:"Heading",h2:"Subheading",h3:"Sub-subheading",pre:"Pre-formatted",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",
replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Select a template to create features",generalSettings:"General Settings",layerSettings:"Layer Settings",editDescription:"Provide display text for the edit panel",editDescriptionTip:"This text is displayed above the Template picker, leave blank for no text.",
promptOnSave:"Prompt to save unsaved edits when form is closed or switched to the next record.",promptOnSaveTip:"Display a prompt when the user clicks close or navigates to the next editable record when the current feature has unsaved edits.",promptOnDelete:"Require confirmation when deleting a record.",promptOnDeleteTip:"Display a prompt when the user clicks delete to confirm the aciton.",removeOnSave:"Remove feature from selection on save.",removeOnSaveTip:"Option to remove the feature from the selection set when the record is saved.  If it is the only selected record, the panel is switched back to the template page.",
useFilterEditor:"Use feature template filter",useFilterEditorTip:"Option to use the Filter Template picker which provides the ability to view one layers templates or search for templates by name.",listenToGroupFilter:"Apply filter values from Group Filter widget to Preset fields",listenToGroupFilterTip:"When a filter is applied in the Group Filter widget, apply the value to a matching field in the Preset value list.",keepTemplateActive:"Keep selected template active",keepTemplateActiveTip:"When the template picker is shown, if a template was previously selected, reselect it.",
layerSettingsTable:{allowDelete:"Allow Delete",allowDeleteTip:"Option to allow the user to delete a feature; disabled if the layer does not support delete",edit:"Editable",editTip:"Option to include the layer in the widget",label:"Layer",labelTip:"Name of the layer as defined in the map",update:"Disable Geometry Editing",updateTip:"Option to disable the ability to move the geometry once placed or move the geometry on an existing feature",allowUpdateOnly:"Update Only",allowUpdateOnlyTip:"Option to allow only the modication of existing features, checked on by default and disabled if the layer does not support creating new features",
fields:"Fields",fieldsTip:"Modify the fields to be edited and define Smart Attributes",description:"Description",descriptionTip:"Option to enter text to display on top of the attribute page."},editFieldError:"Field modifications and Smart attributes are not available to layers that are not editable",noConfigedLayersError:"Smart Editor requires one or more editable layers"},editDescriptionPage:{title:"Define attribute overview text for \x3cb\x3e${layername}\x3c/b\x3e "},fieldsPage:{title:"Configure fields for \x3cb\x3e${layername}\x3c/b\x3e",
description:"Use the Preset column to allow the user to enter a value prior to creating a new feature. Use the Actions edit button to activate Smart Attributes on a layer. The Smart Attributes can require, hide or disable a field based on values in other fields.",fieldsNotes:"* is a required field.  If you uncheck Display for this field, and the edit template does not populate that field value, you will not be able to save a new record.",fieldsSettingsTable:{display:"Display",displayTip:"Determine whether the field is not visible",
edit:"Editable",editTip:"Check on if the field is present in the attribute form",fieldName:"Name",fieldNameTip:"Name of the field defined in the database",fieldAlias:"Alias",fieldAliasTip:"Name of the field defined in the map",canPresetValue:"Preset",canPresetValueTip:"Option to show the field in the preset field list and allow the user to set the value prior to editing",actions:"Actions",actionsTip:"Change the order of the fields or set up Smart Attributes"},smartAttSupport:"Smart Attributes are not supported on required database fields"},
actionPage:{title:"Configure the Smart Attribute actions for \x3cb\x3e${fieldname}\x3c/b\x3e",description:"The actions are always off unless you specify the criteria on which they will be triggered.  The actions are processed in order and only one action will be triggered per field.  Use the Criteria Edit button to define the criteria.",actionsSettingsTable:{rule:"Action",ruleTip:"Action performed when the criteria is satsified",expression:"Expression",expressionTip:"The resulting expression in SQL format from the defined criteria",
actions:"Criteria",actionsTip:"Change the order of the rule and define the criteria when it is triggered"},actions:{hide:"Hide",required:"Required",disabled:"Disabled"}},filterPage:{submitHidden:"Submit attribute data for this field even when hidden?",title:"Configure expression for the ${action} rule",filterBuilder:"Set action on field when record matches ${any_or_all} of the following expressions",noFilterTip:"Using the tools below, define the statement for when the action is active."},_localized:{}}});