// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Podebljano",copy:"Kopiraj",cut:"Iseci","delete":"Izbri\u0161i",indent:"Uvla\u010denje ",insertHorizontalRule:"Horizontalna linija vodilja",insertOrderedList:"Numerisana lista",insertUnorderedList:"Lista sa znakovima za nabrajanje",italic:"Kurzivno",justifyCenter:"Poravnaj po centru",justifyFull:"Poravnaj obostrano",justifyLeft:"Poravnaj levo",justifyRight:"Poravnaj desno",outdent:"Izvla\u010denje",paste:"Nalepi",redo:"Ponovi radnju",removeFormat:"Ukloni format",
selectAll:"Izaberi sve",strikethrough:"Precrtani tekst",subscript:"Indeksni tekst",superscript:"Eksponentni tekst",underline:"Podvu\u010deno",undo:"Opozovi radnju",unlink:"Ukloni link",createLink:"Kreiraj link",toggleDir:"Uklju\u010di/isklju\u010di smer",insertImage:"Umetni sliku",insertTable:"Umetni/uredi tabelu",toggleTableBorder:"Uklju\u010di/isklju\u010di ivicu tabele",deleteTable:"Izbri\u0161i tabelu",tableProp:"Svojstva tabele",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",
plainFormatBlock:"Stil pasusa",formatBlock:"Stil pasusa",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",tabIndent:"Uvla\u010denje kartice",fullScreen:"Uklju\u010di/isklju\u010di prikaz preko celog ekrana",viewSource:"Prika\u017ei HTML izvor",print:"\u0160tampaj",newPage:"Nova stranica",systemShortcut:"Radnja \u201e${0}\u201c je dostupna u pregleda\u010du samo pomo\u0107u tasterskih pre\u010dica. Koristite ${1}.",ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"xx-malo",
2:"x-malo",3:"malo",4:"srednje",5:"veliko",6:"x-veliko",7:"xx-veliko",fontSize:"Veli\u010dina",fontName:"Font",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"jednorazma\u010dni",cursive:"kurziv",fantasy:"fantazija",noFormat:"Bez formata",p:"Pasus",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Preformatirano",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Prona\u0111i:",findTooltip:"Unesite tekst koji treba prona\u0107i",
replaceLabel:"Zameni sa:",replaceTooltip:"Unesite zamenski tekst",findReplace:"Prona\u0111i i zameni",matchCase:"Podudaranje malih i velikih slova",matchCaseTooltip:"Podudaranje malih i velikih slova",backwards:"Unazad",backwardsTooltip:"Pretra\u017eite tekst unazad",replaceAllButton:"Zameni sve",replaceAllButtonTooltip:"Zamenjuje sav tekst",findButton:"Prona\u0111i",findButtonTooltip:"Prona\u0111ite tekst",replaceButton:"Zameni",replaceButtonTooltip:"Zamenite tekst",replaceDialogText:"Zamenjeno ${0} pojava.",
eofDialogText:"Poslednja pojava ${0}",eofDialogTextFind:"prona\u0111eno",eofDialogTextReplace:"zamenjeno",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Nalepi iz programa Word",instructions:"Nalepite sadr\u017eaj iz programa Word u okvir za tekst ispod.  Kada ste zadovoljni sa sadr\u017eajem za umetanje, kliknite na dugme Nalepi.  Da otka\u017eete umetanje teksta, kliknite na dugme Otka\u017ei.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",
title:"Svojstva sidra",anchor:"Ime:",text:"Opis:",set:"Podesi",cancel:"Otka\u017ei",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Citat pasusa",_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Izaberite \u0161ablon da biste kreirali geoobjekte",generalSettings:"Op\u0161te postavke",layerSettings:"Postavke sloja",editDescription:"Obezbedi tekst prikaza za panel za ure\u0111ivanje",editDescriptionTip:"Ovaj tekst je prikazan iznad bira\u010da \u0161ablona, ostavite prazno ukoliko ne \u017eelite tekst.",
promptOnSave:"Postavi upit za \u010duvanje nesa\u010duvanih izmena kada se obrazac zatvori ili prebaci na slede\u0107i zapis.",promptOnSaveTip:"Prika\u017ei upit kada korisnik klikne na \u201ezatvori\u201c ili ode na slede\u0107i zapis koji mo\u017ee da se izmene, kada trenutni geoobjekat ima nesa\u010duvane izmene.",promptOnDelete:"Zahtevaj potvrdu prilikom brisanja zapisa.",promptOnDeleteTip:"Prika\u017ei upit kada korisnik klikne na brisanje da bi potvrdio radnju.",removeOnSave:"Ukloni geoobjekat iz izbora prilikom \u010duvanja.",
removeOnSaveTip:"Opcija za uklanjanje geoobjekta iz skupa izbora kada je zapis sa\u010duvan. Ako je to jedini izabran zapis, panel se prebacuje nazad na stranicu \u0161ablona.",useFilterEditor:"Koristi filter \u0161ablona geoobjekta",useFilterEditorTip:"Opcija za kori\u0161\u0107enje bira\u010da \u0161ablona filtera koji obezbe\u0111uje mogu\u0107nost da se pregledaju \u0161abloni jednog sloja ili tra\u017ee \u0161abloni po imenu.",listenToGroupFilter:"Primeni vrednosti filtera iz vid\u017eeta Grupni filter na unapred pode\u0161ena polja",
listenToGroupFilterTip:"Kada primenite filter u vid\u017eetu Grupni filter, primenite vrednost na odgovaraju\u0107e polje u listi sa Unapred pode\u0161enom vrednosti.",keepTemplateActive:"Odr\u017ei izabrani \u0161ablon aktivnim",keepTemplateActiveTip:"Kada je prikazan bira\u010d \u0161ablona, ponovo izaberite \u0161ablon ako je bio prethodno izabran.",layerSettingsTable:{allowDelete:"Dozvoli brisanje",allowDeleteTip:"Opcija da se korisniku dozvoli da obri\u0161e geoobjekat; onemogu\u0107ena je ako sloj ne podr\u017eava brisanje",
edit:"Mo\u017ee da se izmeni",editTip:"Opcija da se sloj uklju\u010di u vid\u017eet",label:"Sloj",labelTip:"Ime sloja kako je definisano na mapi",update:"Onemogu\u0107i izmene geometrije",updateTip:"Opcija za onemogu\u0107avanje mogu\u0107nosti pomeranja geometrije kada je jednom postavljena ili pomeranja geometrije na postoje\u0107em geoobjektu",allowUpdateOnly:"Samo a\u017euriraj",allowUpdateOnlyTip:"Opcija da se dozvoli izmena postoje\u0107ih geoobjekata, automatski potvr\u0111ena i onemogu\u0107ena ako sloj ne podr\u017eava kreiranje novih geoobjekata",
fields:"Polja",fieldsTip:"Izmeni polja koja treba izmeniti i defini\u0161i pametne atribute",description:"Opis",descriptionTip:"Opcija za unos teksta koji \u017eelite da prika\u017eete na vrhu stranice atributa."},editFieldError:"Izmene polja i pametni atributi nisu dostupni slojevima koji ne mogu da se izmene",noConfigedLayersError:"Smart Editor zahteva jedan ili vi\u0161e izmenjivih slojeva"},editDescriptionPage:{title:"Defini\u0161ite tekst za pregled atributa za \x3cb\x3e${layername}\x3c/b\x3e "},
fieldsPage:{title:"Konfiguri\u0161ite polja za \x3cb\x3e${layername}\x3c/b\x3e",description:"Koristite kolonu za Po\u010detnu vrednost da dozvolite korisniku da unese vrednost pre kreiranja novog geoobjekta. Koristite dugme za menjanje radnje za aktiviranje pametnih atributa na sloju. Pametni atributi mogu da zahtevaju, sakriju ili onemogu\u0107e polje na osnovu vrednosti u drugim poljima.",fieldsNotes:"* je obavezno polje. Ukoliko poni\u0161tite izbor \u201ePrikaz\u201c za ovo polje i \u0161ablon za menjanje ne popuni to vrednost polja, ne\u0107ete mo\u0107i da sa\u010duvate novi zapis.",
fieldsSettingsTable:{display:"Prikaz",displayTip:"Utvrdi da li polje nije vidljivo",edit:"Mo\u017ee da se izmeni",editTip:"Proveri da li je polje prisutno u obrascu atributa",fieldName:"Naziv",fieldNameTip:"Ime polja definisano u bazi podataka",fieldAlias:"Alias",fieldAliasTip:"Ime polja definisano u mapi",canPresetValue:"Predefinisano pode\u0161avanje",canPresetValueTip:"Opcija za prikazivanje polja u listi unapred pode\u0161enih polja i za omogu\u0107avanje korisniku da podesi vrednost pre menjanja",
actions:"Radnje",actionsTip:"Promeni redosled polja ili postavi pametne atribute"},smartAttSupport:"Pametni atributi nisu podr\u017eani u obaveznim poljima baze podataka"},actionPage:{title:"Konfiguri\u0161ite radnje pametnih atributa za \x3cb\x3e${fieldname}\x3c/b\x3e",description:"Radnje su uvek isklju\u010dene, osim ukoliko navedete kriterijum po kom \u0107e se aktivirati. Radnje se izvr\u0161avaju redom i samo jedna radnja \u0107e biti aktivirana po polju. Koristite dugme za izmenu kriterijuma da biste definisali kriterijum.",
actionsSettingsTable:{rule:"Radnja",ruleTip:"Radnja izvr\u0161ena kada je kriterijum zadovoljen",expression:"Izraz",expressionTip:"Rezultuju\u0107i izraz u SQL formatu od definisanog kriterijuma",actions:"Kriterijum",actionsTip:"Promeni redosled pravila i defini\u0161i kriterijum kada je aktivirano"},actions:{hide:"Sakrij",required:"Obavezno",disabled:"Onemogu\u0107eno"}},filterPage:{submitHidden:"\u017delite li da prosledite podatke o atributima za ovo polje \u010dak i kada je sakriveno?",title:"Konfiguri\u0161i izraz za ${action} pravilo",
filterBuilder:"Podesi radnju na polju kada se zapis poklapa ${any_or_all} od slede\u0107ih izraza",noFilterTip:"Pomo\u0107u alata ispod, defini\u0161ite izjavu za slu\u010daj kada je radnja aktivna."},_localized:{}}});