// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Gras",copy:"Copier",cut:"Couper","delete":"Supprimer",indent:"Retrait",insertHorizontalRule:"R\u00e8gle horizontale",insertOrderedList:"Liste num\u00e9rot\u00e9e",insertUnorderedList:"Liste \u00e0 puces",italic:"Italique",justifyCenter:"Aligner au centre",justifyFull:"Justifier",justifyLeft:"Aligner \u00e0 gauche",justifyRight:"Aligner \u00e0 droite",outdent:"Retrait n\u00e9gatif",paste:"Coller",redo:"R\u00e9tablir",removeFormat:"Supprimer la mise en forme",
selectAll:"S\u00e9lectionner tout",strikethrough:"Barrer",subscript:"Indice",superscript:"Exposant",underline:"Souligner",undo:"Annuler",unlink:"Supprimer le lien",createLink:"Cr\u00e9er un lien",toggleDir:"Changer de sens",insertImage:"Ins\u00e9rer une image",insertTable:"Ins\u00e9rer/Modifier un tableau",toggleTableBorder:"Afficher/Masquer la bordure du tableau",deleteTable:"Supprimer le tableau",tableProp:"Propri\u00e9t\u00e9 du tableau",htmlToggle:"Source HTML",foreColor:"Couleur avant-plan",
hiliteColor:"Couleur arri\u00e8re-plan",plainFormatBlock:"Style de paragraphe",formatBlock:"Style de paragraphe",fontSize:"Taille de police",fontName:"Nom de police",tabIndent:"Retrait de tabulation",fullScreen:"Basculer en plein \u00e9cran",viewSource:"Afficher la source HTML",print:"Imprimer",newPage:"Nouvelle page",systemShortcut:'Action "${0}" uniquement disponible dans votre navigateur via un raccourci clavier. Utilisez ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"tr\u00e8s tr\u00e8s petite",
2:"tr\u00e8s petite",3:"petite",4:"moyenne",5:"grande",6:"tr\u00e8s grande",7:"tr\u00e8s tr\u00e8s grande",fontSize:"Taille",fontName:"Police",formatBlock:"Mise en forme",serif:"serif","sans-serif":"sans serif",monospace:"espacement fixe",cursive:"cursive",fantasy:"fantaisie",noFormat:"N\u00e9ant",p:"Paragraphe",h1:"En-t\u00eate",h2:"Sous-en-t\u00eate",h3:"Sous-sous-en-t\u00eate",pre:"Pr\u00e9-mise en forme",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Aper\u00e7u",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Rechercher :",
findTooltip:"Entrez le texte \u00e0 rechercher",replaceLabel:"Remplacer par :",replaceTooltip:"Entrez le texte de remplacement",findReplace:"Rechercher et remplacer",matchCase:"Respecter la casse",matchCaseTooltip:"Respecter la casse",backwards:"Vers l'arri\u00e8re",backwardsTooltip:"Recherchez le texte vers l'arri\u00e8re",replaceAllButton:"Remplacer tout",replaceAllButtonTooltip:"Remplacez tout le texte",findButton:"Rechercher",findButtonTooltip:"Recherchez le texte",replaceButton:"Remplacer",replaceButtonTooltip:"Remplacez le texte",
replaceDialogText:"${0} occurrence(s) remplac\u00e9e(s)",eofDialogText:"Derni\u00e8re occurrence ${0}",eofDialogTextFind:"trouv\u00e9",eofDialogTextReplace:"remplac\u00e9",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Coller depuis Word",instructions:"Collez le contenu Word dans la zone de texte ci-dessous. Quand le contenu \u00e0 ins\u00e9rer vous convient, appuyez sur le bouton Coller. Pour annuler l'insertion du texte, utilisez le bouton Annuler.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Ins\u00e9rer un point d'ancrage",
title:"Propri\u00e9t\u00e9s du point d'ancrage",anchor:"Nom :",text:"Description :",set:"D\u00e9finir",cancel:"Annuler",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Bloc de citation",_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"S\u00e9lectionnez un mod\u00e8le pour cr\u00e9er des entit\u00e9s",generalSettings:"Param\u00e8tres g\u00e9n\u00e9raux",layerSettings:"Param\u00e8tres de la couche",editDescription:"Fournir le texte \u00e0 afficher pour la fen\u00eatre de mise \u00e0 jour",
editDescriptionTip:"Ce texte appara\u00eet au-dessus du s\u00e9lecteur de mod\u00e8les. Vous pouvez \u00e9galement n'indiquer aucun texte.",promptOnSave:"Demandez \u00e0 enregistrer les modifications non enregistr\u00e9es lors de la fermeture du formulaire ou de l'acc\u00e8s au prochain enregistrement.",promptOnSaveTip:"Affichez une invite lorsque l'utilisateur clique sur Fermer ou acc\u00e8de au prochain enregistrement modifiable alors que l'entit\u00e9 actuelle comporte des modifications non enregistr\u00e9es.",
promptOnDelete:"Demandez confirmation lors de la suppression d'un enregistrement.",promptOnDeleteTip:"Affichez une invite lorsque l'utilisateur clique sur Supprimer afin de confirmer l'action.",removeOnSave:"Supprimez l'entit\u00e9 de la s\u00e9lection lors de l'enregistrement.",removeOnSaveTip:"Option permettant de supprimer l'entit\u00e9 du jeu de s\u00e9lection lors de la sauvegarde de l'enregistrement. S'il s'agit du seul enregistrement s\u00e9lectionn\u00e9, la fen\u00eatre revient sur la page du mod\u00e8le.",
useFilterEditor:"Utiliser le filtre des mod\u00e8les d'entit\u00e9s",useFilterEditorTip:"Option permettant d'utiliser le s\u00e9lecteur des mod\u00e8les de filtre visant \u00e0 afficher un mod\u00e8le de couche ou \u00e0 rechercher des mod\u00e8les en fonction de leur nom.",listenToGroupFilter:"Appliquer des valeurs de filtre du widget Filtrer les groupes aux champs pr\u00e9d\u00e9finis",listenToGroupFilterTip:"Lorsqu'un filtre est appliqu\u00e9 dans le widget Filtrer les groupes, appliquez la valeur \u00e0 un champ d'appariement dans la liste des valeurs pr\u00e9d\u00e9finies.",
keepTemplateActive:"Conserver le mod\u00e8le s\u00e9lectionn\u00e9 actif",keepTemplateActiveTip:"Lorsque le s\u00e9lecteur de mod\u00e8les est affich\u00e9, si un mod\u00e8le a \u00e9t\u00e9 pr\u00e9c\u00e9demment s\u00e9lectionn\u00e9, res\u00e9lectionnez-le.",layerSettingsTable:{allowDelete:"Autoriser la suppression",allowDeleteTip:"Option qui permet \u00e0 l'utilisateur de supprimer une entit\u00e9. D\u00e9sactiv\u00e9e si la couche ne prend pas en charge la suppression",edit:"Modifiable",editTip:"Option permettant d'inclure la couche dans le widget",
label:"Couche",labelTip:"Nom de la couche selon la d\u00e9finition de la carte",update:"D\u00e9sactiver la mise \u00e0 jour de la g\u00e9om\u00e9trie",updateTip:"Option permettant de d\u00e9sactiver la possibilit\u00e9 de d\u00e9placement de la g\u00e9om\u00e9trie une fois positionn\u00e9e ou de d\u00e9placement de la g\u00e9om\u00e9trie sur une entit\u00e9 existante.",allowUpdateOnly:"Mettre \u00e0 jour uniquement",allowUpdateOnlyTip:"Option autorisant uniquement la modification des entit\u00e9s existantes. S\u00e9lectionn\u00e9e par d\u00e9faut et d\u00e9s\u00e9lectionn\u00e9e si la couche ne prend pas en charge la cr\u00e9ation de nouvelles entit\u00e9s.",
fields:"Champs",fieldsTip:"Modifier les champs \u00e0 mettre \u00e0 jour et d\u00e9finir les attributs intelligents",description:"Description",descriptionTip:"Option permettant de saisir le texte \u00e0 afficher au-dessus de la page des attributs."},editFieldError:"Les modifications de champ et les attributs intelligents ne sont pas disponibles dans les couches non modifiables",noConfigedLayersError:"Le widget Editeur intelligent requiert une ou plusieurs couches modifiables"},editDescriptionPage:{title:"D\u00e9finir le texte de vue d'ensemble des attributs de \x3cb\x3e${layername}\x3c/b\x3e "},
fieldsPage:{title:"Configurer les champs de \x3cb\x3e${layername}\x3c/b\x3e",description:"Utilisez la colonne Pr\u00e9d\u00e9fini pour autoriser l'utilisateur \u00e0 saisir une valeur avant de cr\u00e9er une nouvelle entit\u00e9. Utilisez le bouton de mise \u00e0 jour des actions pour activer les attributs intelligents sur une couche. Les attributs intelligents peuvent requ\u00e9rir, masquer ou d\u00e9sactiver un champ en fonction des valeurs pr\u00e9sentes dans d'autres champs.",fieldsNotes:"* est un champ obligatoire. Si vous d\u00e9sactivez Affichage pour ce champ, et que le mod\u00e8le de mise \u00e0 jour ne renseigne pas cette valeur de champ, vous ne pourrez pas enregistrer de nouvel enregistrement.",
fieldsSettingsTable:{display:"Affichage",displayTip:"D\u00e9terminer si le champ n'est pas visible",edit:"Modifiable",editTip:"Activer si le champ est pr\u00e9sent dans le formulaire d'attribut",fieldName:"Nom",fieldNameTip:"Nom du champ d\u00e9fini dans la base de donn\u00e9es",fieldAlias:"Alias",fieldAliasTip:"Nom du champ d\u00e9fini dans la carte",canPresetValue:"Pr\u00e9d\u00e9fini",canPresetValueTip:"Option permettant d'afficher le champ dans la liste des champs pr\u00e9d\u00e9finis et d'autoriser l'utilisateur \u00e0 d\u00e9finir la valeur avant la mise \u00e0 jour",
actions:"Actions",actionsTip:"Modifier l'ordre des champs ou configurer les attributs intelligents"},smartAttSupport:"Les attributs intelligents ne sont pas pris en charge dans les champs de base de donn\u00e9es requis"},actionPage:{title:"Configurer les actions des attributs intelligents de \x3cb\x3e${fieldname}\x3c/b\x3e",description:"Les actions sont toujours d\u00e9sactiv\u00e9es sauf si vous sp\u00e9cifiez leurs crit\u00e8res de d\u00e9clenchement. Les actions sont trait\u00e9es par ordre et une seule action est d\u00e9clench\u00e9e par champ. Utilisez le bouton de mise \u00e0 jour des crit\u00e8res pour d\u00e9finir ces derniers.",
actionsSettingsTable:{rule:"Op\u00e9ration",ruleTip:"Action effectu\u00e9e une fois le crit\u00e8re rempli",expression:"Expression",expressionTip:"L'expression obtenue au format SQL \u00e0 partir des crit\u00e8res d\u00e9finis",actions:"Crit\u00e8re",actionsTip:"Modifier l'ordre de la r\u00e8gle et d\u00e9finir les crit\u00e8res lors de son d\u00e9clenchement"},actions:{hide:"Masquer",required:"Obligatoire",disabled:"D\u00e9sactiv\u00e9"}},filterPage:{submitHidden:"Soumettre les donn\u00e9es attributaires de ce champ m\u00eame s'il est masqu\u00e9\u00a0?",
title:"Configurer l'expression de la r\u00e8gle ${action}",filterBuilder:"D\u00e9finir l'action sur le champ lorsque l'enregistrement correspond \u00e0 ${any_or_all} des expressions suivantes",noFilterTip:"A l'aide des outils ci-dessous, d\u00e9finissez l'instruction indiquant la p\u00e9riode d'activit\u00e9 de l'action."},_localized:{}}});