// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fett",copy:"Kopieren",cut:"Ausschneiden","delete":"L\u00f6schen",indent:"Einr\u00fccken",insertHorizontalRule:"Horizontaler Strich",insertOrderedList:"Nummerierung",insertUnorderedList:"Aufz\u00e4hlungszeichen",italic:"Kursiv",justifyCenter:"Zentriert",justifyFull:"Blocksatz",justifyLeft:"Linksb\u00fcndig",justifyRight:"Rechtsb\u00fcndig",outdent:"Ausr\u00fccken",paste:"Einf\u00fcgen",redo:"Wiederholen",removeFormat:"Formatierung entfernen",selectAll:"Alles ausw\u00e4hlen",
strikethrough:"Durchgestrichen",subscript:"Tiefgestellt",superscript:"Hochgestellt",underline:"Unterstrichen",undo:"R\u00fcckg\u00e4ngig",unlink:"Link entfernen",createLink:"Link erstellen",toggleDir:"Richtung wechseln",insertImage:"Grafik einf\u00fcgen",insertTable:"Tabelle einf\u00fcgen/bearbeiten",toggleTableBorder:"Tabellenumrandung ein-/ausschalten",deleteTable:"Tabelle l\u00f6schen",tableProp:"Tabelleneigenschaft",htmlToggle:"HTML-Quelltext",foreColor:"Vordergrundfarbe",hiliteColor:"Hintergrundfarbe",
plainFormatBlock:"Absatzstil",formatBlock:"Absatzstil",fontSize:"Schriftgr\u00f6\u00dfe",fontName:"Schriftartname",tabIndent:"Registerkarteneinr\u00fcckung",fullScreen:"Gesamtanzeige",viewSource:"HTML-Quelle",print:"Drucken",newPage:"Neue Seite",systemShortcut:'Die Aktion "${0}" ist nur \u00fcber einen Direktaufruf in Ihrem Browser verf\u00fcgbar. Verwenden Sie ${1}.',ctrlKey:"Strg+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"XXS",2:"XS",3:"S",4:"M",5:"L",6:"XL",7:"XXL",
fontSize:"Gr\u00f6\u00dfe",fontName:"Schriftart",formatBlock:"Format",serif:"Serife","sans-serif":"Serifenlos",monospace:"Monospaceschrift",cursive:"Kursiv",fantasy:"Fantasie",noFormat:"Keine Angabe",p:"Absatz",h1:"\u00dcberschrift",h2:"Unter\u00fcberschrift",h3:"Unterunter\u00fcberschrift",pre:"Vorformatiert",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Vorschau",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Suchen:",findTooltip:"Text zum Suchen eingeben",replaceLabel:"Ersetzen durch:",
replaceTooltip:"Text zum Ersetzen eingeben",findReplace:"Suchen und ersetzen",matchCase:"Gro\u00df- und Kleinschreibung abgleichen",matchCaseTooltip:"Gro\u00df- und Kleinschreibung abgleichen",backwards:"Zur\u00fcck",backwardsTooltip:"R\u00fcckw\u00e4rts nach Text suchen",replaceAllButton:"Global ersetzen",replaceAllButtonTooltip:"Gesamten Text ersetzen",findButton:"Suchen",findButtonTooltip:"Text suchen",replaceButton:"Ersetzen",replaceButtonTooltip:"Text ersetzen",replaceDialogText:"${0} Vorkommen ersetzt.",
eofDialogText:"Letztes Vorkommen ${0}",eofDialogTextFind:"gefunden",eofDialogTextReplace:"ersetzt",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Aus Word einf\u00fcgen",instructions:"F\u00fcgt den Inhalt aus Word in das Textfeld unten ein. Wenn Sie mit dem einzuf\u00fcgenden Inhalt zufrieden sind, klicken Sie auf die Schaltfl\u00e4che zum Einf\u00fcgen. Um das Einf\u00fcgen von Text abzubrechen, klicken Sie auf die Schaltfl\u00e4che zum Abbrechen. ",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Anker einf\u00fcgen",
title:"Eigenschaften des Ankers",anchor:"Name:",text:"Beschreibung:",set:"Festlegen",cancel:"Abbrechen",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockzitat",_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Vorlage zur Feature-Erstellung ausw\u00e4hlen",generalSettings:"Allgemeine Einstellungen",layerSettings:"Layer-Einstellungen",editDescription:"Anzeigetext f\u00fcr den Bearbeitungsbereich bereitstellen",editDescriptionTip:"Dieser Text wird \u00fcber der Vorlagenauswahl angezeigt; lassen Sie ihn leer.",
promptOnSave:"Zum Speichern nicht gespeicherter \u00c4nderungen auffordern, wenn das Formular geschlossen oder zum n\u00e4chsten Datensatz gewechselt wird",promptOnSaveTip:'Es wird eine Eingabeaufforderung angezeigt, wenn der Benutzer auf "Schlie\u00dfen" klickt oder zum n\u00e4chsten editierbaren Datensatz navigiert, wenn das aktuelle Feature nicht gespeicherte \u00c4nderungen enth\u00e4lt.',promptOnDelete:"Beim L\u00f6schen eines Datensatzes eine Best\u00e4tigung anfordern",promptOnDeleteTip:'Es wird eine Eingabeaufforderung angezeigt, wenn der Benutzer auf "L\u00f6schen" klickt, um die Aktion zu best\u00e4tigen.',
removeOnSave:"Das Feature beim Speichern aus der Auswahl entfernen",removeOnSaveTip:"Option zum Entfernen des Features aus dem Auswahlsatz, wenn der Datensatz gespeichert wird.  Wenn dies der einzige ausgew\u00e4hlte Datensatz ist, wechselt der Bereich zur\u00fcck zur Vorlagenseite.",useFilterEditor:"Feature-Vorlagenfilter verwenden",useFilterEditorTip:"Option zum Verwenden der Filtervorlagenauswahl, die es erm\u00f6glicht, die Vorlagen eines Layers anzuzeigen oder Vorlagen nach Name zu suchen.",
listenToGroupFilter:'Filterwerte aus dem Widget "Gruppenfilter" auf voreingestellte Felder anwenden',listenToGroupFilterTip:'Wenn ein Filter im Widget "Gruppenfilter" angewendet wird, wird der Wert auf ein \u00fcbereinstimmendes Feld in der Liste der voreingestellten Werte angewendet.',keepTemplateActive:"Ausgew\u00e4hlte Vorlage aktiviert lassen",keepTemplateActiveTip:"Wenn die Vorlagenauswahl angezeigt wird, wird die zuvor ausgew\u00e4hlte Vorlage erneut ausgew\u00e4hlt.",layerSettingsTable:{allowDelete:"L\u00f6schen zulassen",
allowDeleteTip:"Option, die Benutzern das L\u00f6schen eines Features erm\u00f6glicht; sie ist deaktiviert, wenn der Layer die L\u00f6schfunktion nicht unterst\u00fctzt.",edit:"Editierbar",editTip:"Option zum Einbeziehen des Layers in das Widget",label:"Layer",labelTip:"Name des Layers gem\u00e4\u00df der Definition in der Karte",update:"Geometriebearbeitung deaktivieren",updateTip:"Option zum Deaktivieren der Bearbeitung der Geometrie, nachdem sie platziert wurde, bzw. f\u00fcr ein vorhandenes Feature",
allowUpdateOnly:"Nur Update",allowUpdateOnlyTip:"Option, die lediglich die \u00c4nderung vorhandener Features zul\u00e4sst; sie ist standardm\u00e4\u00dfig aktiviert, jedoch deaktiviert, wenn der Layer die Erstellung neuer Features nicht zul\u00e4sst.",fields:"Felder",fieldsTip:"Die zu bearbeitenden Felder \u00e4ndern und intelligente Attribute definieren",description:"Beschreibung",descriptionTip:"Option zum Eingeben von Text, der im oberen Bereich der Attributseite angezeigt werden soll"},editFieldError:"Feld\u00e4nderungen und intelligente Attribute sind f\u00fcr nicht editierbare Layer nicht verf\u00fcgbar.",
noConfigedLayersError:"Smart Editor erfordert mindestens einen editierbaren Layer"},editDescriptionPage:{title:"\u00dcbersichtstext f\u00fcr \x3cb\x3e${layername}\x3c/b\x3e definieren "},fieldsPage:{title:"Felder f\u00fcr \x3cb\x3e${layername}\x3c/b\x3e konfigurieren",description:'Verwenden Sie die Spalte "Voreinstellung", um vor dem Erstellen eines neuen Features einen Wert einzugeben. Verwenden Sie die Schaltfl\u00e4che zum Bearbeiten von Aktionen, um intelligente Attribute f\u00fcr einen Layer zu aktivieren. Intelligente Attribute k\u00f6nnen ein Feld basierend auf Werten in anderen Feldern erfordern, ausblenden oder deaktivieren.',
fieldsNotes:'* Erforderliches Feld. Wenn "Anzeigen" f\u00fcr dieses Feld deaktiviert wird und die Bearbeitungsvorlage diesen Feldwert nicht f\u00fcllt, k\u00f6nnen Sie keinen neuen Datensatz speichern.',fieldsSettingsTable:{display:"Anzeigen",displayTip:"Festlegen, ob das Feld unsichtbar sein soll",edit:"Editierbar",editTip:"Aktivieren, wenn das Feld im Attributformular vorhanden sein soll",fieldName:"Name",fieldNameTip:"Name des in der Datenbank definierten Feldes",fieldAlias:"Alias",fieldAliasTip:"Name des in der Karte definierten Feldes",
canPresetValue:"Voreinstellung",canPresetValueTip:"Option, mit der das Feld in der Liste der voreingestellten Felder angezeigt wird und die es dem Benutzer erm\u00f6glicht, den Wert vor der Bearbeitung festzulegen",actions:"Aktionen",actionsTip:"Die Reihenfolge der Felder \u00e4ndern oder intelligente Attribute einrichten"},smartAttSupport:"Intelligente Attribute werden f\u00fcr erforderliche Datenbankfelder nicht unterst\u00fctzt."},actionPage:{title:"Aktionen f\u00fcr intelligente Attribute f\u00fcr \x3cb\x3e${fieldname}\x3c/b\x3e konfigurieren",
description:'Die Aktionen sind immer deaktiviert, es sei denn, Sie legen die Kriterien f\u00fcr deren Ausl\u00f6sung fest.  Die Aktionen werden der Reihenfolge nach verarbeitet und pro Feld wird nur eine Aktion ausgel\u00f6st.  Verwenden Sie zum Festlegen der Kriterien die Schaltfl\u00e4che "Kriterien bearbeiten".',actionsSettingsTable:{rule:"Aktion",ruleTip:"Aktion, die bei Erf\u00fcllung der Kriterien durchgef\u00fchrt wird",expression:"Ausdruck",expressionTip:"Der resultierende Ausdruck im SQL-Format aus den definierten Kriterien",
actions:"Kriterien",actionsTip:"Die Reihenfolge der Regel \u00e4ndern und die Kriterien f\u00fcr deren Ausl\u00f6sung definieren"},actions:{hide:"Ausblenden",required:"Erforderlich",disabled:"Deaktiviert"}},filterPage:{submitHidden:"Attributdaten f\u00fcr dieses Feld auch dann senden, wenn es ausgeblendet ist?",title:"Ausdruck f\u00fcr die ${action}-Regel konfigurieren",filterBuilder:"Aktion f\u00fcr das Feld festlegen, wenn der Datensatz mit ${any_or_all} der folgenden Ausdr\u00fccke \u00fcbereinstimmt",
noFilterTip:"Definieren Sie mit den folgenden Werkzeugen die Anweisung f\u00fcr den Zeitraum, in dem die Aktion aktiv ist."},_localized:{}}});