// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Rasvane",copy:"Kopeeri",cut:"L\u00f5ika","delete":"Kustuta",indent:"Paremtaane",insertHorizontalRule:"Horisontaaljoon",insertOrderedList:"Nummerdatud loend",insertUnorderedList:"T\u00e4pploend",italic:"Kursiiv",justifyCenter:"Keskjoondus",justifyFull:"R\u00f6\u00f6pjoondus",justifyLeft:"Vasakjoondus",justifyRight:"Paremjoondus",outdent:"Vasaktaane",paste:"Kleebi",redo:"Tee uuesti",removeFormat:"Eemalda vorming",selectAll:"Vali k\u00f5ik",strikethrough:"L\u00e4bikriipsutus",
subscript:"Allindeks",superscript:"\u00dclaindeks",underline:"Allajoonitud",undo:"T\u00fchista",unlink:"Eemalda link",createLink:"Loo link",toggleDir:"Vaheta suund",insertImage:"Sisesta pilt",insertTable:"Lisa/muuda tabelit",toggleTableBorder:"L\u00fclita tabeli\u00e4\u00e4ris sisse/v\u00e4lja",deleteTable:"Kustuta tabel",tableProp:"Tabeli atribuut",htmlToggle:"HTML-l\u00e4htetekst",foreColor:"Esiv\u00e4rv",hiliteColor:"Taustav\u00e4rv",plainFormatBlock:"L\u00f5igu laad",formatBlock:"L\u00f5igu laad",
fontSize:"Fondi suurus",fontName:"Fondi nimi",tabIndent:"Tabeldustaane",fullScreen:"L\u00fclita t\u00e4isekraan sisse/v\u00e4lja",viewSource:"Kuva HTML-l\u00e4htetekst",print:"Prindi",newPage:"Uus leht",systemShortcut:"Seda toimingut ${0} saab Teie brauseris teha ainult kiirklahvi abil. Kasutage klahvikombinatsiooni ${1}.",ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"eriti v\u00e4ike",2:"v\u00e4ga v\u00e4ike",3:"v\u00e4ike",4:"keskmine",5:"suur",6:"v\u00e4ga suur",
7:"eriti suur",fontSize:"Suurus",fontName:"Font",formatBlock:"Formaat",serif:"seriifidega","sans-serif":"groteskkiri",monospace:"p\u00fcsisamm",cursive:"kursiiv",fantasy:"fantaasia",noFormat:"Puudub",p:"L\u00f5ik",h1:"Pealkiri",h2:"Alapealkiri",h3:"Ala-alapealkiri",pre:"Eelvormindatud",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Preview",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Find:",findTooltip:"Enter text to find",replaceLabel:"Replace with:",replaceTooltip:"Enter text to replace with",
findReplace:"Find and Replace",matchCase:"Match case",matchCaseTooltip:"Match case",backwards:"Backwards",backwardsTooltip:"Search backwards for text",replaceAllButton:"Replace All",replaceAllButtonTooltip:"Replace all the text",findButton:"Find",findButtonTooltip:"Find the text",replaceButton:"Replace",replaceButtonTooltip:"Replace the text",replaceDialogText:"Replaced ${0} occurrences.",eofDialogText:"Last occurrence ${0}",eofDialogTextFind:"found",eofDialogTextReplace:"replaced",_localized:{}},
"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Paste From Word",instructions:"Paste the content from Word into the text box below.  Once you are satisfied with the content to insert, press the paste button.  To abort inserting text, press the cancel button.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Insert Anchor",title:"Anchor Properties",anchor:"Name:",text:"Description:",set:"Set",cancel:"Cancel",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",
_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Valige objektide loomiseks mall",generalSettings:"\u00dcldseaded",layerSettings:"Kihi seaded",editDescription:"Sisestage redigeerimispaneelil kuvatav tekst",editDescriptionTip:"See tekst kuvatakse mallivalija kohal. Kui te ei soovi teksti kuvada, j\u00e4tke t\u00fchjaks.",promptOnSave:"Viip salvestamata muudatuste salvestamiseks, kui vorm suletakse v\u00f5i valitakse j\u00e4rgmine kirje.",promptOnSaveTip:"Kui kasutaja kl\u00f5psab sulgemisnuppu v\u00f5i liigub j\u00e4rgmisele redigeeritavale kirjele ja praegusel objektil on salvestamata muudatusi, kuvatakse see viip.",
promptOnDelete:"Kirje kustutamisel n\u00f5utakse kinnitust.",promptOnDeleteTip:"Kui kasutaja kl\u00f5psab toimingu kinnitamiseks kustutamisnuppu, kuvatakse see viip.",removeOnSave:"Salvestamisel eemaldatakse objekt valikust.",removeOnSaveTip:"Valik objekti eemaldamiseks valitud komplektist, kui kirjet salvestatakse. Kui see on ainus valitud kirje, l\u00fclitub paneel tagasi mallilehele.",useFilterEditor:"Kasuta objekti malli filtrit",useFilterEditorTip:"Valik filtrimalli valija kasutamiseks, mille abil saab vaadata \u00fche kihi malle v\u00f5i otsida malle nime j\u00e4rgi.",
listenToGroupFilter:"Grupeerimise filtri vidina filtriv\u00e4\u00e4rtuste rakendamine eelseatud v\u00e4ljadele",listenToGroupFilterTip:"Kui filter on rakendatud r\u00fchmafiltri vidinas, rakendage v\u00e4\u00e4rtus vastavale v\u00e4ljale eelseatud v\u00e4\u00e4rtuste loendis.",keepTemplateActive:"Valitud malli hoidmine aktiivsena",keepTemplateActiveTip:"Kui mall oli eelnevalt valitud, valige see mallivalija kuvamise korral uuesti.",layerSettingsTable:{allowDelete:"Luba kustutamine",allowDeleteTip:"Valik, mis lubab kasutajal objekti kustutada. Kui kiht ei toeta kustutamist, on see valik keelatud.",
edit:"Muudetav",editTip:"Valik kihi kaasamiseks vidinasse",label:"Kiht",labelTip:"Kihi nimi\u00a0kaardil m\u00e4\u00e4ratletud kujul",update:"Keela geomeetria muutmine",updateTip:"Valik geomeetria teisaldamise keelamiseks\u00a0p\u00e4rast selle paigutamist v\u00f5i olemasolevale objektile",allowUpdateOnly:"Ainult uuenda",allowUpdateOnlyTip:"Valik ainult olemasolevate objektide muutmiseks.\u00a0Seda kontrollitakse vaikimisi\u00a0ja see on v\u00e4lja l\u00fclitatud,\u00a0kui kiht ei toeta uute objektide loomist.",
fields:"V\u00e4ljad",fieldsTip:"Saate muuta redigeeritavaid v\u00e4lju ja m\u00e4\u00e4ratleda nutikad atribuudid",description:"Kirjeldus",descriptionTip:"V\u00f5imalus sisestada atribuudilehe \u00fclaosas kuvatav tekst."},editFieldError:"Mittemuudetavate kihtide korral ei saa v\u00e4lju\u00a0muuta ja nutikad atribuudid pole saadaval",noConfigedLayersError:"Smart Editor n\u00f5uab mitut muudetavat kihti"},editDescriptionPage:{title:"M\u00e4\u00e4ratle kihi\u00a0\x3cb\x3e${layername}\x3c/b\x3e atribuutide \u00fclevaate tekst "},
fieldsPage:{title:"Konfigureeri kihi \x3cb\x3e${layername}\x3c/b\x3e\u00a0v\u00e4ljad",description:"Kasutage veergu Eelseatud, et lubada kasutajal sisestada v\u00e4\u00e4rtus enne uue objekti loomist.\u00a0Kasutage kihi nutikate atribuutide\u00a0aktiveerimiseks toimingute redigeerimise nuppu. Nutikad atribuudid v\u00f5ivad n\u00f5uda muudel v\u00e4ljadel olevate v\u00e4\u00e4rtustel p\u00f5hineva v\u00e4lja olemassolu v\u00f5i nende peitmist v\u00f5i keelamist.",fieldsNotes:"* on n\u00f5utav v\u00e4li. Kui t\u00fchistate selle v\u00e4lja puhul m\u00e4rkeruudu Kuva valiku ja redigeerimismall ei t\u00e4ida seda v\u00e4lja v\u00e4\u00e4rtusega, ei saa te uut kirjet salvestada.",
fieldsSettingsTable:{display:"Kuva",displayTip:"M\u00e4\u00e4rake, kas v\u00e4li on n\u00e4htav v\u00f5i mitte",edit:"Muudetav",editTip:"Kontrollige, kas v\u00e4li on atribuudi vormil olemas",fieldName:"Nimi",fieldNameTip:"V\u00e4lja nimi, mis on\u00a0andmebaasis m\u00e4\u00e4ratletud",fieldAlias:"Alias",fieldAliasTip:"V\u00e4lja nimi, mis on\u00a0kaardil m\u00e4\u00e4ratletud",canPresetValue:"Eelseatud",canPresetValueTip:"Valik v\u00e4lja kuvamiseks eelseatud v\u00e4ljade loendis ja selleks, et lubada kasutajal\u00a0m\u00e4\u00e4rata v\u00e4\u00e4rtuse enne muutmist",
actions:"Toimingud",actionsTip:"Saate muuta v\u00e4ljade j\u00e4rjestust v\u00f5i seadistada nutikad atribuudid"},smartAttSupport:"N\u00f5utavad andmebaasi v\u00e4ljad ei toeta nutikaid atribuute"},actionPage:{title:"Konfigureerige v\u00e4lja \x3cb\x3e${fieldname}\x3c/b\x3e\u00a0nutikate atribuutide toimingud",description:"Need toimingud on alati v\u00e4lja l\u00fclitatud, v\u00e4lja arvatud juhul, kui m\u00e4\u00e4ratlete kriteeriumid, mille korral need sisse l\u00fclituvad. Toiminguid t\u00f6\u00f6deldakse\u00a0etten\u00e4htud j\u00e4rjestuses ja iga v\u00e4lja kohta l\u00fclitatakse sisse ainult \u00fcks toiming. Kriteeriumide m\u00e4\u00e4ratlemiseks kasutage nuppu Kriteeriumide muutmine.",
actionsSettingsTable:{rule:"Tegevus",ruleTip:"Kriteeriumidele vastavuse korral tehtav toiming",expression:"V\u00e4ljend",expressionTip:"M\u00e4\u00e4ratletud kriteeriumide alusel\u00a0saadav avaldis\u00a0SQL-vormingus",actions:"Kriteeriumid",actionsTip:"Saate muuta reegli j\u00e4rjestust ja m\u00e4\u00e4ratleda selle sissel\u00fclitumise\u00a0kriteeriumid"},actions:{hide:"Peida",required:"N\u00f5utav",disabled:"Keelatud"}},filterPage:{submitHidden:"Kas edastada selle v\u00e4lja kohta\u00a0atribuudi andmed isegi siis, kui see on peidetud?",
title:"Konfigureerige\u00a0toimingu\u00a0${action} reegli avaldis",filterBuilder:"Saate m\u00e4\u00e4rata v\u00e4ljale toimingu, kui kirje vastab ${any_or_all} j\u00e4rgmistele avaldistele",noFilterTip:"M\u00e4\u00e4ratlege allj\u00e4rgnevate t\u00f6\u00f6riistade abil avaldus, mille korral toiming on aktiivne."},_localized:{}}});