// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Fet",copy:"Kopier",cut:"Klipp ut","delete":"Slett",indent:"Innrykk",insertHorizontalRule:"Vannrett strek",insertOrderedList:"Nummerert liste",insertUnorderedList:"Punktliste",italic:"Kursiv",justifyCenter:"Midtstill",justifyFull:"Juster",justifyLeft:"Venstrejuster",justifyRight:"H\u00f8yrejuster",outdent:"Fjern innrykk",paste:"Lim inn",redo:"Gj\u00f8r om",removeFormat:"Fjern format",selectAll:"Velg alle",strikethrough:"Gjennomstreking",subscript:"Senket skrift",
superscript:"Hevet skrift",underline:"Understreking",undo:"Angre",unlink:"Fjern kobling",createLink:"Opprett kobling",toggleDir:"Bytt retning",insertImage:"Sett inn bilde",insertTable:"Sett inn/rediger tabell",toggleTableBorder:"Bytt tabellkant",deleteTable:"Slett tabell",tableProp:"Tabellegenskap",htmlToggle:"HTML-kilde",foreColor:"Forgrunnsfarge",hiliteColor:"Bakgrunnsfarge",plainFormatBlock:"Avsnittsstil",formatBlock:"Avsnittsstil",fontSize:"Skriftst\u00f8rrelse",fontName:"Skriftnavn",tabIndent:"Tabulatorinnrykk",
fullScreen:"Sl\u00e5 p\u00e5/av full skjerm",viewSource:"Vis HTML-kilde",print:"Skriv ut",newPage:"Ny side",systemShortcut:'Handlingen "${0}" er bare tilgjengelig i nettleseren ved hjelp av en tastatursnarvei. Bruk ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"xx-liten",2:"x-liten",3:"liten",4:"middels",5:"stor",6:"x-stor",7:"xx-stor",fontSize:"St\u00f8rrelse",fontName:"Skrift",formatBlock:"Format",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",
cursive:"kursiv",fantasy:"fantasi",noFormat:"Ingen",p:"Avsnitt",h1:"Overskrift",h2:"Undertittel",h3:"Under-undertittel",pre:"Forh\u00e5ndsformatert",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Forh\u00e5ndsvis",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"S\u00f8k:",findTooltip:"Skriv inn teksten du vil s\u00f8ke etter",replaceLabel:"Erstatt med:",replaceTooltip:"Skriv inn teksten du vil erstatte med",findReplace:"S\u00f8k og erstatt",matchCase:"Skill mellom store og sm\u00e5 bokstaver",
matchCaseTooltip:"Skill mellom store og sm\u00e5 bokstaver",backwards:"Bakover",backwardsTooltip:"S\u00f8k bakover etter tekst",replaceAllButton:"Erstatt alle",replaceAllButtonTooltip:"Erstatt all tekst",findButton:"S\u00f8k",findButtonTooltip:"S\u00f8k etter teksten",replaceButton:"Erstatt",replaceButtonTooltip:"Erstatt teksten",replaceDialogText:"Erstattet ${0} forekomster.",eofDialogText:"Siste forekomst ${0}",eofDialogTextFind:"funnet",eofDialogTextReplace:"erstattet",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Lim inn fra Word",
instructions:"Lim inn innhold fra Word til tekstboksen nedenfor. N\u00e5r du er forn\u00f8yd med innholdet du skal sette inn, trykker du p\u00e5 innlimingsknappen. Hvis du vil avbryte innsettingen av teksten, trykker du p\u00e5 avbruddsknappen.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Sett inn anker",title:"Ankeregenskaper",anchor:"Navn:",text:"Beskrivelse:",set:"Definer",cancel:"Avbryt",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blokksitat",_localized:{}},
"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Velg mal for \u00e5 opprette geoobjekter",generalSettings:"Generelle innstillinger",layerSettings:"Laginnstillinger",editDescription:"Angi visningstekst for redigeringspanelet",editDescriptionTip:"Teksten vises over malvelgeren. La st\u00e5 tomt om du ikke \u00f8nsker tekst.",promptOnSave:"Sp\u00f8r om endringer skal lagres n\u00e5r skjemaet lukkes eller g\u00e5r til neste post.",promptOnSaveTip:"Vis en melding n\u00e5r brukeren klikker p\u00e5 Lukk eller navigerer til neste redigerbare post hvis det er ulagrede endringer for gjeldende geoobjekt.",
promptOnDelete:"Be om bekreftelse ved sletting av post.",promptOnDeleteTip:"Vis en melding som ber brukeren bekrefte slettingen.",removeOnSave:"Fjern geoobjekt fra utvalg ved lagring.",removeOnSaveTip:"Alternativ for \u00e5 fjerne geoobjektet fra utvalget som er angitt n\u00e5r posten lagres. Hvis posten er den eneste valgte posten, g\u00e5r panelet tilbake til \u00e5 vise malsiden.",useFilterEditor:"Bruk geoobjektmal-filter",useFilterEditorTip:"Alternativ for bruk av filtermalvelgeren som gj\u00f8r det mulig \u00e5 vise malene for ett lag eller s\u00f8ke etter maler basert p\u00e5 navn.",
listenToGroupFilter:"Bruk filterverdier fra widgeten Grupper filter i Forh\u00e5ndsinnstilte felt",listenToGroupFilterTip:"N\u00e5r et filter brukes i widgeten Grupper filter, bruker du verdien i et tilsvarende felt i listen Forh\u00e5ndsinnstilte verdier.",keepTemplateActive:"Hold valgt mal aktiv",keepTemplateActiveTip:"Hvis en mal tidligere ble valgt n\u00e5r malvelgeren vises, velger du den p\u00e5 nytt.",layerSettingsTable:{allowDelete:"Tillat sletting",allowDeleteTip:"Alternativ som tillater at brukeren sletter et geoobjekt. Deaktivert dersom laget ikke st\u00f8tter sletting.",
edit:"Redigerbar",editTip:"Alternativ for \u00e5 inkludere laget i miniprogrammet",label:"Lag",labelTip:"Navn p\u00e5 laget slik det er definert i kartet",update:"Deaktiver redigering for geometri",updateTip:"Alternativ som deaktiverer muligheten til \u00e5 flytte geometrien etter at den er plassert  eller flytte geometrien p\u00e5 et eksisterende geoobjekt",allowUpdateOnly:"Kun oppdatering",allowUpdateOnlyTip:"Alternativ som kun tillater endring av eksisterende geoobjekter. Standardinnstillingen er at alternativet er valgt. Alternativet er deaktivert hvis laget ikke st\u00f8tter oppretting av nye geoobjekter.",
fields:"Felter",fieldsTip:"Endre feltene som skal redigeres og definer Smart-attributter",description:"Beskrivelse",descriptionTip:"Alternativ for \u00e5 skrive inn tekst som skal vises \u00f8verst p\u00e5 siden med attributter."},editFieldError:"Det er ikke mulig \u00e5 endre felt og smarte attributter i lag som ikke er redigerbare",noConfigedLayersError:"Smart redigering krever ett eller flere redigerbare lag"},editDescriptionPage:{title:"Angi tekst for attributtoversikt for \x3cb\x3e${layername}\x3c/b\x3e "},
fieldsPage:{title:"Konfigurer felter for \x3cb\x3e${layername}\x3c/b\x3e",description:"Bruk Forh\u00e5ndsdefinert-kolonnen til \u00e5 gi brukerne tilgang til \u00e5 angi en verdi f\u00f8r opprettelsen av et nytt geoobjekt. Bruk knappen for redigering av handlinger til \u00e5 aktivere smarte attributter i et lag. Smarte attributter kan kreve, skjule eller deaktivere et felt basert p\u00e5 verdier i andre felt.",fieldsNotes:"* obligatorisk felt. Hvis du fjerner merket for Vis for dette feltet, og redigeringsmalen ikke fyller inn denne feltverdien, kan du ikke lagre en ny post.",
fieldsSettingsTable:{display:"Vis",displayTip:"Angi om feltet ikke er synlig",edit:"Redigerbar",editTip:"Merk av for dette hvis feltet finnes i attributtskjemaet",fieldName:"Navn",fieldNameTip:"Navnet p\u00e5 feltet definert i databasen",fieldAlias:"Alias",fieldAliasTip:"Navnet p\u00e5 feltet definert i kartet",canPresetValue:"Forh\u00e5ndsinnstilt",canPresetValueTip:"Alternativ for \u00e5 vise feltet i listen over forh\u00e5ndsinnstilte felt og tillate at brukeren angir verdien f\u00f8r redigering",
actions:"Handlinger",actionsTip:"Endre rekkef\u00f8lgen p\u00e5 feltene, eller konfigurer smarte attributter"},smartAttSupport:"Smarte attributter st\u00f8ttes ikke i obligatoriske databasefelt"},actionPage:{title:"Konfigurer handlinger for smarte attributter for \x3cb\x3e${fieldname}\x3c/b\x3e",description:"Disse handlingene er alltid deaktivert med mindre du angir vilk\u00e5rene som skal utl\u00f8se dem. Handlingene behandles i rekkef\u00f8lge, og det utl\u00f8ses kun \u00e9n handling per felt. Bruk knappen for redigering av vilk\u00e5r til \u00e5 definere vilk\u00e5rene.",
actionsSettingsTable:{rule:"Handling",ruleTip:"Handling som utf\u00f8res n\u00e5r vik\u00e5rene oppfylles",expression:"Uttrykk",expressionTip:"Resulterende uttrykk i SQL-format fra de definerte vilk\u00e5rene",actions:"Vilk\u00e5r",actionsTip:"Endre rekkef\u00f8lgen for regelen og definer vilk\u00e5rene for n\u00e5r den utl\u00f8ses"},actions:{hide:"Skjul",required:"P\u00e5krevd",disabled:"Deaktivert"}},filterPage:{submitHidden:"Sende inn attributtdata for dette feltet selv om det er skjult?",title:"Konfigurer uttrykk for regelen ${action}",
filterBuilder:"Angi handling for feltet n\u00e5r posten samsvarer med ${any_or_all} av f\u00f8lgende uttrykk",noFilterTip:"Bruk verkt\u00f8yene nedenfor til \u00e5 definere uttrykket for n\u00e5r handlingen er aktiv."},_localized:{}}});