// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negrito",copy:"Copiar",cut:"Recortar","delete":"Excluir",indent:"Recuar",insertHorizontalRule:"R\u00e9gua Horizontal",insertOrderedList:"Lista Numerada",insertUnorderedList:"Lista com Marcadores",italic:"It\u00e1lico",justifyCenter:"Alinhar pelo Centro",justifyFull:"Justificar",justifyLeft:"Alinhar pela Esquerda",justifyRight:"Alinhar pela Direita",outdent:"N\u00e3o-chanfrado",paste:"Colar",redo:"Refazer",removeFormat:"Remover Formato",selectAll:"Selecionar Todos",
strikethrough:"Tachado",subscript:"Subscrito",superscript:"Sobrescrito",underline:"Sublinhado",undo:"Desfazer",unlink:"Remover Link",createLink:"Criar Link",toggleDir:"Comutar Dire\u00e7\u00e3o",insertImage:"Inserir Imagem",insertTable:"Inserir/Editar Tabela",toggleTableBorder:"Alternar Moldura da Tabela",deleteTable:"Excluir Tabela",tableProp:"Propriedade da Tabela",htmlToggle:"Origem HTML",foreColor:"Cor do Primeiro Plano",hiliteColor:"Cor de segundo plano",plainFormatBlock:"Estilo de Par\u00e1grafo",
formatBlock:"Estilo de Par\u00e1grafo",fontSize:"Tamanho da Fonte",fontName:"Nome da Fonte",tabIndent:"Recuo de Guia",fullScreen:"Comutar Tela Cheia",viewSource:"Visualizar Origem HTML",print:"Impress\u00e3o",newPage:"Nova P\u00e1gina",systemShortcut:'A a\u00e7\u00e3o "${0}" est\u00e1 dispon\u00edvel em seu navegador apenas usando um atalho do teclado. Use ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"extra-extra-pequeno",2:"extra-pequeno",3:"pequena",
4:"m\u00e9dio",5:"grande",6:"extra-grande",7:"extra-extra-grande",fontSize:"Tamanho",fontName:"Fonte",formatBlock:"Formatar",serif:"serif","sans-serif":"sans-serif",monospace:"espa\u00e7o simples",cursive:"cursiva",fantasy:"fantasy",noFormat:"Nenhum",p:"Par\u00e1grafo",h1:"T\u00edtulo",h2:"Subt\u00edtulo",h3:"Sub-subt\u00edtulo",pre:"Pr\u00e9-formatado",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Visualizar",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Localizar:",
findTooltip:"Inserir texto a ser localizado",replaceLabel:"Substituir por:",replaceTooltip:"Inserir texto a ser substitu\u00eddo por",findReplace:"Localizar e Substituir",matchCase:"Diferenciar mai\u00fasculas/min\u00fasculas",matchCaseTooltip:"Diferenciar mai\u00fasculas/min\u00fasculas",backwards:"Retroceder",backwardsTooltip:"Procurar texto para tr\u00e1s",replaceAllButton:"Substituir Todos",replaceAllButtonTooltip:"Substituir todo o texto",findButton:"Localizar",findButtonTooltip:"Localizar o texto",
replaceButton:"Substituir",replaceButtonTooltip:"Substituir o texto",replaceDialogText:"${0} ocorr\u00eancias substitu\u00eddas.",eofDialogText:"\u00daltima ocorr\u00eancia ${0}",eofDialogTextFind:"localizado",eofDialogTextReplace:"substitu\u00eddo",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Colar do Word",instructions:"Cole o conte\u00fado do Word na caixa de texto a seguir. Quando estiver satisfeito com o conte\u00fado a ser inserido, pressione o bot\u00e3o para colar. Para interromper a inser\u00e7\u00e3o de texto, pressione o bot\u00e3o para cancelar.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserir \u00c2ncora",title:"Propriedades de \u00c2ncora",anchor:"Nome:",text:"Descri\u00e7\u00e3o:",set:"Configurar",cancel:"Cancelar",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Cita\u00e7\u00e3o de Bloco",_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Selecione um modelo para criar fei\u00e7\u00f5es",generalSettings:"Configura\u00e7\u00f5es Gerais",layerSettings:"Configura\u00e7\u00f5es da Camada",
editDescription:"Fornecer texto de visualiza\u00e7\u00e3o para o painel de edit\u00e7\u00e3o",editDescriptionTip:"Este texto \u00e9 exibido sobre o seletor de Modelos, mantenha em branco para nenhum texto.",promptOnSave:"Solicite para salvar edi\u00e7\u00f5es n\u00e3o salvas quando o formul\u00e1rio estiver fechado ou alternado para o pr\u00f3ximo registro.",promptOnSaveTip:"Exibe um lembrete quando o usu\u00e1rio clica em fechar ou navega para o pr\u00f3ximo registro edit\u00e1vel quando a fei\u00e7\u00e3o atual tiver edi\u00e7\u00f5es n\u00e3o salvas.",
promptOnDelete:"Exige confirma\u00e7\u00e3o ao excluir um registro.",promptOnDeleteTip:"Exibe um lembrete quando o usu\u00e1rio clica em excluir para confirmar a a\u00e7\u00e3o.",removeOnSave:"Remove a fei\u00e7\u00e3o da sele\u00e7\u00e3o ao salvar.",removeOnSaveTip:"Op\u00e7\u00e3o para remover a fei\u00e7\u00e3o do conjunto de sele\u00e7\u00e3o quando o registro for salvo.  Se ele for o \u00fanico registro selecionado, o painel \u00e9 trocado de volta para a p\u00e1gina do modelo.",useFilterEditor:"Utilizar filtro do modelo de fei\u00e7\u00e3o",
useFilterEditorTip:"Op\u00e7\u00e3o para utilizar o seletor do Modelo de Filtro que fornece a habilidade para visualizar uns modelos de camadas ou pesquisar modelos por nome.",listenToGroupFilter:"Aplica valores de filtro a partir do widget Filtrar Grupo para os campos Preset",listenToGroupFilterTip:"Quando um filtro for aplicado no widget Filtrar Grupo, aplique o valor para um campo correspondente na lista de valor do Preset.",keepTemplateActive:"Mantenha o modelo selecionado ativo",keepTemplateActiveTip:"Quando o seletor de modelo for exibido, se um modelo foi selecionado anteriormente, selecione-o novamente.",
layerSettingsTable:{allowDelete:"Permitir Exclus\u00e3o",allowDeleteTip:"Op\u00e7\u00e3o para permitir que o usu\u00e1rio exclua uma fei\u00e7\u00e3o; desabilitado se a camada n\u00e3o suportar exclus\u00e3o",edit:"Edit\u00e1vel",editTip:"Op\u00e7\u00e3o para incluir a camada no widget",label:"Camada",labelTip:"Nome da camada como definido no mapa",update:"Desabilitar Edi\u00e7\u00e3o de Geometria",updateTip:"Op\u00e7\u00e3o para desabilitar o recurso de mover a geometria uma vez posicionada ou mover a geometria em uma fei\u00e7\u00e3o existente",
allowUpdateOnly:"Atualizar Somente",allowUpdateOnlyTip:"Op\u00e7\u00e3o para permitir somente a modifica\u00e7\u00e3o de fei\u00e7\u00f5es existentes, marcado por padr\u00e3o e desabilitado se a camada n\u00e3o suportar a cria\u00e7\u00e3o de novas fei\u00e7\u00f5es",fields:"Campos",fieldsTip:"Modificar os campos a serem editados e definir Atributos Inteligentes",description:"Descri\u00e7\u00e3o",descriptionTip:"Op\u00e7\u00e3o para inserir texto para exibir na parte superior da p\u00e1gina de atributos."},
editFieldError:"As modifica\u00e7\u00f5es de campo e atributos Inteligentes n\u00e3o est\u00e3o dispon\u00edveis para camadas que n\u00e3o s\u00e3o edit\u00e1veis",noConfigedLayersError:"O Editor Inteligente exige um ou mais camadas edit\u00e1veis"},editDescriptionPage:{title:"Defina o texto de vis\u00e3o geral dos atributos para \x3cb\x3e${layername}\x3c/b\x3e "},fieldsPage:{title:"Configure campos para \x3cb\x3e${layername}\x3c/b\x3e",description:"Utilize a coluna Pr\u00e9-Configurado para permitir que o usu\u00e1rio insira um valor antes de criar uma nova fei\u00e7\u00e3o. Utilize o bot\u00e3o editar A\u00e7\u00f5es para ativar Atributos Inteligentes em uma camada. Os Atributos Inteligentes podem exigir, ocultar ou desativar um campo baseado em valores em outros campos.",
fieldsNotes:"* \u00e9 um campo exigido.  Se voc\u00ea desmarcar Exibir para este campo e a edi\u00e7\u00e3o do modelo n\u00e3o preencher este valor de campo, voc\u00ea n\u00e3o poder\u00e1 salvar um novo registro.",fieldsSettingsTable:{display:"Exibir",displayTip:"Determinar se o campo n\u00e3o \u00e9 vis\u00edvel",edit:"Edit\u00e1vel",editTip:"Verifique se o campo est\u00e1 presente no formul\u00e1rio de atributo",fieldName:"Nome",fieldNameTip:"Nome do campo definido no banco de dados",fieldAlias:"Nome Alternativo",
fieldAliasTip:"Nome do campo definido no mapa",canPresetValue:"Ajustar",canPresetValueTip:"Op\u00e7\u00e3o para mostrar o campo na lista do campo pr\u00e9-configurado e permitir ao usu\u00e1rio configurar o valor antes da edi\u00e7\u00e3o",actions:"A\u00e7\u00f5es",actionsTip:"Alterar a ordem dos campos ou configurar os Atributos Inteligentes"},smartAttSupport:"Atributos Inteligentes n\u00e3o s\u00e3o suportados em campos do banco de dados exigidos"},actionPage:{title:"Configure as a\u00e7\u00f5es do Atributo Inteligente para \x3cb\x3e${fieldname}\x3c/b\x3e",
description:"As a\u00e7\u00f5es est\u00e3o sempre desativadas a menos que voc\u00ea especifique os crit\u00e9rios nos quais elas ser\u00e3o ativadas.  As a\u00e7\u00f5es s\u00e3o processadas em ordem e somente uma a\u00e7\u00e3o ser\u00e1 ativada por campo.  Utilize o bot\u00e3o Editar Crit\u00e9rios para definir os crit\u00e9rios.",actionsSettingsTable:{rule:"A\u00e7\u00e3o",ruleTip:"A a\u00e7\u00e3o executada quando os crit\u00e9rios forem atendidos",expression:"Express\u00e3o",expressionTip:"A express\u00e3o resultante no formato SQL a partir dos crit\u00e9rios definidos",
actions:"Crit\u00e9rios",actionsTip:"Altere a ordem da regra e defina os crit\u00e9rios quando ela for ativada"},actions:{hide:"Ocultar",required:"Exigido",disabled:"Desabilitado"}},filterPage:{submitHidden:"Enviar dados de atributos para este campo at\u00e9 quando estiver oculto?",title:"Configure a express\u00e3o para a regra ${action}",filterBuilder:"Configure a a\u00e7\u00e3o no campo quando o registro corresponder ${any_or_all} das seguintes express\u00f5es",noFilterTip:"Utilizando as ferramentas abaixo, defina a declara\u00e7\u00e3o para quando a a\u00e7\u00e3o estiver ativa."},
_localized:{}}});