// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Boldirano",copy:"Kopiraj",cut:"Izre\u017ei","delete":"Izbri\u0161i",indent:"Uvla\u010di",insertHorizontalRule:"Horizontalno pravilo",insertOrderedList:"Numerisana lista",insertUnorderedList:"Lista oznaka",italic:"Kurziv",justifyCenter:"Poravnaj po sredini",justifyFull:"Poravnaj",justifyLeft:"Poravnaj na lijevo",justifyRight:"Poravnaj na desno",outdent:"Izvuci",paste:"Zalijepi",redo:"Ponovo napravi",removeFormat:"Ukloni format",selectAll:"Izaberi sve",strikethrough:"Precrtaj",
subscript:"Indeks",superscript:"Superskript",underline:"Podvuci",undo:"Poni\u0161ti",unlink:"Ukloni link",createLink:"Kreiraj link",toggleDir:"Promijeni smjer",insertImage:"Umetni sliku",insertTable:"Umetni/uredi tabelu",toggleTableBorder:"Promijeni rub tabele",deleteTable:"Bri\u0161i tabelu",tableProp:"Osobina tabele",htmlToggle:"HTML izvor",foreColor:"Boja prednjeg plana",hiliteColor:"Boja pozadine",plainFormatBlock:"Stil paragrafa",formatBlock:"Stil paragrafa",fontSize:"Veli\u010dina fonta",fontName:"Ime fonta",
tabIndent:"Uvla\u010denje kartice",fullScreen:"Promijeni pun ekran",viewSource:"Pogledaj HTML izvor",print:"Ispi\u0161i",newPage:"Nova stranica",systemShortcut:'Akcija "${0}"je dostupna u va\u0161em pretra\u017eiva\u010du kad koristite pre\u010dicu tastature. Koristite ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"xx-malo",2:"x-malo",3:"maleno",4:"srednje",5:"veliko",6:"x-veliko",7:"xx-veliko",fontSize:"Veli\u010dina",fontName:"Font",formatBlock:"Format",
serif:"serif","sans-serif":"bez-serifa",monospace:"monoprostor",cursive:"kurziv",fantasy:"Fantazija",noFormat:"ni\u0161ta",p:"Paragraf",h1:"Naslov",h2:"Podnaslov",h3:"Pod-podnaslov",pre:"Predformatizovano",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pregled",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Na\u0111i:",findTooltip:"Unesite tekst koji treba na\u0107i",replaceLabel:"Zamijeni sa:",replaceTooltip:"Unesite tekst s kojim zamijeniti",findReplace:"Na\u0111i i zamijeni",
matchCase:"Spari slovo",matchCaseTooltip:"Spari slovo",backwards:"Unazad",backwardsTooltip:"Pretra\u017euj unazad za tekst",replaceAllButton:"Zamijeni sve",replaceAllButtonTooltip:"Zamijeni cijeli tekst",findButton:"Na\u0111i",findButtonTooltip:"Na\u0111i tekst",replaceButton:"Zamijeni",replaceButtonTooltip:"Zamijeni tekst",replaceDialogText:"Zamijenjena ${0} pojavljivanja",eofDialogText:"zadnje pojavljivanje ${0}",eofDialogTextFind:"prona\u0111eno",eofDialogTextReplace:"zamijenjeno",_localized:{}},
"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Zalijepi iz Worda",instructions:"Zalijepi sadr\u017eaj iz Worda ispod okvira s tekstom. Kad ste jednom zadovoljni sa sadr\u017eajem koji ume\u0107ete, pritisnite dugme za lijepljenje. Za prekid umetanja teksta, pritisnite dugme odustani.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Umetni sidro",title:"Osobine sidra",anchor:"Ime:",text:"Opis:",set:"Postav",cancel:"Odustani",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Citat bloka",
_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Odaberite predlo\u017eak za izradu zna\u010dajki",generalSettings:"Op\u0107e postavke",layerSettings:"Postavke sloja",editDescription:"Navedite tekst za prikaz za plo\u010du ure\u0111ivanja",editDescriptionTip:"Ovaj se tekst prikazuje iznad bira\u010da predlo\u017eaka, ostavite prazno ako ne \u017eelite da bude teksta.",promptOnSave:"Upit za spremanje nespremljenih ure\u0111ivanja kad je obrazac zatvoren ili preba\u010den na sljede\u0107i zapis.",
promptOnSaveTip:"Prika\u017eite upit kad korisnik klikne za zatvaranje ili navigira do sljede\u0107eg zapisa koji se mo\u017ee ure\u0111ivati dok trenuta\u010dni geoobjekt ima nespremljena ure\u0111ivanja.",promptOnDelete:"Potrebna je potvrda prilikom brisanja zapisa.",promptOnDeleteTip:"Prika\u017eite upit kad korisnik klikne za brisanje za potvrdu radnje.",removeOnSave:"Uklonite geoobjekt iz odabira za spremanje.",removeOnSaveTip:"Opcija za uklanjanje geoobjekta iz skupa za odabir kad se zapis spremi.  Ako je to jedini odabrani zapis, plo\u010da se prebacuje natrag na stranicu predlo\u0161ka.",
useFilterEditor:"Upotrijebi filtar predlo\u0161ka geoobjekta",useFilterEditorTip:"Opcija za upotrebu bira\u010da predlo\u0161ka filtra koja pru\u017ea mogu\u0107nost prikaza predlo\u017eaka jednog sloja ili pretra\u017eivanja predlo\u017eaka po nazivu.",listenToGroupFilter:"Primijenite vrijednosti filtra iz widgeta grupnog filtra u predefinirana polja",listenToGroupFilterTip:"Kada se primijeni filtar u widgetu grupnog filtra, primijenite vrijednost u odgovaraju\u0107e polje u popisu s predefiniranim vrijednostima.",
keepTemplateActive:"Ostavite aktivnim odabrani predlo\u017eak",keepTemplateActiveTip:"Kada se prika\u017ee bira\u010d predlo\u0161ka, a prethodno je odabran predlo\u017eak, ponovno ga odaberite.",layerSettingsTable:{allowDelete:"Omogu\u0107i brisanje",allowDeleteTip:"Opcija za omogu\u0107avanje korisniku brisanje geoobjekta; onemogu\u0107eno ako sloj ne podr\u017eava brisanje",edit:"Mo\u017ee se ure\u0111ivati",editTip:"Opcija za uklju\u010divanje sloja u widget",label:"Sloj",labelTip:"Naziv sloja kako je definirano na karti",
update:"Onemogu\u0107i ure\u0111ivanje geometrije",updateTip:"Opcija za onemogu\u0107ivanje mogu\u0107nosti pomicanja geometrije jednom kad se postavi ili pomicanja geometrije na postoje\u0107i geoobjekt",allowUpdateOnly:"A\u017euriraj samo",allowUpdateOnlyTip:"Opcija za omogu\u0107ivanje izmjena samo postoje\u0107ih geoobjekata, omogu\u0107eno po zadanim postavkama i onemogu\u0107eno ako sloj ne podr\u017eava stvaranje novih geoobjekata",fields:"Polja",fieldsTip:"Izmijenite polja za ure\u0111ivanje i definirajte pametne atribute",
description:"Opis",descriptionTip:"Opcija za unos teksta da se prikazuje na vrhu stranice atributa."},editFieldError:"Izmjena polja i pametni atributi nisu dostupni za slojeve koji se ne mogu ure\u0111ivati",noConfigedLayersError:"Za Pametni ure\u0111iva\u010d potreban je jedan ili vi\u0161e slojeva koji se mogu ure\u0111ivati"},editDescriptionPage:{title:"Definirajte tekst pregleda atributa za \x3cb\x3e${layername}\x3c/b\x3e "},fieldsPage:{title:"Konfigurirajte polja za \x3cb\x3e${layername}\x3c/b\x3e",
description:"Upotrijebite stupac za prethodno postavljanje kako biste omogu\u0107ili korisnicima uno\u0161enje vrijednosti prije stvaranja novog geoobjekta. Upotrijebite gumb za ure\u0111ivanje radnji da biste aktivirali pametne atribute na sloju. Pametni atributi mogu tra\u017eiti, skrivati ili onemogu\u0107iti polje na temelju vrijednosti u drugim poljima.",fieldsNotes:"* je obavezno polje. Ako odzna\u010dite prikaz za ovo polje i predlo\u017eak ure\u0111ivanja ne ispuni vrijednost tog polja, ne\u0107ete mo\u0107i spremiti novi zapis.",
fieldsSettingsTable:{display:"Prika\u017ei",displayTip:"Utvrdite je li polje nevidljivo",edit:"Mo\u017ee se ure\u0111ivati",editTip:"Provjerite postoji li polje u obliku atributa",fieldName:"Naziv",fieldNameTip:"Naziv polja definirano je u bazi podataka",fieldAlias:"Alias",fieldAliasTip:"Naziv polja definirano na karti",canPresetValue:"Zadano",canPresetValueTip:"Opcija za prikazivanje polja u popisu prethodno postavljenih polja i omogu\u0107ivanje korisniku postavljanje vrijednosti prije ure\u0111ivanja",
actions:"Radnje",actionsTip:"Promijenite redoslijed polja ili postavite pametne atribute"},smartAttSupport:"Pametni atributi nisu podr\u017eani u potrebnim poljima baze podataka"},actionPage:{title:"Konfigurirajte radnje pametnog atributa za \x3cb\x3e${fieldname}\x3c/b\x3e",description:"Radnje su uvijek isklju\u010dene osim ako ne odredite kriterije po kojima \u0107e se aktivirati.  Radnje se obra\u0111uju po redu i samo \u0107e se jedna radnja aktivirati po polju.  Upotrijebite gumb za ure\u0111ivanje kriterija kako biste definirali kriterije.",
actionsSettingsTable:{rule:"Radnja",ruleTip:"Radnja izvr\u0161ena kad su zadovoljeni kriteriji",expression:"Izraz",expressionTip:"Dobiveni izraz u SQL formatu od definiranih kriterija",actions:"Kriteriji",actionsTip:"Promijenite redoslijed pravila i definirajte kriterije kad \u0107e se aktivirati"},actions:{hide:"Sakrij",required:"Potrebno",disabled:"Onemogu\u0107eno"}},filterPage:{submitHidden:"\u017delite predati podatke o atributu za ovo polje \u010dak i kad je skriveno?",title:"Konfiguriraj izraz za pravilo ${action}",
filterBuilder:"Postavite radnju za polje kad zapis odgovara ${any_or_all} sljede\u0107im izrazima",noFilterTip:"Pomo\u0107u alata u nastavku definirajte izjavu za situaciju kad je radnja aktivna."},_localized:{}}});