// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Negrito",copy:"Copiar",cut:"Cortar","delete":"Eliminar",indent:"Indentar",insertHorizontalRule:"R\u00e9gua horizontal",insertOrderedList:"Lista numerada",insertUnorderedList:"Lista marcada",italic:"It\u00e1lico",justifyCenter:"Alinhar ao centro",justifyFull:"Justificar",justifyLeft:"Alinhar \u00e0 esquerda",justifyRight:"Alinhar \u00e0 direita",outdent:"Recuar",paste:"Colar",redo:"Repetir",removeFormat:"Remover formato",selectAll:"Seleccionar tudo",strikethrough:"Rasurado",
subscript:"Inferior \u00e0 linha",superscript:"Superior \u00e0 linha",underline:"Sublinhado",undo:"Anular",unlink:"Remover liga\u00e7\u00e3o",createLink:"Criar liga\u00e7\u00e3o",toggleDir:"Alternar direc\u00e7\u00e3o",insertImage:"Inserir imagem",insertTable:"Inserir/Editar tabela",toggleTableBorder:"Alternar contorno da tabela",deleteTable:"Eliminar tabela",tableProp:"Propriedades da tabela",htmlToggle:"Origem HTML",foreColor:"Cor de primeiro plano",hiliteColor:"Cor de segundo plano",plainFormatBlock:"Estilo de par\u00e1grafo",
formatBlock:"Estilo de par\u00e1grafo",fontSize:"Tamanho do tipo de letra",fontName:"Nome do tipo de letra",tabIndent:"Indentar com a tecla Tab",fullScreen:"Alternar ecr\u00e3 completo",viewSource:"Ver origem HTML",print:"Imprimir",newPage:"Nova p\u00e1gina",systemShortcut:'A ac\u00e7\u00e3o "${0}" apenas est\u00e1 dispon\u00edvel no navegador utilizando um atalho de teclado. Utilize ${1}.',ctrlKey:"ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"xxs",2:"xs",3:"small",
4:"medium",5:"large",6:"xl",7:"xxl",fontSize:"Tamanho",fontName:"Tipo de letra",formatBlock:"Formato",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Nenhum",p:"Par\u00e1grafo",h1:"T\u00edtulo",h2:"Sub-t\u00edtulo",h3:"Sub-subt\u00edtulo",pre:"Pr\u00e9-formatado",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Pr\u00e9-visualizar",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Localizar:",findTooltip:"Introduzir texto a localizar",
replaceLabel:"Substituir por:",replaceTooltip:"Introduzir texto de substitui\u00e7\u00e3o",findReplace:"Localizar e substituir",matchCase:"Correspond\u00eancia de mai\u00fasculas/min\u00fasculas",matchCaseTooltip:"Correspond\u00eancia de mai\u00fasculas/min\u00fasculas",backwards:"Para tr\u00e1s",backwardsTooltip:"Procura de texto para tr\u00e1s",replaceAllButton:"Substituir tudo",replaceAllButtonTooltip:"Substituir todo o texto",findButton:"Localizar",findButtonTooltip:"Localizar o texto",replaceButton:"Substituir",
replaceButtonTooltip:"Substituir o texto",replaceDialogText:"Foram substitu\u00eddas ${0} ocorr\u00eancias.",eofDialogText:"\u00daltima ocorr\u00eancia ${0}",eofDialogTextFind:"localizado",eofDialogTextReplace:"substitu\u00eddo",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Colar do Word",instructions:"Cole o conte\u00fado do Word na caixa de texto abaixo. Ap\u00f3s estar satisfeito com o conte\u00fado a inserir, prima o bot\u00e3o de colagem. Para cancelar a inser\u00e7\u00e3o de texto, prima o bot\u00e3o de cancelamento.",
_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Inserir \u00e2ncora",title:"Propriedades da \u00e2ncora",anchor:"Nome:",text:"Descri\u00e7\u00e3o:",set:"Definir",cancel:"Cancelar",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Escolha um template para criar elementos",generalSettings:"Configura\u00e7\u00f5es Gerais",layerSettings:"Configura\u00e7\u00f5es de Camada",editDescription:"Fornecer texto de exibi\u00e7\u00e3o para o painel editar",
editDescriptionTip:"Este texto \u00e9 exibido acima do seletor Modelo, deixe em branco caso prefira que n\u00e3o haja texto.",promptOnSave:"Solicita\u00e7\u00e3o para guardar edi\u00e7\u00f5es por guardar quando o formul\u00e1rio \u00e9 encerrado ou alterado para o registo seguinte.",promptOnSaveTip:"Exibir uma solicita\u00e7\u00e3o quando o utilizador clica em encerrar ou navega para o registo edit\u00e1vel seguinte, quando o elemento atual tem edi\u00e7\u00f5es por guardar.",promptOnDelete:"Requerer confirma\u00e7\u00e3o ao eliminar um registo.",
promptOnDeleteTip:"Exibir uma solicita\u00e7\u00e3o quando o utilizador clica em eliminar para confirmar a a\u00e7\u00e3o.",removeOnSave:"Remover elemento de sele\u00e7\u00e3o ao guardar.",removeOnSaveTip:"Op\u00e7\u00e3o para remover o elemento do conjunto de sele\u00e7\u00e3o quando o registo \u00e9 guardado.  Casos e trate do \u00fanico registo selecionado, o painel regressa \u00e0 p\u00e1gina do modelo.",useFilterEditor:"Utilizar filtro de modelo de elemento",useFilterEditorTip:"Op\u00e7\u00e3o para utilizar o seletor Modelo de Filtro, que oferece a possibilidade de visualizar os modelos de uma camada ou pesquisar modelos por nome.",
listenToGroupFilter:"Aplicar valores de filtros do widget Agrupar Filtros para Predefinir campos",listenToGroupFilterTip:"Quando um filtro \u00e9 aplicado no widget Agrupar Filtros, aplique o valor a um campo correspondente na lista de valor Predefinido.",keepTemplateActive:"Manter modelo selecionado ativo",keepTemplateActiveTip:"Quando o seletor de modelos \u00e9 exibido, caso um modelo tenha sido selecionado anteriormente, volte a selecion\u00e1-lo.",layerSettingsTable:{allowDelete:"Permitir Elimina\u00e7\u00e3o",
allowDeleteTip:"Op\u00e7\u00e3o para permitir ao utilizador eliminar um elemento; \u00e9 desativada caso a camada n\u00e3o suporte elimina\u00e7\u00e3o",edit:"Edit\u00e1vel",editTip:"Op\u00e7\u00e3o para incluir a camada no widget",label:"Camada",labelTip:"Nome da camada tal como definido no mapa",update:"Desativar Edi\u00e7\u00e3o de Geometria",updateTip:"Op\u00e7\u00e3o para desativar a capacidade de mover a geometria ap\u00f3s colocada, ou mover a geometria num elemento existente",allowUpdateOnly:"Atualizar Apenas",
allowUpdateOnlyTip:"Op\u00e7\u00e3o para permitir apenas a modifica\u00e7\u00e3o de elementos existentes, selecionados por defeito e desativados caso a camada n\u00e3o suporte a cria\u00e7\u00e3o de novos elementos",fields:"Campos",fieldsTip:"Modificar os campos para serem editados e definir Atributos Inteligentes",description:"Descri\u00e7\u00e3o",descriptionTip:"Op\u00e7\u00e3o para introduzir texto a exibir no topo da p\u00e1gina de atributos."},editFieldError:"Modifica\u00e7\u00f5es de campos e atributos Inteligentes n\u00e3o se encontram dispon\u00edveis para camadas que n\u00e3o s\u00e3o edit\u00e1veis",
noConfigedLayersError:"O Smart Editor requer uma ou mais camadas edit\u00e1veis."},editDescriptionPage:{title:"Defina o texto de vista geral de atributos para \x3cb\x3e${layername}\x3c/b\x3e "},fieldsPage:{title:"Configure campos para \x3cb\x3e${layername}\x3c/b\x3e",description:"Utilize a coluna Predefini\u00e7\u00e3o para permitir ao utilizador introduzir um valor antes de criar um novo elemento. Utilize o bot\u00e3o de edi\u00e7\u00e3o A\u00e7\u00f5es para ativar Atributos Inteligentes numa camada. Os Atributos Inteligentes podem requerer, ocultar ou desativar um campo com base em valores de outros campos.",
fieldsNotes:"* \u00e9 um campo exigido.  Caso desmarque Exibir para este campo, e o modelo de edi\u00e7\u00e3o n\u00e3o preencha esse valor de campo, n\u00e3o lhe ser\u00e1 poss\u00edvel  guardar um novo registo.",fieldsSettingsTable:{display:"Exibir",displayTip:"Determinar se o campo n\u00e3o \u00e9 vis\u00edvel",edit:"Edit\u00e1vel",editTip:"Marcar se o campo estiver presente no formul\u00e1rio de atributos",fieldName:"Nome",fieldNameTip:"Nome do campo tal como definido na base de dados",fieldAlias:"Nome Alternativo",
fieldAliasTip:"Nome do campo definido no mapa",canPresetValue:"Pr\u00e9-definido",canPresetValueTip:"Op\u00e7\u00e3o para exibir o campo na lista de campos de predefini\u00e7\u00e3o, e permitir ao utilizador definir o valor antes de editar",actions:"Ac\u00e7\u00f5es",actionsTip:"Alterar a ordem dos campos ou configurar Atributos Inteligentes"},smartAttSupport:"Os Atributos Inteligentes n\u00e3o s\u00e3o suportados nos campos obrigat\u00f3rios da base de dados"},actionPage:{title:"Configure as ac\u00e7\u00f5es de Atributos Inteligentes para \x3cb\x3e${fieldname}\x3c/b\x3e",
description:"As a\u00e7\u00f5es est\u00e3o sempre desativadas, a n\u00e3o ser que especifique os crit\u00e9rios atrav\u00e9s dos quais s\u00e3o desencadeadas.   As a\u00e7\u00f5es s\u00e3o processadas por ordem e apenas uma a\u00e7\u00e3o por campo ser\u00e1 desencadeada.  Utilize o bot\u00e3o Edi\u00e7\u00e3o de Crit\u00e9rios para definir os crit\u00e9rios.",actionsSettingsTable:{rule:"A\u00e7\u00e3o",ruleTip:"A\u00e7\u00e3o executada quando os crit\u00e9rios s\u00e3o correspondidos",expression:"Express\u00e3o",
expressionTip:"A express\u00e3o resultante em formato SQL a partir dos crit\u00e9rios definidos",actions:"Crit\u00e9rios",actionsTip:"Alterar a ordem da regra e definir os crit\u00e9rios quando esta \u00e9 desencadeada"},actions:{hide:"Esconder",required:"Exigido",disabled:"Desativado"}},filterPage:{submitHidden:"Submeter dados de atributos para este campo, mesmo quando se encontra oculto?",title:"Configurar express\u00e3o para a regra ${action}",filterBuilder:"Definir a\u00e7\u00e3o para campo quando o registo corresponde a ${any_or_all} das express\u00f5es seguintes",
noFilterTip:"Utilizando as express\u00f5es apresentadas acima, defina a declara\u00e7\u00e3o apresentada quando a a\u00e7\u00e3o se encontra ativa."},_localized:{}}});