// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"dijit/_editor/nls/commands":{bold:"Lihavointi",copy:"Kopioi",cut:"Leikkaa","delete":"Poista",indent:"Sisenn\u00e4",insertHorizontalRule:"Vaakasuuntainen viiva",insertOrderedList:"Numeroitu luettelo",insertUnorderedList:"Numeroimaton luettelo",italic:"Kursivointi",justifyCenter:"Tasaus keskelle",justifyFull:"Tasaus",justifyLeft:"Tasaus vasemmalle",justifyRight:"Tasaus oikealle",outdent:"Ulonna",paste:"Liit\u00e4",redo:"Tee uudelleen",removeFormat:"Poista muotoilu",selectAll:"Valitse kaikki",
strikethrough:"Yliviivaus",subscript:"Alennettu",superscript:"Korotettu",underline:"Alleviivaus",undo:"Kumoa",unlink:"Poista linkki",createLink:"Luo linkki",toggleDir:"Vaihda suuntaa",insertImage:"Lis\u00e4\u00e4 kuva",insertTable:"Lis\u00e4\u00e4 taulukko/muokkaa taulukkoa",toggleTableBorder:"Ota taulukon kehys k\u00e4ytt\u00f6\u00f6n/poista kehys k\u00e4yt\u00f6st\u00e4",deleteTable:"Poista taulukko",tableProp:"Taulukon ominaisuudet",htmlToggle:"HTML-l\u00e4hde",foreColor:"Edustav\u00e4ri",hiliteColor:"Taustav\u00e4ri",
plainFormatBlock:"Kappaletyyli",formatBlock:"Kappaletyyli",fontSize:"Fonttikoko",fontName:"Fontin nimi",tabIndent:"Sarkainsisennys",fullScreen:"Vaihda koko n\u00e4ytt\u00f6",viewSource:"N\u00e4yt\u00e4 HTML-l\u00e4hde",print:"Tulosta",newPage:"Uusi sivu",systemShortcut:'Toiminto "${0}" on k\u00e4ytett\u00e4viss\u00e4 selaimessa vain n\u00e4pp\u00e4imist\u00f6n pikatoiminnolla. K\u00e4yt\u00e4 seuraavaa: ${1}.',ctrlKey:"Ctrl+${0}",appleKey:"\u2318${0}",_localized:{}},"dijit/_editor/nls/FontChoice":{1:"xx-small",
2:"x-small",3:"small",4:"medium",5:"large",6:"x-large",7:"xx-large",fontSize:"Koko",fontName:"Fontti",formatBlock:"Muotoile",serif:"serif","sans-serif":"sans-serif",monospace:"monospace",cursive:"cursive",fantasy:"fantasy",noFormat:"Ei mit\u00e4\u00e4n",p:"Kappale",h1:"Otsikko",h2:"Alatason otsikko",h3:"Alimman tason otsikko",pre:"Esimuotoiltu",_localized:{}},"dojox/editor/plugins/nls/Preview":{preview:"Esikatselu",_localized:{}},"dojox/editor/plugins/nls/FindReplace":{findLabel:"Etsi:",findTooltip:"Anna etsitt\u00e4v\u00e4 teksti",
replaceLabel:"Korvaa seuraavalla:",replaceTooltip:"Anna korvaava teksti",findReplace:"Etsi ja korvaa",matchCase:"Sama kirjainkoko",matchCaseTooltip:"Sama kirjainkoko",backwards:"Taaksep\u00e4in",backwardsTooltip:"Etsi teksti\u00e4 taaksep\u00e4in",replaceAllButton:"Korvaa kaikki",replaceAllButtonTooltip:"Korvaa kaikki teksti",findButton:"Etsi",findButtonTooltip:"Etsi teksti",replaceButton:"Korvaa",replaceButtonTooltip:"Korvaa teksti",replaceDialogText:"Korvattu ${0} esiintym\u00e4\u00e4.",eofDialogText:"Viimeinen esiintym\u00e4 ${0}",
eofDialogTextFind:"l\u00f6ytynyt",eofDialogTextReplace:"korvattu",_localized:{}},"dojox/editor/plugins/nls/PasteFromWord":{pasteFromWord:"Liit\u00e4 Word-ohjelmasta",instructions:"Liit\u00e4 sis\u00e4lt\u00f6 Word-tiedostosta alla olevaan tekstikentt\u00e4\u00e4n. Kun lis\u00e4tt\u00e4v\u00e4 sis\u00e4lt\u00f6 on mielest\u00e4si valmis, napsauta Liit\u00e4-painiketta. Voit peruuttaa lis\u00e4yksen napsauttamalla Peruuta-painiketta.",_localized:{}},"dojox/editor/plugins/nls/InsertAnchor":{insertAnchor:"Lis\u00e4\u00e4 ankkuri",
title:"Ankkurin ominaisuudet",anchor:"Nimi:",text:"Kuvaus:",set:"Aseta",cancel:"Peruuta",_localized:{}},"dojox/editor/plugins/nls/Blockquote":{blockquote:"Blockquote",_localized:{}},"widgets/SmartEditor/setting/nls/strings":{layersPage:{title:"Luo kohteita valitsemalla malli",generalSettings:"Yleiset asetukset",layerSettings:"Karttatason asetukset",editDescription:"J\u00e4rjest\u00e4 n\u00e4ytt\u00f6teksti muokkauspaneelia varten",editDescriptionTip:"T\u00e4m\u00e4 teksti n\u00e4ytet\u00e4\u00e4n mallin valitsimen yl\u00e4puolella. J\u00e4t\u00e4 tyhj\u00e4ksi, jos et halua siihen tulevan teksti\u00e4.",
promptOnSave:"Kehote tallentamattomien muokkausten tallentamiseksi, kun lomake on suljettu tai vaihdettu seuraavaksi tietueeksi.",promptOnSaveTip:"N\u00e4yt\u00e4 kehote, kun k\u00e4ytt\u00e4j\u00e4 napsauttaa sulkemistoimintoa tai siirtyy seuraavaan muokattavissa olevaan tietueeseen, kun nykyisess\u00e4 kohteessa on tallentamattomia muokkauksia.",promptOnDelete:"Vaadi vahvistus tietuetta poistettaessa.",promptOnDeleteTip:"N\u00e4yt\u00e4 kehote, kun k\u00e4ytt\u00e4j\u00e4 vahvistaa toiminnon napsauttamalla poistotoimintoa.",
removeOnSave:"Poista kohde valinnasta tallennettaessa.",removeOnSaveTip:"Toiminto, joka poistaa kohteen valintajoukosta, kun tietue tallennetaan. Jos se on ainoa valittu tietue, paneeli vaihdetaan takaisin mallisivulle.",useFilterEditor:"K\u00e4yt\u00e4 kohdemallien suodatinta",useFilterEditorTip:"Toiminto, joka k\u00e4ytt\u00e4\u00e4 suodatinmallin valitsinta, joka antaa mahdollisuuden katsella yht\u00e4 karttatasomallia tai hakea malleja nimen mukaan.",listenToGroupFilter:"K\u00e4yt\u00e4 ryhm\u00e4suodattimen pienoisohjelman suodatinarvoja esiasetetuissa kentiss\u00e4",
listenToGroupFilterTip:"Kun suodatinta k\u00e4ytet\u00e4\u00e4n ryhm\u00e4suodattimen pienoisohjelmassa, k\u00e4yt\u00e4 arvoa vastaavassa kent\u00e4ss\u00e4 esiasetettujen arvojen luettelossa.",keepTemplateActive:"Pid\u00e4 valittu mallipohja aktiivisena",keepTemplateActiveTip:"Kun mallipohjan valitsin on n\u00e4kyviss\u00e4, poista aiemmin valitun mallinpohjan valinta.",layerSettingsTable:{allowDelete:"Salli poisto",allowDeleteTip:"Toiminto, joka sallii k\u00e4ytt\u00e4j\u00e4n poistaa kohteen. Se on pois k\u00e4yt\u00f6st\u00e4, jos karttataso ei mahdollista poistamista",
edit:"Muokattavissa",editTip:"Toiminto, joka sis\u00e4llytt\u00e4 karttatason pienoisohjelmaan",label:"Karttataso",labelTip:"Karttatason nimi karttaan m\u00e4\u00e4ritetyss\u00e4 muodossa",update:"Poista geometrian muokkaus k\u00e4yt\u00f6st\u00e4",updateTip:"Toiminto, joka est\u00e4\u00e4 geometrian siirt\u00e4misen sen asettamisen j\u00e4lkeen tai geometrian siirt\u00e4misen olemassa olevaan kohteeseen",allowUpdateOnly:"Vain p\u00e4ivitys",allowUpdateOnlyTip:"Toiminto, joka sallii vain olemassa olevien kohteiden muokkauksen. Se on valittuna oletusarvoisesti ja poistetaan k\u00e4yt\u00f6st\u00e4, jos karttataso ei mahdollista uusien kohteiden luomista",
fields:"Kent\u00e4t",fieldsTip:"Muokkaa muokattavia kentti\u00e4 ja m\u00e4\u00e4rit\u00e4 \u00e4lykk\u00e4\u00e4t ominaisuudet",description:"Kuvaus",descriptionTip:"Asetus n\u00e4ytt\u00e4\u00e4 kirjoitetun tekstin ominaisuussivun yl\u00e4osassa."},editFieldError:"Kent\u00e4n muokkaukset ja \u00e4lykk\u00e4\u00e4t ominaisuudet eiv\u00e4t ole k\u00e4ytett\u00e4viss\u00e4 karttatasoissa, joita ei voi muokata",noConfigedLayersError:"\u00c4lyk\u00e4s muokkausohjelma edellytt\u00e4\u00e4 v\u00e4hint\u00e4\u00e4n yht\u00e4 muokattavaa karttatasoa"},
editDescriptionPage:{title:"M\u00e4\u00e4rit\u00e4 ominaisuuden yleiskatsausteksti karttatasolle \x3cb\x3e${layername}\x3c/b\x3e "},fieldsPage:{title:"M\u00e4\u00e4rit\u00e4 kent\u00e4t karttatasolle \x3cb\x3e${layername}\x3c/b\x3e",description:"K\u00e4yt\u00e4 Esiasetus-saraketta, kun haluat sallia k\u00e4ytt\u00e4j\u00e4n sy\u00f6tt\u00e4v\u00e4n arvon ennen uuden kohteen luomista. K\u00e4yt\u00e4 Toiminnot-muokkauspainiketta, kun haluat aktivoida \u00e4lykk\u00e4\u00e4t ominaisuudet karttatasossa. \u00c4lykk\u00e4\u00e4t ominaisuudet voivat edellytt\u00e4\u00e4, piilottaa tai poistaa k\u00e4yt\u00f6st\u00e4 kent\u00e4n muiden kenttien arvojen perusteella.",
fieldsNotes:"* on pakollinen kentt\u00e4. Jos poistat N\u00e4yt\u00e4-valinnan t\u00e4m\u00e4n kent\u00e4n kohdalta ja muokkausmalli ei luo t\u00e4t\u00e4 kent\u00e4n arvoa, et pysty tallentamaan uutta tietuetta.",fieldsSettingsTable:{display:"N\u00e4yt\u00e4",displayTip:"M\u00e4\u00e4rit\u00e4, n\u00e4kyyk\u00f6 kentt\u00e4",edit:"Muokattavissa",editTip:"Valitse t\u00e4m\u00e4, jos kentt\u00e4 on ominaisuustietomuodossa",fieldName:"Nimi",fieldNameTip:"Tietokantaan m\u00e4\u00e4ritetty kent\u00e4n nimi",
fieldAlias:"Alias",fieldAliasTip:"Karttaan m\u00e4\u00e4ritetty kent\u00e4n nimi",canPresetValue:"Esiasetus",canPresetValueTip:"Toiminto, joka n\u00e4ytt\u00e4\u00e4 kent\u00e4n esiasetuskenttien luettelossa ja sallii k\u00e4ytt\u00e4j\u00e4n m\u00e4\u00e4ritt\u00e4\u00e4 arvo ennen muokkausta",actions:"Toiminnot",actionsTip:"Muuta kenttien j\u00e4rjestyst\u00e4 tai aseta \u00e4lykk\u00e4\u00e4t ominaisuudet k\u00e4ytt\u00f6\u00f6n"},smartAttSupport:"\u00c4lykk\u00e4\u00e4t ominaisuudet -toimintoa ei tueta pakollisissa tietokannan kentiss\u00e4"},
actionPage:{title:"M\u00e4\u00e4rit\u00e4 \u00c4lykk\u00e4\u00e4t ominaisuudet -toiminnot kent\u00e4lle \x3cb\x3e${fieldname}\x3c/b\x3e",description:"Toiminnot ovat aina pois k\u00e4yt\u00f6st\u00e4, ellet m\u00e4\u00e4rit\u00e4 ehtoja, joiden perusteella ne k\u00e4ynnistet\u00e4\u00e4n. Toiminnot k\u00e4sitell\u00e4\u00e4n j\u00e4rjestyksess\u00e4, ja kentt\u00e4\u00e4 kohti k\u00e4ynnistet\u00e4\u00e4n vain yksi toiminto. Voit m\u00e4\u00e4ritt\u00e4\u00e4 ehdot ehtojen muokkauspainikkeella.",actionsSettingsTable:{rule:"Toiminto",
ruleTip:"Toiminto suoritetaan, kun ehdot t\u00e4yttyv\u00e4t",expression:"Lauseke",expressionTip:"SQL-muodossa oleva m\u00e4\u00e4ritettyjen ehtojen perusteella syntyv\u00e4 lauseke",actions:"Hakuperusteet",actionsTip:"Muuta s\u00e4\u00e4nn\u00f6n j\u00e4rjestyst\u00e4 ja m\u00e4\u00e4rit\u00e4 ehdot, kun se k\u00e4ynnistet\u00e4\u00e4n."},actions:{hide:"Piilota",required:"Pakollinen",disabled:"Poissa k\u00e4yt\u00f6st\u00e4"}},filterPage:{submitHidden:"L\u00e4hetet\u00e4\u00e4nk\u00f6 t\u00e4lle kent\u00e4lle ominaisuustiedot my\u00f6s, kun se on piilotettu?",
title:"M\u00e4\u00e4rit\u00e4 lauseke s\u00e4\u00e4nn\u00f6lle ${action}",filterBuilder:"Aseta kent\u00e4lle teht\u00e4v\u00e4 toiminto, kun tietue vastaa ${any_or_all} seuraavaa lauseketta",noFilterTip:"M\u00e4\u00e4rit\u00e4 alla olevien ty\u00f6kalujen avulla lauseke sit\u00e4 tilannetta varten, kun toiminto on aktiivinen."},_localized:{}}});