// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["dojo/_base/lang","dojo/_base/array","esri/geometry/Extent","jimu/utils"],function(k,f,l,m){return{checkIfFieldAliasAlreadyExists:function(a,b){return 0<=a.split(",").indexOf(b)},pointToExtent:function(a,b,c){var d=a.extent.getWidth()/a.width;c*=d;return new l(b.x-c,b.y-c,b.x+c,b.y+c,a.spatialReference)},filterOnlyUpdatedAttributes:function(a,b,c){var d={},e;for(e in a)a.hasOwnProperty(e)&&(e===c.objectIdField||e===c.globalIdField?d[e]=a[e]:null===a[e]&&""===b[e]||a[e]!==b[e]&&(d[e]=a[e]));
return d},mergeFieldInfosWithConfiguration:function(a,b){var c=[],d=this.getDefaultEditableFieldInfos(a,!0);b&&b.fieldInfos?(f.forEach(b.fieldInfos,function(a){f.some(d,function(b){if(a.fieldName===b.fieldName)return c.push(this.mergeLastToFirst(b,a)),!0},this)},this),f.forEach(d,function(a){0===f.filter(c,function(b){return b.fieldName===a.fieldName},this).length&&c.push(a)},this)):c=d;return c},getDefaultEditableFieldInfos:function(a,b){var c=[],d=this.getFieldInfosFromWebmap(a);if(void 0===d||
null===d)d=this.getFieldInfosLayer(a);f.forEach(d,function(a){a.isEditable=a.editable;a.fieldName=a.name;a.canPresetValue=!1;!0===a.editable&&!0===b?c.push(k.clone(a)):!1===b&&c.push(k.clone(a))});return c},getFieldInfosFromWebmap:function(a){var b=null,c=a.getPopupInfo();c&&c.fieldInfos&&(b=[],f.forEach(c.fieldInfos,function(c){f.some(a.layerObject.fields,function(a){if(a.name===c.fieldName)return a=this.mergeFirstToLast(c,a),a.format&&(a.format.dateFormat&&a.format.dateFormat.toLowerCase()&&0<=
a.format.dateFormat.toLowerCase().indexOf("time"))&&(a.format.time=!0),b.push(a),!0},this)},this));return b},getFieldInfosLayer:function(a){var b=[];a&&a.layerObject&&f.forEach(a.layerObject.fields,function(a){var d=m.getDefaultPortalFieldInfo(a),d=this.mergeFirstToLast(d,a);d.format&&(d.format.dateFormat&&d.format.dateFormat.toLowerCase()&&0<=d.format.dateFormat.toLowerCase().indexOf("time"))&&(d.format.time=!0);d.visible=!0;b.push(d)},this);return b},getConfigInfos:function(a,b,c,d){var e=[];f.forEach(a.getLayerInfoArrayOfWebmap(),
function(a){var h=!1;"Feature Layer"===a.layerObject.type&&a.layerObject.url&&(a.layerObject.isEditable&&a.layerObject.isEditable()&&c?h=!0:c&&!1===c&&(h=!0));if(!0===h){var g=this.getConfigInfo(a,b);g.layerInfo=a;!0===g.featureLayer.layerAllowsDelete&&!1===g.featureLayer.layerAllowsCreate&&!1===g.featureLayer.layerAllowsUpdate?console.warn(g.layerInfo.title+" delete only not supported"):d&&!0===d?!0===f.some(b,function(a){return a.featureLayer.id===g.featureLayer.id})&&e.push(g):e.push(g)}},this);
return e},getConfigInfo:function(a,b){var c=null,d=this.createDefaultConfigInfo(a);!1===f.some(b,function(b){return b.featureLayer&&b.featureLayer.id===a.layerObject.id?(c=k.clone(b),c.fieldInfos=this.mergeFieldInfosWithConfiguration(a,c),c=this.mergeDefaultWithConfig(c,d),c._editFlag=!0):!1},this)&&(c=d);return c},mergeDefaultWithConfig:function(a,b){a.featureLayer=b.featureLayer;!0===a.allowDelete&&!1===a.featureLayer.layerAllowsDelete&&(a.allowDelete=!1);!1===a.disableGeometryUpdate&&!1===a.featureLayer.layerAllowGeometryUpdates&&
(a.disableGeometryUpdate=!0);!1===a.featureLayer.layerAllowsCreate&&!0===a.featureLayer.layerAllowsUpdate&&(a.allowUpdateOnly=!0);return a},createDefaultConfigInfo:function(a){var b=!1,c=!1,d=!1,e=!1;try{var f=a.layerObject.getEditCapabilities();f.canCreate&&(b=!0);f.canUpdate&&(e=c=!0);f.canDelete&&(d=!0)}catch(h){a.layerObject.hasOwnProperty("capabilities")&&(-1===String(a.layerObject.capabilities).indexOf("Update")&&-1===String(a.layerObject.capabilities).indexOf("Delete")&&-1===String(a.layerObject.capabilities).indexOf("Create")&&
-1!==String(a.layerObject.capabilities).indexOf("Editing")?b=d=c=!0:(-1!==String(a.layerObject.capabilities).indexOf("Update")&&(e=c=!0),-1!==String(a.layerObject.capabilities).indexOf("Delete")&&(d=!0),-1!==String(a.layerObject.capabilities).indexOf("Create")&&(b=!0)))}a.layerObject.hasOwnProperty("allowGeometryUpdates")&&(e=a.layerObject.allowGeometryUpdates);return{featureLayer:{id:a.layerObject.id,layerAllowsCreate:b,layerAllowsUpdate:c,layerAllowsDelete:d,layerAllowGeometryUpdates:e},disableGeometryUpdate:!e,
allowUpdateOnly:!b,allowDelete:!1,fieldInfos:this.mergeFieldInfosWithConfiguration(a,null),_editFlag:!1}},mergeLastToFirst:function(){for(var a={},b=0,c=arguments.length,d;b<c;b++)for(d in arguments[b])arguments[b].hasOwnProperty(d)&&(a[d]=arguments[b][d]);return a},mergeFirstToLast:function(){for(var a={},b=arguments.length-1,c;0<=b;b--)for(c in arguments[b])arguments[b].hasOwnProperty(c)&&(a[c]=arguments[b][c]);return a},isObjectEmpty:function(a){if(a)for(var b in a)if(a.hasOwnProperty(b))return!1;
return!0},addDateTimeFormat:function(a){a&&(a.format&&null!==a.format)&&(a.format.dateFormat&&null!==a.format.dateFormat&&0<=a.format.dateFormat.toString().toUpperCase().indexOf("TIME"))&&(a.format.time=!0)}}});