// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/event dojo/_base/lang dojo/_base/Color dojo/_base/html dojo/DeferredList dojo/dom-class dojo/dom dojox/gfx/fx dojo/on dojo/Evented jimu/utils esri/layers/GraphicsLayer esri/graphic esri/geometry/Extent esri/geometry/Point esri/symbols/PictureMarkerSymbol esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/TextSymbol esri/symbols/Font esri/renderers/SimpleRenderer esri/tasks/query esri/tasks/QueryTask esri/symbols/jsonUtils esri/renderers/jsonUtils esri/layers/FeatureLayer".split(" "),
function(C,w,D,n,l,s,E,B,F,G,H,I,x,J,h,K,u,y,p,m,L,M,N,t,z,v,A,O){return C("ClusterLayer",[J,I],{constructor:function(a){this.clusterGraphics=null;this.cancelRequest=!1;this.clusterSize=120;this._singles=[];this._showSingles=!0;this.updateFeatures=[];this.hidePanel=a.hidePanel;this._parent=a._parent;if(this._parentLayer=a.parentLayer)this.objectIdField=this._parentLayer.objectIdField,this.fields=this._parentLayer.fields;this.name=a.name;this._map=a.map;this.color=l.fromString(a.color||"#ff0000");
this._styleColor=a._styleColor;this.symbolData=a.lyrInfo.symbolData;this.countColor=this.symbolData._highLightColor;this.itemId=a.lyrInfo.itemId;this.refresh=a.lyrInfo.refresh;this.displayFeatureCount=this.symbolData.displayFeatureCount;this.node=a.node;this.countEnabled=a.countEnabled;this.legendNode=a.legendNode;this.id=a.id;this.infoTemplate=a.infoTemplate;this.url=a.lyrInfo.url;this._testRenderer=a.lyrInfo.renderer;(this.originOperLayer=a.originOperLayer)&&this._getInfoTemplate(this.originOperLayer);
this.lyrInfo=a.lyrInfo;this.lyrType=a.lyrType;this.filter=a.filter;this._setupSymbols();this._setFieldNames();this.countFeatures(this._parentLayer);0<this._parentLayer.refreshInterval&&setInterval(n.hitch(this,this._updateEnd),6E4*this._parentLayer.refreshInterval)},countFeatures:function(a){var b=new t;b.geometry=this._map.extent;a.queryCount?a.queryCount(b,n.hitch(this,function(b){if(0<b)this.hidePanel||(this.nodeCount=b),this._initFeatures(this._parentLayer);else if(!this.hidePanel){this.nodeCount=
0;var d=new O(a.url);H(d,"load",n.hitch(this,function(){this.countFeatures(d)}))}})):this._initFeatures(this._parentLayer)},_initFeatures:function(a){this._features=[];var b=!0,c=new t;-1<["CSV","Feature Collection","GeoRSS","KML"].indexOf(this.lyrType)||null===this.url?(this._getSourceFeatures(a.graphics),this.clusterFeatures()):"undefined"!==typeof this.url?this.loadData(this.url):(c.where=this.filter?this.filter:"1\x3d1",c.outFields=this._fieldNames,c.returnGeometry=!0,a.queryFeatures?a.queryFeatures(c).then(n.hitch(this,
function(a){a.features&&(this._getSourceFeatures(a.features),this.clusterFeatures())})):b="error");"error"!==b&&(this.extentChangeSignal||(this.extentChangeSignal=this._map.on("extent-change",n.hitch(this,this.handleMapExtentChange))),this.clickSignal||(this.clickSignal=this.on("click",n.hitch(this,this.handleClick))))},_getSourceFeatures:function(a){this._features=[];for(var b=0;b<a.length;b++){var c=a[b];c.geometry&&this._features.push(c)}},_getInfoTemplate:function(a){a=a.parentLayerInfo?a.parentLayerInfo:
a;if(a.controlPopupInfo&&(a=a.controlPopupInfo.infoTemplates)){if(this.url){var b=this.url.split("/").pop();b&&(a.indexOf?-1<a.indexOf(b)&&(this.infoTemplate=a[b].infoTemplate):a.hasOwnProperty(b)&&(this.infoTemplate=a[b].infoTemplate))}this.setInfoTemplate(this.infoTemplate)}},_setFieldNames:function(){this._fieldNames=[];if(this.infoTemplate&&"undefined"!==typeof this.infoTemplate.info){var a=this.infoTemplate.info.fieldInfos;if(a)for(var b=0;b<a.length;b++)a[b].visible&&this._fieldNames.push(a[b].fieldName)}if(this.symbolData.featureDisplayOptions&&
0<this.symbolData.featureDisplayOptions.fields.length)for(a=0;a<this.symbolData.featureDisplayOptions.fields.length;a++)b=this.symbolData.featureDisplayOptions.fields[a],-1===this._fieldNames.indexOf(b.name)&&this._fieldNames.push(b.name);1>this._fieldNames.length&&(this._fieldNames=["*"])},setLayerInfo:function(a){this.lyrInfo=a},clearSingles:function(a){w.forEach(a||this._singles,function(a){this.remove(a)},this);this._singles.length=0},_getSingleGraphic:function(a){a=new h(new u(a.geometry.x,a.geometry.y,
this._map.spatialReference),null,a.attributes);a.setSymbol(this._singleSym);return a},_addSingles:function(a){w.forEach(a,function(a){a=this._getSingleGraphic(a);this._singles.push(a);this._showSingles&&this.add(a)},this);this._map.infoWindow.setFeatures(this._singles)},initalCount:function(a){if(!this.hidePanel){var b=new t;b.returnGeometry=!1;b.geometry=this._map.extent;b.where=this.filter?this.filter:"1\x3d1";(new z(a)).executeForIds(b).then(n.hitch(this,function(a){var b;this.node?(B.contains(this.node,
"searching")&&B.remove(this.node,"searching"),this.node.innerHTML=a?x.localizeNumber(a.length):0,b=this.node.parentNode):this.legendNode&&(b=this.legendNode.previousSibling);this.updateExpand(b,a?!1:!0)}))}},updateExpand:function(a,b){if(!this.hidePanel&&"undefined"!==typeof a){var c;-1<a.id.indexOf("rec_")&&(c=a.id.replace("rec_",""),c=F.byId("exp_"+c));b?(a&&(s.addClass(a,"recDefault"),s.addClass(a,"inActive")),c&&s.addClass(c,"expandInActive")):(a&&(s.removeClass(a,"recDefault"),s.removeClass(a,
"inActive")),c&&s.removeClass(c,"expandInActive"))}},loadData:function(a){if(0<a.length){this.initalCount(a);var b=new t;b.where="1\x3d1";this.filter&&(b.where=this.filter);b.returnGeometry=!1;this.queryPending=!0;(new z(a)).executeForIds(b).then(n.hitch(this,function(b){if(b){this.queryIDs=b;b=[];var d,k;d=0;for(k=this.queryIDs.length;d<k;d+=1E3){var e=this.queryIDs.slice(d,d+1E3),f=new t;f.outFields=this._fieldNames;f.objectIds=e;f.returnGeometry=!0;f.outSpatialReference=this._map.spatialReference;
e=new z(a);b.push(e.execute(f))}this._features=[];this.cancelRequest?console.log("Cancelled ClusterLayer 1"):(new E(b)).then(n.hitch(this,function(a){this.queryPending=!1;if(this.cancelRequest)console.log("Cancelled ClusterLayer 2");else if(a){for(var b=this._map.spatialReference,c=[],e=0;e<a.length;e++)if(a[e][1].features)for(var f=0;f<a[e][1].features.length;f++){var d=a[e][1].features[f];if("undefined"!==typeof d.geometry&&null!==d.geometry&&d.geometry){var k=new u(d.geometry.x,d.geometry.y,b),
k=new h(k);k.setAttributes(d.attributes);this.infoTemplate&&k.setInfoTemplate(this.infoTemplate);c.push(k)}}a=!0;1E4>c&&(a=JSON.stringify(this._features)!==JSON.stringify(c));a&&(this._features=c,this.clusterFeatures(),this.emit("update-end",{bubbles:!0,cancelable:!0}))}}))}}))}},handleClick:function(a){var b=[];if(a.graphic&&(b=a.graphic,b.attributes)){var c=b.attributes;c.Data&&1<c.Data.length?(this.clearSingles(this._singles),b=c.Data,a.stopPropagation(),this._addSingles(b)):c.Data&&1===c.Data.length?
(c.Data[0].symbol=b.symbol,this._map.infoWindow.setFeatures([c.Data[0]])):this._map.infoWindow.setFeatures([b])}this.infoTemplate&&this._map.infoWindow.show(a.mapPoint);D.stop(a)},handleMapExtentChange:function(a){if(a.levelChange)this.clusterFeatures();else if(a.delta){var b=a.delta;a=Math.abs(b.x);b=Math.abs(b.y);(50<a||50<b)&&this.clusterFeatures()}},refreshFeatures:function(a){if(this.itemId){a=a.featureSet.features;"undefined"===typeof this.updateFeatures&&(this.updateFeatures=a);var b=!0;1E4>
a.length&&(b=JSON.stringify(this.updateFeatures)!==JSON.stringify(a));if(b){this._features=[];this._parentLayer.clear();var b=this._parentLayer.spatialReference,c;this._parentLayer.renderer?c=this._parentLayer.renderer:this._testRenderer&&(c=this._testRenderer);for(var d=0;d<a.length;d++){var k=a[d];if(k.geometry){var e=new h(this.getGraphicOptions(k,b,c));e.setAttributes(k.attributes);this.infoTemplate&&e.setInfoTemplate(this.infoTemplate);e.setSymbol(c.getSymbol(e));this._parentLayer.add(e);this._features.push(e)}else console.log("Null geometry skipped")}this.clusterFeatures()}this.updateFeatures=
a}else this.url&&this.loadData(this.url)},getGraphicOptions:function(a,b,c){return"undefined"!==typeof a.geometry.rings?{geometry:{rings:a.geometry.rings,spatialReference:{wkid:b.wkid}}}:"undefined"!==typeof a.geometry.paths?{geometry:{paths:a.geometry.paths,spatialReference:{wkid:b.wkid}}}:{geometry:new u(a.geometry.x,a.geometry.y,a.geometry.spatialReference),symbol:c.symbol}},flashFeatures:function(){this._map.graphics.clear();this.flashGraphics(this.graphics)},flashSingle:function(a){if("undefined"===
typeof a.symbol){var b=new m(m.STYLE_NULL,new l(0,0,0,0),0),c=this.color.toRgb();a.setSymbol(new p(p.STYLE_CIRCLE,9,b,new l([c[0],c[1],c[2],0.5])))}this.flashGraphics([a])},flashGraphics:function(a){for(var b=0;b<a.length;b++)this._flashFeature(a[b]);setTimeout(n.hitch(this,this._clearFeatures),1100)},_flashFeature:function(a){var b;if(a.geometry){var c=l.fromHex(this._styleColor),d=n.clone(c);d.a=0.4;"undefined"!==typeof a.symbol&&(b=new p(p.STYLE_CIRCLE,a.symbol.size,new m(m.STYLE_SOLID,c,1),d))}if("undefined"!==
typeof b&&(a=new h(a.geometry,b),this._map.graphics.add(a),b=a.getDojoShape()))G.animateStroke({shape:b,duration:700,color:{start:b.strokeStyle.color,end:b.strokeStyle.color},width:{start:18,end:0}}).play(),setTimeout(this._clearFeature,850,a)},_clearFeatures:function(){this._map.graphics.clear()},_clearFeature:function(a){a.getLayer().remove(a)},setColor:function(a){this.color=a},setStyleColor:function(a){this._styleColor=a},cancelPendingRequests:function(){console.log("Cancel Query...");this.queryPending&&
(this.cancelRequest=!0);this.removeEventListeners()},removeEventListeners:function(){this.extentChangeSignal&&(this.extentChangeSignal.remove(),this.extentChangeSignal=null);this.clickSignal&&(this.clickSignal.remove(),this.clickSignal=null)},clusterFeatures:function(){this.clear();null===this._map&&(this._map=this._parent.map);this._map.infoWindow.isShowing&&this._map.infoWindow.hide();var a=this._features,b=0;if("undefined"!==typeof a){if(0<a.length&&this.visible){var c=this.clusterSize;this.clusterGraphics=
[];for(var d=this._map.spatialReference,k=this._map.extent,e=new u(k.xmin,k.ymax,d),f=Math.ceil(this._map.height/c),g=Math.ceil(this._map.width/c),r=k.getWidth()/this._map.width*c,c=k.getHeight()/this._map.height*c,k=0;k<f;k++)for(var p=0;p<g;p++){var m=e.x+r*p,n=e.y-c*k,n=new K(m,n-c,m+r,n,d),m=[],l;for(l in a){var s=a[l];n.contains(s.geometry)&&(b+=1,m.push(s))}0<m.length&&(n=this.getClusterCenter(m),this.clusterGraphics.push({center:n,graphics:m}))}for(var t in this.clusterGraphics){a=this.clusterGraphics[t];
d=a.graphics.length;e=a.graphics;r=x.localizeNumber(d);g=f=19*r.length;f+=5;l=new M;l.family="Arial";l.size="16px";r=new L(r,l,this.countColor);r.setOffset(0,-4);var q;this.symbolData&&this.symbolData.symbol?this.symbolData.symbol.size?q=this.symbolData.symbol.size:this.symbolData.symbol.width&&(q=this.symbolData.symbol.width,l=this.symbolData.symbol.height,q=q>=l?q:l):this.icon.width?(f=this.icon.width>=f?this.icon.width+5:f,f=this.icon.height>=f?this.icon.height+5:f,g=this.icon.width>=g?this.icon.width+
1:g,g=this.icon.height>=g?this.icon.height+1:g):this.icon.size&&(q=this.icon.size);q&&(f=q>=f?q+5:f,g=q>=g?q+1:g);g>=f&&(f+=0===g-f?4:g-f+5);this._setSymbols(f+15,f);e={Count:d,Data:e};1<d?"undefined"!==typeof this.symbolData?"CustomSymbol"!==this.symbolData.symbolType?(this.add(new h(a.center,this.csym,e)),this.displayFeatureCount?this.add(new h(a.center,r,e)):this.add(new h(a.center,this.csym3,e))):(this.add(new h(a.center,this.csym,e)),this.displayFeatureCount?this.add(new h(a.center,r,e)):this.add(new h(a.center,
this.psym,e))):(this.add(new h(a.center,this.csym,e)),this.displayFeatureCount?this.add(new h(a.center,r,e)):this.add(new h(a.center,this.psym,e))):(a=a.graphics[0].geometry,this.renderer&&(this.renderer.hasOwnProperty("getSymbol")&&"LayerSymbol"===this.symbolData.symbolType?(a=new h(a,null,e.Data[0].attributes,this.infoTemplate),a.setSymbol(this.renderer.getSymbol(a))):this.renderer.hasOwnProperty("symbol")&&"LayerSymbol"===this.symbolData.symbolType?(a=new h(a,null,e.Data[0].attributes,this.infoTemplate),
a.setSymbol(v.fromJson(this.renderer.symbol))):a="EsriSymbol"===this.symbolData.symbolType?new h(a,v.fromJson(this.symbolData.symbol),e,this.infoTemplate):"LayerSymbol"!==this.symbolData.symbolType?new h(a,this.psym,e,this.infoTemplate):this.renderer.symbol?new h(a,this.renderer.symbol,e,this.infoTemplate):new h(a,this.psym,e,this.infoTemplate),"undefined"!==typeof a&&this.add(a)))}}this._updateNode(b)}},_getSym:function(a){var b;this.renderer.hasOwnProperty("getSymbol")&&"LayerSymbol"===this.symbolData.symbolType?
b=this.renderer.getSymbol(a):this.renderer.hasOwnProperty("symbol")&&"LayerSymbol"===this.symbolData.symbolType?b=this.renderer.symbol:"EsriSymbol"===this.symbolData.symbolType?b=this.symbolData.symbol:this.symbolData.symbol&&(b=this.symbolData.symbol);return b},_updateNode:function(a){if(!this.hidePanel){var b;this.node?(this.node.innerHTML=a?x.localizeNumber(a):0,b=this.node.parentNode):this.legendNode&&(b=this.legendNode.previousSibling);this.updateExpand(b,a&&this.visible?!1:!0)}},_updatePanelTime:function(a){if(!this.hidePanel){this.pageTitle.innerHTML=
"\x3cdiv\x3e\x3c/div\x3e";var b="";""!==this.config.mainPanelText&&(b=this.config.mainPanelText+" ");this.pageTitle.innerHTML=b+(new Date(a)).toLocaleDateString(navigator.language,{month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!0})}},_setSymbols:function(a,b){var c=this.color.toRgb(),d,k,e;if("undefined"!==typeof this.symbolData){var f;"custom"===this.backgroundClusterSymbol?f=c:(d=v.fromJson(this.backgroundClusterSymbol),0===d.outline.color.a||0===d.outline.width?
(k=m.STYLE_NULL,e=0):(k=m.STYLE_SOLID,e=d.outline.width));d?(c=m(k,d.outline.color,e),f=d.color.toRgb(),this.csym=new p(p.STYLE_CIRCLE,a,c,new l([f[0],f[1],f[2],0.75]))):this.csym=new p(p.STYLE_CIRCLE,a,null,new l([f[0],f[1],f[2],0.75]));(c=this.symbolData.s)&&-1<c.indexOf("${appPath}")?(c=window.location.pathname.replace("index.html",""),c=this.symbolData.s.replace("${appPath}",window.location.origin+c)):c=this.symbolData.s?this.symbolData.s:this.icon.imageData;if(c&&"CustomIcon"===this.symbolData.iconType){var g,
h;this.symbolData.symbol&&this.symbolData.symbol.height&&(g=this.symbolData.symbol.height);this.symbolData.symbol&&this.symbolData.symbol.width&&(h=this.symbolData.symbol.width);g&&h?h=g=h>g?h:g:(g=this.symbolData.icon.height?this.symbolData.icon.height:b,h=this.symbolData.icon.width?this.symbolData.icon.width:b);this.psym=new y(c,g,h)}else c&&"LayerIcon"===this.symbolData.iconType?this.psym=v.fromJson(this.symbolData.symbol):(g=m(this.icon.outline.style,this.icon.outline.color,this.icon.outline.width),
this.psym=new p(this.icon.style,this.icon.size,g,this.icon.color));this.csym2=n.clone(this.psym);this.csym3=n.clone(this.csym2);"undefined"!==typeof this.csym2.xoffset&&(this.csym3.xoffset=0);"undefined"!==typeof this.csym2.yoffset&&(this.csym3.yoffset=0)}else g=new m(m.STYLE_NULL,new l(0,0,0,0),0),this.csym=new p(p.STYLE_CIRCLE,a,g,new l([c[0],c[1],c[2],0.5])),this.psym=new y(this.icon.url,a-10,a-10),this.psym2=new y(this.icon.url,b-7,b-7),g=new m(m.STYLE_NULL,new l(0,0,0,0),0),this.csym2=new p(p.STYLE_CIRCLE,
b,g,new l([c[0],c[1],c[2],0.5]))},_setupSymbols:function(){if("undefined"!==typeof this.symbolData){this.countColor=this.symbolData._highLightColor;this.backgroundClusterSymbol=this.symbolData.clusterSymbol;this.icon=this.symbolData.icon;"LayerSymbol"===this.symbolData.symbolType?this._parentLayer.renderer?this.renderer=this._parentLayer.renderer.toJson?this._parentLayer.renderer:A.fromJson(this._parentLayer.renderer):this._testRenderer?this.renderer=A.fromJson(this._testRenderer):this.symbolData.renderer&&
(this.renderer=this.symbolData.renderer.toJson?this.symbolData.renderer:A.fromJson(this.symbolData.renderer)):this.renderer=new N(v.fromJson(this.symbolData.symbol));var a=this.color.toRgb(),b=new m(m.STYLE_NULL,new l(0,0,0,0),0);this._singleSym=new p(p.STYLE_CIRCLE,9,b,new l([a[0],a[1],a[2],0.5]))}},getLayer:function(){return this},getClusterCenter:function(a){var b=0,c=0,d=a.length;w.forEach(a,function(a){b+=a.geometry.x;c+=a.geometry.y},this);return new u(b/d,c/d,a[0].geometry.spatialReference)},
destroy:function(){this._clear();this.removeEventListeners()},_clear:function(){this.clear();this._features=[]},_updateEnd:function(){this.loadData(this.url)}})});