// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dijit/_WidgetBase dojo/Evented dojo/_base/lang dojo/_base/array esri/dijit/Search esri/tasks/locator esri/layers/FeatureLayer jimu/utils dojo/dom-construct jimu/LayerInfos/LayerInfos ./searchSourceUtils dojo/when dojo/Deferred dojo/promise/all dojo/on esri/InfoTemplate".split(" "),function(n,p,q,c,e,r,s,t,f,u,v,l,w,x,y,m,z){return n([p,q],{config:null,map:null,searchOptions:null,layerInfosObj:null,_urlParams:{},constructor:function(b){c.mixin(this,b)},postCreate:function(){this._urlParams=
{}},startup:function(){this.inherited(arguments);v.getInstance(this.map,this.map.itemInfo).then(c.hitch(this,function(b){this.layerInfosObj=b;this.own(this.layerInfosObj.on("layerInfosFilterChanged",c.hitch(this,this.onLayerInfosFilterChanged)));l.setMap(this.map);l.setLayerInfosObj(this.layerInfosObj);l.setAppConfig(this.appConfig);w(l.getConfigInfo(this.config.searchSourceSettings)).then(c.hitch(this,function(a){this.config.searchSourceSettings||(this.config.searchSourceSettings=a);return y(this._convertConfig(a)).then(function(a){return e.filter(a,
function(a){return a})})})).then(c.hitch(this,function(a){this.domNode&&this._init(a)}))}))},_convertConfig:function(b){return e.map(b.sources,c.hitch(this,function(a){var b=new x;if(a&&a.url&&"locator"===a.type){var d={locator:new s(a.url||""),outFields:["*"],singleLineFieldName:a.singleLineFieldName||"",name:f.stripHTML(a.name||""),placeholder:f.stripHTML(a.placeholder||""),countryCode:a.countryCode||"",maxSuggestions:a.maxSuggestions,maxResults:a.maxResults||6,zoomScale:a.zoomScale||5E4,useMapExtent:!!a.searchInCurrentMapExtent};
a.enableLocalSearch&&(d.localSearchOptions={minScale:a.localSearchMinScale,distance:a.localSearchDistance});b.resolve(d)}else a&&a.url&&"query"===a.type?(d=new t(a.url||null,{outFields:["*"]}),this.own(m(d,"load",c.hitch(this,function(c){var d,h,k;d=c.layer;h=this._getInfoTemplate(d,a,a.displayField);k=null;a.searchFields&&0<a.searchFields.length?k=a.searchFields:(k=[],e.forEach(d.fields,function(a){"esriFieldTypeOID"!==a.type&&(a.name!==d.objectIdField&&"esriFieldTypeGeometry"!==a.type)&&k.push(a.name)}));
c={featureLayer:d,outFields:["*"],searchFields:k,displayField:a.displayField||"",exactMatch:!!a.exactMatch,name:f.stripHTML(a.name||""),placeholder:f.stripHTML(a.placeholder||""),maxSuggestions:a.maxSuggestions||6,maxResults:a.maxResults||6,zoomScale:a.zoomScale||5E4,infoTemplate:h,useMapExtent:!!a.searchInCurrentMapExtent,_featureLayerId:a.layerId};h||delete c.infoTemplate;c._featureLayerId&&(h=this.layerInfosObj.getLayerInfoById(c._featureLayerId),d.setDefinitionExpression(h.getFilter()));b.resolve(c)}))),
this.own(m(d,"error",function(){b.resolve(null)}))):b.resolve(null);return b}))},_getInfoTemplate:function(b,a,f){var d,g,e;g=(d=this.layerInfosObj.getLayerInfoById(a.layerId))&&d.getInfoTemplate();e=d&&g;if(d&&!e)return null;e||(g=new z,g.setTitle("\x26nbsp;"),g.setContent(c.hitch(this,"_formatContent",a.name,b,f)));return g},_init:function(b){var a;a={map:this.map,addLayersFromMap:!1,autoNavigate:!1,autoComplete:!0,minCharacters:0,searchDelay:100,enableInfoWindow:!0,enableHighlight:this.config.searchSourceSettings.showInfoWindowOnSelect,
showInfoWindowOnSelect:this.config.searchSourceSettings.showInfoWindowOnSelect,activeSourceIndex:1===b.length?0:"all",allPlaceholder:f.stripHTML(this.config.searchSourceSettings.allPlaceholder)};c.mixin(a,this.searchOptions);this._urlParams=this._getUrlParams();this.search=new r(a,u.create("div",{"class":"searchControl"},this.domNode));this.search.set("sources",b);this.own(this.search.on("load",c.hitch(this,this._load)));this.own(this.search.on("select-result",c.hitch(this,this._selectResult)));this.own(this.search.on("clear-search",
c.hitch(this,this._clear)));this.own(this.search.on("search-results",c.hitch(this,this._results)));this.own(this.search.on("suggest-results",c.hitch(this,this._results)));this.search.startup()},_getUrlParams:function(){var b=f.urlToObject(document.location.href);b.query=b.query||{};return b.query},setSearchText:function(b){this.search.set("value",b)},clearSearchText:function(){this.search&&this.search.clear()},_setSearchString:function(){this._urlParams.find&&(this.search.set("value",this._urlParams.find),
setTimeout(c.hitch(this,function(){this.search.search()}),1E3))},onLayerInfosFilterChanged:function(b){e.some(b,c.hitch(this,function(a){this.search&&(this.search.sources&&0<this.search.sources.length)&&e.forEach(this.search.sources,function(b){b._featureLayerId===a.id&&b.featureLayer.setDefinitionExpression(a.getFilter())})}))},_load:function(b){this.emit("search-loaded",b);this._setSearchString()},_results:function(b){this.emit("search-results",b)},_clear:function(b){this.emit("clear-search",b)},
_selectResult:function(b){this.search.blur();this.emit("select-result",b)}})});