// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/Deferred dojo/_base/array dojo/promise/all esri/SpatialReference jimu/portalUtils jimu/shared/basePortalUrlUtils esri/request".split(" "),function(f,h,g,s,m,k,t,u){function n(a){if(!a)return null;var b=a.indexOf("?");return 0===a.search(/http|\/\//)&&-1!==b?a.slice(0,b).replace(/\/*$/g,""):a}function l(a){return a?t.removeProtocol(n(a)):null}function p(a){var b=[];g.forEach(a,function(a){b.push(a.url)});b.sort();a="";for(var c=0,c=0;c<b.length;c++){var d=b[c].indexOf("?"),
e="",e=-1!==d?b[c].slice(0,d):b[c];a+=e}return a.replace(/\ /,"")}function v(a){var b=!1;if(a)for(var c=0;c<a.length;c++)if(a[c].type){b=!0;break}return b}function q(a,b){var c=null,d=new h;b.spatialReference||a.spatialReference?(c=b.spatialReference||a.spatialReference,d.resolve(c)):a.owner&&0===a.owner.indexOf("esri_")?d.resolve({wkid:"102100"}):v(b.baseMap.baseMapLayers)?d.resolve({wkid:"102100"}):b.baseMap.baseMapLayers&&b.baseMap.baseMapLayers[0]?u({url:b.baseMap.baseMapLayers[0].url,content:{f:"json"},
handleAs:"json",callbackParamName:"callback"}).then(f.hitch(this,function(a){c=a.spatialReference?a.spatialReference:null;d.resolve(c)}),f.hitch(this,function(){d.resolve(null)})):d.resolve(null);return d}function w(a){var b=new h;k.getPortalSelfInfo(a).then(f.hitch(this,function(c){r.getBasemapGalleryGroup(a,c.basemapGalleryGroupQuery).then(f.hitch(this,function(a){a.queryItems({start:1,num:100,f:"json",q:k.webMapQueryStr}).then(f.hitch(this,function(a){b.resolve(a)}),f.hitch(this,function(){b.reject()}))}),
f.hitch(this,function(){b.reject()}))}));return b}var r={_loadPortalBaseMaps:function(a,b){var c=new h,d=[];w(a).then(function(a){g.forEach(a.results,function(a){var c=new h;d.push(c);a.getItemData().then(function(d){q(a,d).then(f.hitch(this,function(e){var f=[];if(b&&e&&b.equals(new m(e.wkid))){var f=g.map(d.baseMap.baseMapLayers,function(a){return a}),h=l(a.thumbnailUrl);c.resolve({layers:f,title:a.title||d.baseMap.title,thumbnailUrl:h,spatialReference:e})}else c.resolve({})}))})});s(d).then(function(a){a=
g.filter(a,function(a){return a&&a.title?!0:!1},this);c.resolve(a)})},function(a){c.reject(a)});return c},compareSameBasemap:function(a,b){var c=b.layers,d="",e="",d=p(a.layers),e=p(c);return d===e},compareSameBasemapByOrder:function(a,b){var c=a.layers,d=b.layers;if(c.length!==d.length)return!1;for(var e=0;e<c.length;e++)if(c[e].type||(c[e].type=null),d[e].type||(d[e].type=null),c[e].type!==d[e].type||!c[e].type&&!c[e].type&&(c[e].url||(c[e].url=null),d[e].url||(d[e].url=null),l(c[e].url)!==l(d[e].url)))return!1;
return!0},isBingMap:function(a){if(!a||!a.layers)return!1;for(var b=0;b<a.layers.length;b++)if("BingMapsAerial"===a.layers[b].type||"BingMapsRoad"===a.layers[b].type||"BingMapsHybrid"===a.layers[b].type)return!0;return!1},isNoUrlLayerMap:function(a){if(!a||!a.layers)return!1;for(var b=0;b<a.layers.length;b++)if("BingMapsAerial"===a.layers[b].type||"BingMapsRoad"===a.layers[b].type||"BingMapsHybrid"===a.layers[b].type||"OpenStreetMap"===a.layers[b].type)return!0;return!1},getToken:function(a){a=k.getPortal(a);
a.updateCredential();return a.credential?"?token\x3d"+a.credential.token:""},removeUrlQuery:function(a){return n(a)},getStanderdUrl:function(a){return l(a)},getUniqueTitle:function(a,b){if(!b||0===b.length)return a;var c=g.filter(b,function(b){return b===a?!0:0===b.indexOf(a)?(b=b.substr(a.length+1),!isNaN(+b)):!1});if(0===c.length)return a;c=g.map(c,function(b){return b===a?0:+b.substr(a.length+1)});c=c.sort();return a+" "+(c[c.length-1]+1)},getBasemapInfo:function(a,b){var c,d;return k.getPortal(a).getItemById(b).then(function(a){c=
a;return a.getItemData()}).then(function(a){d=a;return q(c,a)}).then(function(a){return{thumbnailUrl:c.thumbnailUrl,title:c.title||d.baseMap.title,layers:d.baseMap.baseMapLayers,spatialReference:new m(a)}})},getBasemapGalleryGroup:function(a,b){var c=new h,d=k.getPortal(a),e=b.indexOf("esri_");if(0<=e){var e=b.slice(e,e+7),g="esri_"+dojoConfig.locale.slice(0,2);b=b.replace(e,g)}d.queryGroups({f:"json",q:b}).then(f.hitch(this,function(a){0<a.results.length?c.resolve(a.results[0]):c.reject()}),f.hitch(this,
function(){c.reject()}));return c}};return r});