// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Query/RelatedRecordsResult.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"popup-menu-button related-records-action-button not-visible" data-dojo-attach-point\x3d"btnAction" data-dojo-attach-event\x3d"click:_onBtnMenuClicked"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"noresult-tip not-visible" data-dojo-attach-point\x3d"noResultTip"\x3e${nls.noResult}\x3c/div\x3e\r\n  \x3cdiv class\x3d"content not-visible" data-dojo-attach-point\x3d"content" data-dojo-attach-event\x3d"click:_onContentClicked"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/query dojo/Evented dojo/_base/html dojo/_base/lang dojo/_base/array dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./RelatedRecordsResult.html esri/dijit/PopupRenderer esri/layers/FeatureLayer esri/renderers/SimpleRenderer jimu/utils jimu/symbolUtils jimu/dijit/PopupMenu jimu/FeatureActionManager".split(" "),function(k,l,c,d,f,m,n,p,q,r,s,t,u,g,h,v,w){return m([n,p,q,l],{baseClass:"related-records-result",templateString:r,popupMenu:null,
featureActionManager:null,featureSet:null,layer:null,map:null,layerDefinition:null,nls:null,postCreate:function(){this.inherited(arguments);this.popupMenu=v.getInstance();this.featureActionManager=w.getInstance();if("Table"!==this.layerDefinition.type){this.layer=new t({layerDefinition:{geometryType:this.layerDefinition.geometryType,fields:this.layerDefinition.fields}});var a=g.getTypeByGeometryType(this.layerDefinition.geometryType),b=null;"point"===a?b=h.getDefaultMarkerSymbol():"polyline"===a?
b=h.getDefaultLineSymbol():"polygon"===a&&(b=h.getDefaultFillSymbol());b&&(a=new u(b),this.layer.setRenderer(a));this.map.addLayer(this.layer)}},destroy:function(){this.layer&&this.map.removeLayer(this.layer);this.layer=null;this.inherited(arguments)},setResult:function(a,b){this.layer&&this.layer.clear();this.featureSet=b;0<b.features.length?(f.forEach(b.features,d.hitch(this,function(b){this._createItem(a,b);this.layer&&this.layer.add(b)})),c.removeClass(this.btnAction,"not-visible"),c.addClass(this.noResultTip,
"not-visible"),c.removeClass(this.content,"not-visible"),g.featureAction.zoomTo(this.map,b.features)):(c.addClass(this.btnAction,"not-visible"),c.removeClass(this.noResultTip,"not-visible"),c.addClass(this.content,"not-visible"))},getLayer:function(){return this.layer},showLayer:function(){this.layer&&this.layer.show()},hideLayer:function(){this.layer&&this.layer.hide()},_createItem:function(a,b){var e='\x3cdiv class\x3d"item"\x3e\x3cdiv class\x3d"item-title"\x3e'+(a.getTitle(b)||"")+'\x3c/div\x3e\x3cdiv class\x3d"item-content"\x3e\x3c/div\x3e\x3c/div\x3e',
e=c.toDom(e),x=k(".item-content",e)[0],d=new s({template:a,graphic:b,chartTheme:a.chartTheme});c.place(d.domNode,x);d.startup();c.place(e,this.content)},_onContentClicked:function(a){a=a.target||a.srcElement;var b=null;if(b=c.hasClass(a,"item-title")?a:g.getAncestorDom(a,function(a){return c.hasClass(a,"item-title")},this.content))a=b.parentNode,c.toggleClass(a,"selected"),b=c.hasClass(a,"selected"),k(".item",this.content).removeClass("selected"),b&&c.addClass(a,"selected")},_onBtnBackClicked:function(){this.emit("back")},
_onBtnMenuClicked:function(a){if(this.featureSet){var b=c.position(a.target||a.srcElement);this.featureActionManager.getSupportedActions(this.featureSet).then(d.hitch(this,function(a){f.forEach(a,d.hitch(this,function(a){a.data=this.featureSet}));a=f.filter(a,d.hitch(this,function(a){return"CreateLayer"!==a.name}));this.popupMenu.setActions(a);this.popupMenu.show(b)}))}}})});