// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/Deferred jimu/utils esri/tasks/query esri/tasks/QueryTask esri/layers/FeatureLayer".split(" "),function(n,e,h,f,p,l,m,r){function q(){return{queryTr:null,config:null,layerInfo:null,relationshipLayerInfos:null,relationshipPopupTemplates:null,queryType:-1,query:{maxRecordCount:1E3,resultLayer:null,where:"",geometry:null,relationship:null,nextIndex:0,allCount:0,objectIds:[]}}}n=n(null,{tempResultLayer:null,map:null,currentAttrs:null,constructor:function(a,
b){this.map=a;this.currentAttrs=b;0<this.currentAttrs.layerInfo.maxRecordCount&&(this.currentAttrs.query.maxRecordCount=this.currentAttrs.layerInfo.maxRecordCount)},resetCurrentAttrs:function(){this.currentAttrs=q()},getCurrentAttrs:function(){return this.currentAttrs},executeQueryForFirstTime:function(){var a=null,a=this.currentAttrs.query.where,b=this.currentAttrs.query.geometry;return a=1===this.currentAttrs.queryType?this.doQuery_SupportOrderByAndPagination(a,b):2===this.currentAttrs.queryType?
this.doQuery_SupportObjectIds(a,b):this.doQuery_NotSupportObjectIds(a,b)},executeQueryWhenScrollToBottom:function(){var a=null;1===this.currentAttrs.queryType?a=this.onResultsScroll_SupportOrderByAndPagination():2===this.currentAttrs.queryType&&(a=this.onResultsScroll_SupportObjectIds());return a},_isServiceSupportsOrderBy:function(a){var b=!1;a.advancedQueryCapabilities&&a.advancedQueryCapabilities.supportsOrderBy&&(b=!0);return b},_isServiceSupportsPagination:function(a){var b=!1;a.advancedQueryCapabilities&&
a.advancedQueryCapabilities.supportsPagination&&(b=!0);return b},_tryLocaleNumber:function(a){var b=p.localizeNumber(a);if(null===b||void 0===b)b=a;return b},_tryLocaleDate:function(a){var b=p.localizeDate(a);b||(b=a.toLocaleDateString());return b},_getLayerIndexByLayerUrl:function(a){var b=a.lastIndexOf("/");a=a.slice(b+1,a.length);return parseInt(a,10)},_getServiceUrlByLayerUrl:function(a){var b=a.lastIndexOf("/");return a.slice(0,b)},_isSupportObjectIds:function(a){var b=0;a.currentVersion&&(b=
parseFloat(a.currentVersion));return 10<=b||a.hasOwnProperty("typeIdField")},_isImageServiceLayer:function(a){return-1<a.indexOf("/ImageServer")},_isTable:function(a){return"Table"===a.type},_getBestQueryName:function(a){for(var b=a=a?a+(" _"+this.nls.queryResult):a+this.nls.queryResult,c=h.map(this.map.graphicsLayerIds,e.hitch(this,function(a){return this.map.getLayer(a).name})),d=2;0<=h.indexOf(c,b);)b=a+"_"+d,d++;return b},getObjectIdsForAllRelatedRecordsAction:function(){var a=new f;if(this.currentAttrs.query.objectIds&&
0<this.currentAttrs.query.objectIds.length)a.resolve(this.currentAttrs.query.objectIds);else if(1===this.currentAttrs.queryType)a=this._queryIds(this.currentAttrs.query.where,this.currentAttrs.query.geometry,this.currentAttrs.query.relationship);else if(3===this.currentAttrs.queryType){var b=this.currentAttrs.config.objectIdField,c=h.map(this.currentAttrs.query.resultLayer.graphics,e.hitch(this,function(a){return parseInt(a.attributes[b],10)}));a.resolve(c)}return a},doQuery_SupportOrderByAndPagination:function(a,
b){var c=new f,d=e.hitch(this,function(a){console.error(a);c.reject(a)}),k=this.currentAttrs.query.relationship;this._queryCount(a,b,k).then(e.hitch(this,function(g){this.currentAttrs.query.allCount=g;0===g?c.resolve([]):(this.currentAttrs.query.nextIndex=0,this._queryWithPaginationAndOrder(a,b,0,this.currentAttrs.query.maxRecordCount,k).then(e.hitch(this,function(a){a=a.features;this.currentAttrs.query.nextIndex+=a.length;c.resolve(a)}),d))}),d);return c},onResultsScroll_SupportOrderByAndPagination:function(){var a=
new f,b=this.currentAttrs.query.nextIndex;if(b>=this.currentAttrs.query.allCount)return a.resolve([]),a;var c=e.hitch(this,function(b){console.error(b);a.reject(b)});this._queryWithPaginationAndOrder(this.currentAttrs.query.where,this.currentAttrs.query.geometry,b,this.currentAttrs.query.maxRecordCount,this.currentAttrs.query.relationship).then(e.hitch(this,function(b){b=b.features;this.currentAttrs.query.nextIndex+=b.length;a.resolve(b)}),c);return a},doQuery_SupportObjectIds:function(a,b){var c=
new f,d=e.hitch(this,function(a){console.error(a);c.reject(a)}),k=this.currentAttrs.query.relationship;this._queryIds(a,b,k).then(e.hitch(this,function(a){if(a&&0<a.length){var b=this.currentAttrs.query.allCount=a.length;this.currentAttrs.query.objectIds=a;this.currentAttrs.query.nextIndex=0;var h=this.currentAttrs.query.maxRecordCount,f=[],f=b>h?a.slice(0,h):a;this._queryByObjectIds(f,!0,k).then(e.hitch(this,function(a){a=a.features;this.currentAttrs.query.nextIndex+=a.length;c.resolve(a)}),e.hitch(this,
function(a){d(a)}))}else this.currentAttrs.query.allCount=0,c.resolve([])}),d);return c},onResultsScroll_SupportObjectIds:function(){var a=new f,b=this.currentAttrs.query.objectIds,c=this.currentAttrs.query.nextIndex;if(c>=this.currentAttrs.query.allCount)a.resolve([]);else{var d=Math.min(b.length-c,this.currentAttrs.query.maxRecordCount),b=b.slice(c,c+d);if(0===b.length)a.resolve([]);else return this._queryByObjectIds(b,!0,this.currentAttrs.query.relationship).then(e.hitch(this,function(b){b=b.features;
this.currentAttrs.query.nextIndex+=b.length;a.resolve(b)}),e.hitch(this,function(b){a.reject(b)})),a}},doQuery_NotSupportObjectIds:function(a,b){var c=new f;this._query(a,b,!0,this.currentAttrs.query.relationship).then(e.hitch(this,function(a){a=a.features;this.currentAttrs.query.allCount=a.length;c.resolve(a)}),e.hitch(this,function(a){console.error(a);c.reject(a)}));return c},_getObjectIdField:function(){return this.currentAttrs.config.objectIdField},getOutputFields:function(){var a=[],b=[],c=this.currentAttrs.config.objectIdField;
c&&b.push(c);c=this._getRequiredFieldNames();b=b.concat(c);c=this._getPopupInfoFieldNames();b=b.concat(c);h.forEach(b,e.hitch(this,function(b){0>a.indexOf(b)&&a.push(b)}));return a},_getRequiredFieldNames:function(){var a=e.clone(this.currentAttrs.layerInfo);return(new r({layerDefinition:a,featureSet:null})).getOutFields()},_getPopupInfoFieldNames:function(){var a=[],b=[],c=h.filter(this.currentAttrs.layerInfo.fields,e.hitch(this,function(a){return"esriFieldTypeGeometry"!==a.type})),d=this.currentAttrs.config.popupInfo,
b=b.concat(this._getPlaceholderFieldNames(c,d.title));d.description?b=b.concat(this._getPlaceholderFieldNames(c,d.description)):d.fieldInfos&&0<d.fieldInfos.length&&h.forEach(d.fieldInfos,e.hitch(this,function(a){a.visible&&b.push(a.fieldName)}));d.mediaInfos&&0<d.mediaInfos.length&&h.forEach(d.mediaInfos,e.hitch(this,function(a){b=b.concat(this._getPlaceholderFieldNames(c,a.title));b=b.concat(this._getPlaceholderFieldNames(c,a.caption));if(a=a.value){var d=a.fields;d&&0<d.length&&h.forEach(d,e.hitch(this,
function(a){b.push(a)}));a.normalizeField&&b.push(a.normalizeField);a.tooltipField&&b.push(a.tooltipField);a.sourceURL&&(b=b.concat(this._getPlaceholderFieldNames(c,a.sourceURL)));a.linkURL&&(b=b.concat(this._getPlaceholderFieldNames(c,a.linkURL)))}}));h.forEach(b,e.hitch(this,function(b){0>a.indexOf(b)&&a.push(b)}));return a},_getPlaceholderFieldNames:function(a,b){var c=[];if(b){var d=[];h.forEach(a,e.hitch(this,function(a){a=a.name;0<=b.indexOf("{"+a+"}")&&d.push(a)}));h.forEach(d,e.hitch(this,
function(a){0>c.indexOf(a)&&c.push(a)}))}return c},_query:function(a,b,c,d){var e=new l;e.where=a;b&&(e.geometry=b);e.outSpatialReference=this.map.spatialReference;e.returnGeometry=!!c;e.spatialRelationship=d;e.outFields=this.getOutputFields();return(new m(this.currentAttrs.config.url)).execute(e)},_queryIds:function(a,b,c){var d=new l;d.where=a;b&&(d.geometry=b);d.returnGeometry=!1;d.spatialRelationship=c;d.outSpatialReference=this.map.spatialReference;return(new m(this.currentAttrs.config.url)).executeForIds(d)},
_queryByObjectIds:function(a,b,c){var d=new f,k=new l;k.returnGeometry=!!b;k.outSpatialReference=this.map.spatialReference;k.outFields=this.getOutputFields();k.objectIds=a;k.spatialRelationship=c;(new m(this.currentAttrs.config.url)).execute(k).then(e.hitch(this,function(a){d.resolve(a)}),e.hitch(this,function(g){if(400===g.code){var k=this._getObjectIdField(),f="",l=a.length;h.forEach(a,e.hitch(this,function(a,b){f+=k+" \x3d "+a;b!==l-1&&(f+=" OR ")}));this._query(f,null,b,c).then(e.hitch(this,function(a){d.resolve(a)}),
e.hitch(this,function(a){d.reject(a)}))}else d.reject(g)}));return d},_queryCount:function(a,b,c){var d=new l;d.where=a;b&&(d.geometry=b);d.returnGeometry=!1;d.outSpatialReference=this.map.spatialReference;d.spatialRelationship=c;return(new m(this.currentAttrs.config.url)).executeForCount(d)},_queryWithPaginationAndOrder:function(a,b,c,d,f){var g=new l;g.where=a;b&&(g.geometry=b);g.outSpatialReference=this.map.spatialReference;g.returnGeometry=!0;g.spatialRelationship=f;g.outFields=this.getOutputFields();
g.start=c;g.num=d;if((a=this.currentAttrs.config.orderByFields)&&0<a.length)g.orderByFields=a,a=h.map(a,e.hitch(this,function(a){return a.split(" ")[0]})),h.forEach(a,e.hitch(this,function(a){0>g.outFields.indexOf(a)&&g.outFields.push(a)}));return(new m(this.currentAttrs.config.url)).execute(g)}});n.getCleanCurrentAttrsTemplate=q;return n});