// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/Deferred jimu/utils jimu/portalUrlUtils jimu/LayerInfos/LayerInfos esri/request esri/kernel".split(" "),function(e,h,p,k,m,q,r,s){return{getDefaultPopupInfo:function(a,b,c){var f={title:"",fieldInfos:[],description:null,showAttachments:!1,mediaInfos:[]};c=!!c;if(a.displayField){var g=this._getRealFieldName(a.displayField,a);f.title="{"+g+"}"}else if(g=k.getObjectIdField(a))f.title="{"+g+"}";f.showAttachments=!!a.hasAttachments;g=a=a.fields;b||(g=
h.filter(a,e.hitch(this,function(a){return"esriFieldTypeGeometry"!==a.type})));b=h.map(g,e.hitch(this,function(a){a=k.getDefaultPortalFieldInfo(a);a.visible=c;return a}));f.fieldInfos=b;return f},_getRealFieldName:function(a,b){a=a.toUpperCase();if(b.fields&&0<b.fields.length)for(var c=0;c<b.fields.length;c++)if(b.fields[c].name.toUpperCase()===a)return b.fields[c].name;return""},getPortalFieldInfosWithoutShape:function(a,b){return h.filter(b,e.hitch(this,function(b){return"esriFieldTypeGeometry"!==
k.getFieldInfoByFieldName(a.fields,b.fieldName).type}))},getPopupInfoByAttributes:function(a,b){var c=this.getDefaultPopupInfo(a,!1),f=[],g={},l;for(l in b){f.push(l);var d=k.getFieldInfoByFieldName(a.fields,l).type;if("esriFieldTypeSingle"===d||"esriFieldTypeDouble"===d)d=b[l],null!==d&&void 0!==d&&(d=parseFloat(d),isNaN(d)||(d=d.toString().split("."),2===d.length&&(g[l]=d[1].length)))}c.fieldInfos=h.filter(c.fieldInfos,e.hitch(this,function(a){var b=a.fieldName;g.hasOwnProperty(b)&&(a.format.places=
g[b]);return f.indexOf(b)}));return c},upgradePopupToPopupInfo:function(a,b){var c=this.getDefaultPopupInfo(a,!1,!1);c.title=b.title||"";c.title=c.title.replace("${","{");if(b.fields){var f={};h.forEach(b.fields,e.hitch(this,function(a){f[a.name]=a}));h.forEach(c.fieldInfos,e.hitch(this,function(a){var b=a.fieldName,d=f[b];d&&(a.label=d.alias||a.label,a.visible=!0,"image"===d.specialType&&(b="{"+b+"}",c.mediaInfos.push({title:"",type:"image",caption:a.label,value:{sourceURL:b,linkURL:b}})))}))}return c},
isImageServiceLayer:function(a){return a.url&&-1<a.url.indexOf("/ImageServer")},isTable:function(a){return"Table"===a.type},getConfigWithValidDataSource:function(a){var b={hideLayersAfterWidgetClosed:a.hideLayersAfterWidgetClosed,queries:[]},c=q.getInstanceSync();b.queries=h.filter(a.queries,e.hitch(this,function(a){return(a=a.webMapLayerId)?c.getLayerInfoById(a)?!0:!!c.getTableInfoById(a):!0}));return b},removePopupInfoUnsupportFields:function(a,b){var c=h.map(a.fields,e.hitch(this,function(a){return a.name}));
b.fieldInfos&&0<b.fieldInfos.length&&(b.fieldInfos=h.filter(b.fieldInfos,e.hitch(this,function(a){return 0<=c.indexOf(a.fieldName)})))},overridePopupTemplateMethodGetAttachments:function(a,b,c){a.getAttachments=function(a){var g=new p;try{var e=a.attributes[c],d=b+"/"+e+"/attachments";a={url:d,content:{f:"json"},callbackParamName:"callback"};var k="",n=s.id.findCredential(b);n&&n.token&&(k="?token\x3d"+n.token);r(a).then(function(a){a=a.attachmentInfos;h.forEach(a,function(a){a.url=d+"/"+a.id+k;a.objectId=
e});g.resolve(a)},function(a){g.reject(a)})}catch(m){console.error(m)}return g}},isServiceSupportsOrderBy:function(a){var b=!1;a.advancedQueryCapabilities&&a.advancedQueryCapabilities.supportsOrderBy&&(b=!0);return b},isServiceSupportsPagination:function(a){var b=!1;a.advancedQueryCapabilities&&a.advancedQueryCapabilities.supportsPagination&&(b=!0);return b},isSupportObjectIds:function(a){var b=0,c=k.getObjectIdField(a);a.currentVersion&&(b=parseFloat(a.currentVersion));return!!c&&(10<=b||a.hasOwnProperty("typeIdField"))},
getQueryType:function(a){var b=-1;return b=this.isServiceSupportsOrderBy(a)&&this.isServiceSupportsPagination(a)?1:this.isSupportObjectIds(a)?2:3},getWebMapPopupInfoByUrl:function(a,b){var c=null;b=b.replace(/\/*$/g,"");var f=m.removeProtocol(b);h.some(a.operationalLayers,e.hitch(this,function(a){if(a&&a.url){var b=m.removeProtocol(a.url.replace(/\/*$/g,""));if(a.popupInfo){if(b===f)return c=a.popupInfo,!0}else if(a.layers&&0<a.layers.length)return h.some(a.layers,e.hitch(this,function(d){return b+
"/"+d.id===f?(c=a.popupInfo,!0):!1}))}return!1}));return c},getPopupInfoForRelatedLayer:function(a,b,c){(a=this.getWebMapPopupInfoByUrl(a,b))||(a=this.getDefaultPopupInfo(c,!1,!0));if(!a.title&&(c=k.getObjectIdField(c)))a.title="{"+c+"}";return a}}});