// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Geoprocessing/resultrenderers/RecordSetRenderer.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"output-label" data-dojo-attach-point\x3d"labelNode"\x3e\r\n    \x3cspan data-dojo-attach-point\x3d"labelContent"\x3e\x3c/span\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"control-section"\x3e\r\n    \x3cdiv class\x3d"clear-node jimu-float-trailing" data-dojo-attach-point\x3d"clearNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"export-node jimu-float-trailing" data-dojo-attach-point\x3d"exportNode" style\x3d"display:none"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"magnify-node jimu-float-trailing" data-dojo-attach-point\x3d"magnifyNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"table-node" data-dojo-attach-point\x3d"tableNode"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-construct dojo/dom-style dojo/dom-attr dojo/on dijit/_TemplatedMixin dojo/store/Memory dgrid/OnDemandGrid dgrid/extensions/ColumnResizer jimu/exportUtils jimu/dijit/ExportChooser jimu/LayerInfos/LayerInfos jimu/dijit/Popup dojo/text!./RecordSetRenderer.html ../BaseResultRenderer".split(" "),function(l,e,f,c,b,g,h,k,r,s,t,m,u,v,w,x,y){return l([y,k],{baseClass:"jimu-gp-resultrenderer-base jimu-gp-renderer-table",templateString:x,
postCreate:function(){this.inherited(arguments);var a=[];if(!this.value.features||0===this.value.features.length)b.set(this.clearNode,"display","none"),b.set(this.exportNode,"display","none"),b.set(this.magnifyNode,"display","none"),this.tableNode.innerHTML=this.nls.emptyResult;else{b.set(this.magnifyNode,"display","");if(!this.config.useDynamicSchema&&this.param.defaultValue&&this.param.defaultValue.output&&this.param.defaultValue.output.fields)a=this.param.defaultValue.output.fields;else if(this.value.fields)a=
this.value.fields;else if(this.value.features&&0<this.value.features.length)for(var d in this.value.features[0].attributes)a.push({name:d});if(this.config.shareResults){var n,p=v.getInstanceSync();n=p.addTable({featureCollectionData:{layerDefinition:{fields:a},featureSet:this.value},title:this.param.label||this.param.name});b.set(this.clearNode,"display","");g.set(this.clearNode,"title",this.nls.clear);this.own(h(this.clearNode,"click",e.hitch(this,function(){p.removeTable(n);b.set(this.exportNode,
"display","none");b.set(this.clearNode,"display","none");b.set(this.magnifyNode,"display","none");this.labelContent.innerHTML=this.nls.cleared;c.empty(this.tableNode);this.table&&this.table.destroy()})))}d=f.map(this.value.features,function(a){return a.attributes});g.set(this.magnifyNode,"title",this.nls.enlargeView);this.own(h(this.magnifyNode,"click",e.hitch(this,this.magnifyTable)));if(this.config.showExportButton){g.set(this.exportNode,"title",this.nls.exportOutput);b.set(this.exportNode,"display",
"");var k=m.createDataSource({type:m.TYPE_TABLE,data:{fields:a,datas:d},filename:this.param.name});this.exportChooser=new u({dataSource:k});this.exportChooser.hide();c.place(this.exportChooser.domNode,this.domNode);this.own(h(this.exportNode,"click",e.hitch(this,function(a){a.preventDefault();a.stopPropagation();this.exportChooser.show(a.clientX,a.clientY)})))}var a=f.map(a,function(a){return{label:a.alias||a.name,field:a.name}}),q;f.some(this.value.fields,function(a){if("esriFieldTypeOID"===a.type)return q=
a.name,!0});d=new r({data:d,idProperty:q});this.table=new (l([s,t]))({columns:a,store:d});c.place(this.table.domNode,this.tableNode)}},startup:function(){this.inherited(arguments);this.table.startup()},magnifyTable:function(){var a=c.create("div",{"class":"gp-table-magnified"});c.place(this.table.domNode,a);a=new w({content:a,titleLabel:this.param.tooltip||this.param.label||"",container:"main-page",onClose:e.hitch(this,function(){c.place(this.table.domNode,this.tableNode);this.table.resize()})});
b.set(a.domNode,{top:"5%",left:"5%",width:"90%",height:"90%"});a.startup();this.table.resize()}})});