// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/html dijit/_WidgetBase jimu/dijit/Popup jimu/dijit/Message jimu/dijit/Filter dgrid/OnDemandGrid ../dgrid/Selection dgrid/extensions/ColumnHider dgrid/extensions/ColumnResizer dgrid/extensions/ColumnReorder dijit/Menu dijit/MenuItem dijit/Toolbar dijit/form/Button dijit/DropDownMenu dijit/form/ToggleButton dijit/form/DropDownButton dojo/Deferred dojo/when dojo/Evented dojo/touch dojo/store/Memory esri/config esri/lang esri/request esri/tasks/RelationParameters esri/tasks/RelationshipQuery esri/layers/FeatureLayer esri/tasks/QueryTask esri/tasks/query esri/tasks/ProjectParameters esri/geometry/Multipoint esri/geometry/normalizeUtils esri/IdentityManager dojo/_base/lang dojo/on dojo/aspect dojo/_base/array jimu/dijit/LoadingIndicator jimu/dijit/FieldStatistics jimu/SelectionManager jimu/CSVUtils jimu/utils ../utils dojo/query".split(" "),
function(z,h,C,D,v,E,F,G,H,I,J,K,p,L,w,M,N,O,r,P,Q,R,s,x,n,S,A,T,B,t,q,U,V,W,X,d,l,Y,m,Z,$,aa,ba,ca,y,u){return z([C,Q],{baseClass:"jimu-widget-attributetable-feature-table",_defaultFeatureCount:2E3,_defaultBatchCount:25,_batchCount:0,_filterObj:null,_currentDef:null,_requestStatus:"initial",map:null,matchingMap:!1,layerInfo:null,configedInfo:null,footerHeight:25,layer:null,loading:null,grid:null,footer:null,selectedRowsLabel:null,selectionRows:null,nls:null,_dblClickResult:null,actived:!1,showSelected:!1,
tableCreated:!1,_relatedQuery:!1,_relatedQueryIds:null,_selectionHandles:null,_selectionResults:null,constructor:function(a){a=a||{};this.set("map",a.map||null);this.set("matchingMap",!!a.matchingMap);this.set("layerInfo",a.layerInfo||null);this.set("layer",a.layer||null);this.set("configedInfo",a.configedInfo||null);this.set("relatedOriginalInfo",a.relatedOriginalInfo||null);this.set("relationship",a.relationship||null);this.set("syncSelection",!!a.syncSelection||!0)},postCreate:function(){this.inherited(arguments);
this._relatedQueryIds=[];this.createToolbar();this.loading=new Z;this.loading.placeAt(this.domNode);this.selectionManager=aa.getInstance();this._selectionResults=[];this.selectionRows=[];h.setAttr(this.domNode,"data-layerinfoid",d.getObject("layerInfo.id",!1,this));this.get("map")&&(this.own(l(this.map.root,R.release,d.hitch(this,function(){this._clickMap=!0}))),this.own(l(this.map,"extent-change",d.hitch(this,"_onExtentChange"))))},startup:function(){this.inherited(arguments);this.toolbarHeight=
parseInt(h.getStyle(this.toolbar.domNode,"height"),10)||0},setLayerDefinition:function(a){this._layerDefinition=a},getLayerDefinition:function(){return this._getLayerDifinition()},getFilterableFields:function(){if(this._layerDefinition&&this.configedInfo){var a=d.clone(this._layerDefinition);return this._getFilterableFields(a.fields,this.configedInfo.layer.fields)}return[]},getFilterObj:function(){return this._filterObj},setFilterObj:function(a){this._filterObj=a},showRefreshing:function(a){a?this.loading.show():
this.loading.hide()},active:function(){this.actived=!0},deactive:function(){this.actived=!1},cancelThread:function(){"fulfilled"!==this._requestStatus&&this._currentDef&&(this._currentDef.cancel({canceledBySelf:!0}),this._requestStatus="canceled")},isCanceled:function(){return"canceled"===this._requestStatus},createToolbar:function(){var a=new L({},h.create("div")),b=new M;this.showSelectedRecordsMenuItem=new p({label:this.nls.showSelectedRecords,iconClass:"esriAttributeTableSelectPageImage",onClick:d.hitch(this,
this.toggleSelectedRecords)});b.addChild(this.showSelectedRecordsMenuItem);this.showRelatedRecordsMenuItem=new p({label:this.nls.showRelatedRecords,iconClass:"esriAttributeTableSelectAllImage",onClick:d.hitch(this,this.onShowRelatedRecordsClick)});b.addChild(this.showRelatedRecordsMenuItem);this.filterMenuItem=new p({label:this.nls.filter,iconClass:"esriAttributeTableFilterImage",onClick:d.hitch(this,this.onFilterMenuItemClick)});b.addChild(this.filterMenuItem);this.toggleColumnsMenuItem=new p({label:this.nls.columns,
iconClass:"esriAttributeTableColumnsImage",onClick:d.hitch(this,this.onToggleColumnsClick)});b.addChild(this.toggleColumnsMenuItem);this.hideExportButton||(this.exportCSVMenuItem=new p({label:this.nls.exportFiles,showLabel:!0,iconClass:"esriAttributeTableExportImage",onClick:d.hitch(this,this.onExportCSVClick)}),b.addChild(this.exportCSVMenuItem));this.selectionMenu=new O({label:this.nls.options,iconClass:"esriAttributeTableOptionsImage",dropDown:b});a.addChild(this.selectionMenu);this.matchingCheckBox=
new N({checked:this.matchingMap?!0:!1,showLabel:!0,label:this.nls.filterByExtent,onChange:d.hitch(this,function(a){this.set("matchingMap",a);this._onMatchingCheckBoxChange(a)})});a.addChild(this.matchingCheckBox);this.zoomButton=new w({label:this.nls.zoomto,iconClass:"esriAttributeTableZoomImage",onClick:d.hitch(this,this.zoomTo)});a.addChild(this.zoomButton);this.clearSelectionButton=new w({label:this.nls.clearSelection,iconClass:"esriAttributeTableClearImage",onClick:d.hitch(this,this.clearSelection,
!0,!0)});a.addChild(this.clearSelectionButton);this.refreshButton=new w({label:this.nls.refresh,showLabel:!0,iconClass:"esriAttributeTableRefreshImage",onClick:d.hitch(this,this.refresh)});a.addChild(this.refreshButton);h.place(a.domNode,this.domNode);this.toolbar=a;this.own(l(this,"data-loaded,row-click,clear-selection",d.hitch(this,"changeToolbarStatus")))},startQuery:function(a){this.cancelThread();this._requestStatus="processing";this.loading.show();!a||!a.length?(this._relatedQuery=!1,this._relatedQueryIds=
[],this.queryByStoreObjectIds=null):this.queryByStoreObjectIds=a;this._currentDef=this._getLayerObject();this._currentDef.then(d.hitch(this,function(b){this.domNode&&(this.layer=b,(b=!this.layerInfo.isTable&&this.matchingMap&&this.map.extent||null)&&b.spatialReference&&b.spatialReference.isWebMercator()?(this._currentDef=W.normalizeCentralMeridian([b],null,d.hitch(this,function(a){return a[0]}))).then(d.hitch(this,function(b){this._doQuery(b,a)}),d.hitch(this,function(a){a&&"Request canceled"!==a.message&&
console.error(a);this.changeToolbarStatus();this.loading.hide()})):this._doQuery(b,a))}),d.hitch(this,function(a){console.error(a);this.changeToolbarStatus();this.loading.hide()}))},queryRecordsByRelationship:function(a){var b=a&&a.layer,c=a&&a.selectedIds;a&&a.relationship&&this.set("relationship",a.relationship);a&&a.relatedOriginalInfo&&this.set("relatedOriginalInfo",a.relatedOriginalInfo);var e=this.relationship;b&&e&&c&&0<c.length&&!ca.isEqual(this._relatedQueryIds,c)&&d.getObject("relatedOriginalInfo.layerObject.url",
!1,this)?(this.loading.show(),this._requestStatus="processing",this._relatedQuery=!0,this.matchingCheckBox.set("checked",!1),this.cancelThread(),this._currentDef=this._getLayerObject(),this._currentDef.then(d.hitch(this,function(a){if(this.domNode){this.layer=a;var g=[],k=this.layer;m.forEach(k.fields,function(a){(!n.isDefined(a.show)||!0===a.show||"esriFieldTypeOID"===a.type||n.isDefined(k.objectIdField)&&a.name===k.objectIdField)&&g.push(a.name)});a=new T;a.objectIds=c;a.outFields=g.length?g:["*"];
a.relationshipId=e.id;a.returnGeometry="esriGeometryPoint"===this.layer.geometryType;(this._currentDef=b.queryRelatedFeatures(a,function(a){return a})).then(d.hitch(this,function(a){if(this.domNode){var b={displayFieldName:e.objectIdField,fields:k.fields,features:[],fieldAliases:null},d={},f=function(a){var c=a.attributes[this.layer.objectIdField];d[c]||(d[c]=!0,b.features.push(a))},g;for(g in a){var l=a[g];m.forEach(l&&l.features,f,this)}h.destroy(this.tipNode);0<b.features.length?(this.grid||(this._removeTable(),
h.place(this.loading.domNode,this.domNode)),a=this._getOutFieldsFromLayerInfos(this.layer.objectIdField),this.queryExecute(a,b.features.length,!1,b)):(this.tipNode=h.toDom("\x3cdiv\x3e"+this.nls.noRelatedRecords+"\x3c/div\x3e"),this._removeTable(),h.place(this.tipNode,this.domNode),h.place(this.loading.domNode,this.domNode));this._relatedQueryIds=c;this.emit("data-loaded");this.loading.hide()}}),d.hitch(this,function(a){a&&"Request canceled"!==a.message&&console.error(a);h.destroy(this.tipNode);this.tipNode=
h.toDom("\x3cdiv\x3e"+this.nls.noRelatedRecords+"\x3c/div\x3e");this._removeTable();h.place(this.tipNode,this.domNode);h.place(this.loading.domNode,this.domNode);this.loading.hide();this.changeToolbarStatus()}))}}),d.hitch(this,function(a){console.error(a);this.loading.hide();this.changeToolbarStatus()}))):this.loading.hide()},getSelectedRows:function(){return!this.tableCreated?[]:this.selectionRows},zoomTo:function(){this._zoomToSelected()},toggleSelectedRecords:function(){this._relatedQuery&&!this.showSelected&&
0===this.getSelectedRows().length?(this._relatedQuery=!1,this._relatedQueryIds=[],this.layerInfo&&!this.layerInfo.isTable&&this.matchingCheckBox.set("checked",!0),this.startQuery(),this.showSelectedRecordsMenuItem.set("label",this.nls.showSelectedRecords),this.showSelected=!1,this.emit("show-all-records",{layerInfoId:this.layerInfo.id})):this.tableCreated&&(this.showSelected?(this.showAllSelectedRecords(),this.showSelectedRecordsMenuItem.set("label",this.nls.showSelectedRecords),this.showSelected=
!1,this.emit("show-all-records",{layerInfoId:this.layerInfo.id})):(this.showSelectedRecords(),this.showSelectedRecordsMenuItem.set("label",this.nls.showAllRecords),this.showSelected=!0,this.emit("show-selected-records",{layerInfoId:this.layerInfo.id})))},onShowRelatedRecordsClick:function(){this.emit("show-related-records",{layerInfoId:this.layerInfo.id,objectIds:this.getSelectedRows()})},onFilterMenuItemClick:function(){this.showRefreshing(!0);this.getLayerDefinition().then(d.hitch(this,function(a){if(this.domNode){a=
d.clone(a);var b=this.getFilterableFields();a.fields=b;var c=new E({noFilterTip:this.nls.noFilterTip,style:"width:100%;margin-top:22px;"});this._filterPopup=new D({titleLabel:this.nls.filter,width:720,height:485,content:c,buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){var a=c.toJson();a&&a.expr?(this.setFilterObj(a),this.clearSelection(!1),this.startQuery(),this._filterPopup.close(),this._filterPopup=null,this.emit("apply-filter",{layerInfoId:this.layerInfo.id,expr:a.expr})):new v({message:this.nls.setFilterTip})})},
{label:this.nls.cancel}]});(b=this.getFilterObj())?c.buildByFilterObj(this.layer.url,b,a):c.buildByExpr(this.layer.url,null,a)}}),d.hitch(this,function(a){this.domNode&&console.error(a)})).always(d.hitch(this,function(){this.showRefreshing(!1)}));this.emit("show-filter",{layerInfoId:this.layerInfo.id})},onToggleColumnsClick:function(){this.toggleColumns();this.emit("toggle-columns",{layerInfoId:this.layerInfo.id})},onExportCSVClick:function(){var a=new v({message:this.nls.exportMessage,titleLabel:this.nls.exportFiles,
autoHeight:!0,buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){this.exportToCSV();a.close()})},{label:this.nls.cancel}]});this.emit("export-csv",{layerInfoId:this.layerInfo.id})},onSelectionComplete:function(a){var b=a.features;b&&(0===b.length?this.clearSelection(!1):this._selectBySelf(b)||(this.clearSelection(!1),this._updateSelectRowsByFeatures(a.features)))},changeToolbarStatus:function(){if(this.tableCreated){var a=this.getSelectedRows();this.showSelected?this.showSelectedRecordsMenuItem.set("label",
this.nls.showAllRecords):this.showSelectedRecordsMenuItem.set("label",this.nls.showSelectedRecords);this.tableCreated&&a&&0<a.length&&this.layer&&this.layer.objectIdField?(this.showSelectedRecordsMenuItem.set("disabled",!1),this.clearSelectionButton.set("disabled",!1)):(this.showSelectedRecordsMenuItem.set("disabled",!0),this.clearSelectionButton.set("disabled",!0));this._relatedQuery&&(this.showSelectedRecordsMenuItem.set("disabled",!1),this.tableCreated&&(a&&0===a.length)&&this.showSelectedRecordsMenuItem.set("label",
this.nls.showAllRecords));this.showRelatedRecordsMenuItem.set("disabled",!0);if(this.layerInfo&&this.isSupportQueryToServer()&&a&&0<a.length&&this.layer&&this.layer.objectIdField){this._relatedDef&&!this._relatedDef.isFulfilled()&&this._relatedDef.cancel();var b=this.layerInfo.getRelatedTableInfoArray();this._relatedDef=b;b.then(d.hitch(this,function(a){if(this.domNode){var b=this.getSelectedRows();this.tableCreated&&(a&&0<a.length&&b&&0<b.length)&&this.showRelatedRecordsMenuItem.set("disabled",!1)}}))}this.tableCreated&&
this.isSupportQueryToServer()&&!this._relatedQuery?this.filterMenuItem.set("disabled",!1):this.filterMenuItem.set("disabled",!0);this.matchingCheckBox.set("disabled",!1);this.tableCreated?this.toggleColumnsMenuItem.set("disabled",!1):this.toggleColumnsMenuItem.set("disabled",!0);this.hideExportButton||(a&&0<a.length?this.exportCSVMenuItem.set("label",this.nls.exportSelected):this.exportCSVMenuItem.set("label",this.nls.exportAll),this.tableCreated?this.exportCSVMenuItem.set("disabled",!1):this.exportCSVMenuItem.set("disabled",
!0));this.layerInfo.isShowInMap()?this.tableCreated&&a&&0<a.length?this.zoomButton.set("disabled",!1):this.zoomButton.set("disabled",!0):this.zoomButton.set("disabled",!0);this.layerInfo.isTable&&(this.matchingCheckBox.set("disabled",!0),this.zoomButton.set("disabled",!0))}else this._relatedQuery?(this.showSelectedRecordsMenuItem.set("disabled",!1),this.showSelectedRecordsMenuItem.set("label",this.nls.showAllRecords)):this.showSelectedRecordsMenuItem.set("disabled",!0),this.showRelatedRecordsMenuItem.set("disabled",
!0),this.matchingCheckBox.set("disabled",!0),this.filterMenuItem.set("disabled",!0),this.toggleColumnsMenuItem.set("disabled",!0),this.hideExportButton||this.exportCSVMenuItem.set("disabled",!0),this.zoomButton.set("disabled",!0)},showSelectedRecords:function(){if(this.tableCreated){var a=this.layer.objectIdField,b=this.getSelectedRows();0<b.length&&this.grid&&(this.grid.store instanceof s?this.grid.set("query",d.hitch(this,function(c){return"number"===typeof c&&-1<b.indexOf(c)||-1<b.indexOf(c[a])?
!0:!1})):this.grid.set("query",function(){return b}))}},showAllSelectedRecords:function(){if(this.tableCreated&&this.showSelected){this.grid.set("query",{});var a=this.getSelectedRows();this._updateSelectRowsByIds(a)}},clearSelection:function(a,b){this.tableCreated&&(this.grid.clearSelection(),this.selectionRows=[],a&&this.grid.set("query",{}),b&&(this.selectionManager.clearSelection(this.layer),this._selectionResults=[]),this._closePopup(),this.setSelectedNumber(),this.showSelected=!1,this.emit("clear-selection"))},
refresh:function(){this.grid&&this.grid.clearSelection();this._relatedQuery||this.startQuery();this.emit("refresh",{layerInfoId:this.layerInfo.id})},exportToCSV:function(a){if(this.layerInfo&&this.layer&&this.tableCreated){var b=null,b=this.layer.objectIdField,c=this.getSelectedRowsData(),b=this._getOutFieldsFromLayerInfos(b),b=this._processExecuteFields(this.layer.fields,b),e={};c&&0<c.length?e.datas=c:this.grid.store instanceof s&&(c=this.grid.store.data,e.datas=c);"datas"in e&&"esriGeometryPoint"===
this.layer.geometryType&&(c=d.clone(e.datas),m.forEach(c,function(a){var b=a.geometry;b&&"point"===b.type&&("x"in a?a._x=b.x:a.x=b.x,"y"in a?a._y=b.y:a.y=b.y);delete a.geometry}),e.datas=c,b=d.clone(b),c="",c=-1!==b.indexOf("x")?"_x":"x",b.push({name:c,alias:c,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"}),c=-1!==b.indexOf("y")?"_y":"y",b.push({name:c,alias:c,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"}));e.fromClient=!1;e.withGeometry="esriGeometryPoint"===
this.layer.geometryType;e.outFields=b;e.formatNumber=!1;e.formatDate=!0;e.formatCodedValue=!0;e.popupInfo=this.layerInfo.getPopupInfo();return ba.exportCSVFromFeatureLayer(a||this.configedInfo.name,this.layer,e)}},toggleColumns:function(){this.tableCreated&&this.grid._toggleColumnHiderMenu()},changeHeight:function(a){this.grid&&0<=a-this.toolbarHeight-this.footerHeight&&h.setStyle(this.grid.domNode,"height",a-this.toolbarHeight-this.footerHeight+"px")},isSupportQueryToServer:function(){var a=this.layer&&
"esri.layers.CSVLayer"===this.layer.declaredClass,b=this.layer&&"esri.layers.StreamLayer"===this.layer.declaredClass;return this.layer&&this.layer.url&&this.configedInfo.layer.url&&!a&&!b},isSupportQueryOnClient:function(){var a=this.layer&&"esri.layers.CSVLayer"===this.layer.declaredClass,b=this.layer&&"esri.layers.StreamLayer"===this.layer.declaredClass;return!(this.layer&&this.layer.url&&this.configedInfo.layer.url)||a||b},destroy:function(){this._destroyed||(this.layer=this.configedInfo=this.layerInfo=
null,this._selectionHandles&&m.forEach(this._selectionHandles,function(a){a&&a.remove&&a.remove()}),this._closePopup(),this._filterPopup&&this._filterPopup.domNode&&(this._filterPopup.close(),this._filterPopup=null),this._dblClickResult=null,this.grid&&this.grid.destroy(),this.relationship=this.nls=this.map=null,this._currentDef&&!this._currentDef.isFulfilled()&&this._currentDef.cancel({canceledBySelf:!0}),this._relatedDef&&!this._relatedDef.isFulfilled()&&this._relatedDef.cancel({canceledBySelf:!0}),
this.inherited(arguments))},_selectBySelf:function(a){a=a||[];return a.length!==this._selectionResults.length?!1:m.every(this._selectionResults,function(b){return-1<a.indexOf(b)})},_updateSelectRowsByFeatures:function(a){a=m.map(a,d.hitch(this,function(a){return a.attributes[this.layer.objectIdField]}));this._updateSelectRowsByIds(a)},_updateSelectRowsByIds:function(a){this.grid&&this.tableCreated&&(this.selectionRows=a,m.forEach(a,d.hitch(this,function(a){this.grid.select(a)})),this.setSelectedNumber(),
this.changeToolbarStatus())},_removeTable:function(){this.grid&&this.grid.domNode&&(this.grid.destroy(),this.grid=null);this.footer&&(h.destroy(this.footer),this.selectedRowsLabel=this.footer=null);this.tableCreated=!1},_onMatchingCheckBoxChange:function(a){this.tableCreated&&!this._relatedQuery&&(this.cancelThread(),this.queryByStoreObjectIds=null,this.startQuery());if("fulfilled"===this._requestStatus&&this.tableCreated&&this._relatedQuery)if(a)this.queryByStoreObjectIds=m.map(this.grid.store.data,
d.hitch(this,function(a){return a[this.layer.objectIdField]})),this.startQuery(this.queryByStoreObjectIds);else{var b=this._relatedQueryIds;this._relatedQueryIds=[];this.queryRecordsByRelationship({layer:this.relatedOriginalInfo.layerObject,selectedIds:b})}a||(this._currentExtent=null)},_closePopup:function(){var a=this.map.infoWindow.getSelectedFeature(),b=a&&this._dblClickResult&&a===this._dblClickResult,a=a&&a._layer===this.layer;if(this.domNode&&(b||a))this.map.infoWindow.hide(),this._dblClickResult=
null},_getLayerObject:function(){function a(a){this._selectionHandles&&m.forEach(this._selectionHandles,function(a){a&&a.remove&&a.remove()});this._selectionHandles=[];this._selectionHandles.push(l(a,"selection-complete",d.hitch(this,"onSelectionComplete")))}return(this._currentDef=this.layerInfo.getLayerObject()).then(d.hitch(this,function(b){var c=new r;"esri.layers.ArcGISImageServiceLayer"===b.declaredClass||"esri.layers.ArcGISImageServiceVectorLayer"===b.declaredClass?(b=new B(b.url),this.own(l(b,
"load",d.hitch(this,function(b){d.hitch(this,a)(b.layer);c.resolve(b.layer)})))):(d.hitch(this,a)(b),c.resolve(b));return c}))},_getLayerDifinition:function(){return this._layerDefinition?P(d.clone(this._layerDefinition)):S({url:this.layer.url,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(d.hitch(this,function(a){this.setLayerDefinition(a);return this.getLayerDefinition()}))},_getFilterableFields:function(a,b){return m.filter(a,function(a){return m.some(b,function(b){return a.name===
b.name&&(b.show||!n.isDefined(b.show))&&d.mixin(a,b)})})},_doQuery:function(a,b){if(this.layer){var c=this.layer.objectIdField;this.isSupportQueryToServer()?this._queryToServer(a,c,b):this.isSupportQueryOnClient()&&this._queryOnClient(a,c,b)}},_queryOnClient:function(a,b,c){var e={};e.features="esri.layers.StreamLayer"===this.layer.declaredClass?this.layer.getLatestObservations():this.layer.graphics;c&&0<c.length&&(e.features=m.filter(e.features,function(a){return-1<c.indexOf(a.attributes[this.layer.objectIdField])},
this));var f=this.layer.fields,g=this.configedInfo.layer.fields;e.fields=g?m.filter(g,d.hitch(this,function(a){n.isDefined(a.show)||(a.show=!0);if(a.name===b&&("esriFieldTypeOID"===a.type||"esriFieldTypeInteger"===a.type))a._pk=!0;for(var c=0,e=f.length;c<e;c++)f[c].name===a.name&&!a.type&&(a.type=f[c].type);return a.show||a._pk})):m.filter(f,d.hitch(this,function(a){n.isDefined(a.show)||(a.show=!0);if(a.name===b&&("esriFieldTypeOID"===a.type||"esriFieldTypeInteger"===a.type))a._pk=!0;return a.show||
a._pk}));for(var g=[],k=e.features.length,h=0;h<k;h++)e&&(e.features&&e.features[h]&&e.features[h].geometry)&&g.push(e.features[h].geometry);a&&x.defaults.geometryService&&0<g.length?(k=new A,k.geometries1=g,k.geometries2=[a],k.relation=A.SPATIAL_REL_INTERSECTION,(this._currentDef=x.defaults.geometryService.relation(k,d.hitch(this,function(a){return a}))).then(d.hitch(this,function(b,c){for(var e=c.length,d=[],f=0;f<e;f++)d.push(b.features[c[f].geometry1Index]);b.features=d;this.queryExecute(b.fields,
b.features.length,!1,b,a)},e),d.hitch(this,function(a){a&&"Request canceled"!==a.message&&console.error(a);this.changeToolbarStatus();this.loading.hide()}))):this.queryExecute(e.fields,e.features.length,!1,e,a)},_queryToServer:function(a,b,c){this._getFeatureCount(a,c).then(d.hitch(this,function(e){if(this.domNode)if(c)this._queryFeatureLayer(a,b,e,!1,c);else{var f=this.layer,g=n.isDefined(f.maxRecordCount)?f.maxRecordCount:1E3;this._batchCount=Math.min(g,this._defaultBatchCount);if(e<=g||!this.layer.objectIdField)this._queryFeatureLayer(a,
b,e,!1);else{var k=this._getOutFieldsFromLayerInfos(b),h={fields:this.layer.fields};this.layer._recordCounts=e;f.advancedQueryCapabilities&&f.advancedQueryCapabilities.supportsPagination?this.queryExecute(k,e,!0,h,a):this._getFeatureIds(b,a).then(d.hitch(this,function(b){this.domNode&&(this.layer._objectIds=b,this.queryExecute(k,e,!0,h,a))}),d.hitch(this,function(a){console.error(a);this.changeToolbarStatus()}))}}}),d.hitch(this,function(a){console.error(a);this.changeToolbarStatus()}))},_getFeatureCount:function(a,
b){var c=new r,e=new t(this.configedInfo.layer.url),f=new q;f.returnGeometry=!1;f.where=this._getLayerFilterExpression();b&&(f.where+=" AND "+this.layer.objectIdField+" IN ("+b.join()+")");a&&(f.geometry=a);(this._currentDef=e.executeForCount(f,d.hitch(this,function(a){return a}))).then(d.hitch(this,function(a){c.resolve(a)}),d.hitch(this,function(a){a&&"Request canceled"!==a.message&&(console.error(a),console.log("Could not get feature count."));this.loading.hide();c.reject(a)}));return c},_queryFeatureLayer:function(a,
b,c,e,f){var g=new t(this.configedInfo.layer.url),k=new q;k.where=this._getLayerFilterExpression();f&&b&&(k.where+=" AND "+b+" IN ("+f.join()+")");var h=this._getOutFieldsFromLayerInfos(b);0<h.length?(f=m.map(h,function(a){return a.name}),k.outFields=f):k.outFields=["*"];a&&(k.geometry=a,k.spatialRelationship=q.SPATIAL_REL_INTERSECTS);k.outSpatialReference=d.clone(this.map.spatialReference);k.returnGeometry="esriGeometryPoint"===this.layer.geometryType;b&&(k.orderByFields=[b+" ASC"]);(this._currentDef=
g.execute(k,d.hitch(this,function(a){return a}))).then(d.hitch(this,function(b){this.queryExecute(h,c,e,b,a)}),d.hitch(this,function(a){a&&"Request canceled"!==a.message&&console.error(a);this.changeToolbarStatus();this.loading.hide()}))},_getFeatureIds:function(a,b){var c=new r,e=new t(this.configedInfo.layer.url),f=new q;f.returnGeometry=!1;f.returnIdsOnly=!0;f.where=this._getLayerFilterExpression();if(this.layer._orderByFields||a)f.orderByFields=this.layer._orderByFields||[a+" ASC"];b&&(f.geometry=
b);(this._currentDef=e.executeForIds(f,d.hitch(this,function(a){return a}))).then(d.hitch(this,function(a){c.resolve(a)}),d.hitch(this,function(a){a&&"Request canceled"!==a.message&&(console.error(a),console.log("Could not get feature Ids"));c.resolve([])}));return c},queryExecute:function(a,b,c,e,f){var g=[],g=null,k={};if(this.domNode){e.fields=this._processExecuteFields(this.layer.fields,a);c?g=y.generateCacheStore(this.layer,b,this._batchCount,this._getLayerFilterExpression(),f):(g=m.map(e.features,
d.hitch(this,function(a){var b=d.clone(a.attributes);return d.mixin(b,{geometry:a.geometry})})),g=y.generateMemoryStore(g,this.layer.objectIdField));a=this.layer.typeIdField;var k=this.layer.types,l=d.getObject("advancedQueryCapabilities.supportsOrderBy",!1,this.layer),da=d.getObject("advancedQueryCapabilities.supportsPagination",!1,this.layer),ea=d.getObject("advancedQueryCapabilities.supportsStatistics",!1,this.layer),k=y.generateColumnsFromFields(this.layerInfo.getPopupInfo(),e.fields,a,k,l&&da||
!c,ea);this.layer.hasAttachments&&(this.layer.objectIdField&&this.configedInfo.showAttachments)&&(k.attachmentsColumn=this.formatAttachmentsColumn());c=20+100*e.fields.length<h.getMarginBox(this.domNode).w;this.createTable(k,g,b,c);this._currentExtent=f;b=this.layer.getSelectedFeatures();this.selectionRows&&0<this.selectionRows.length?this._updateSelectRowsByIds(this.selectionRows):b&&0<b.length?this._updateSelectRowsByFeatures(b):this.grid.clearSelection();this.changeToolbarStatus();this.emit("data-loaded")}},
formatAttachmentsColumn:function(){var a={label:this.nls.attachments,className:"attachments-column",hidden:!1,unhidable:!0,field:"at-show-attachments",sortable:!1,_cache:{sortable:!1,statistics:!1}};a.renderCell=d.hitch(this,function(a,c,e){var f=a[this.layer.objectIdField];this.layer.queryAttachmentInfos(f,d.hitch(this,function(a){var b=m.map(a,d.hitch(this,function(a){var b=a.name&&/\.(png|jpg|jpeg|gif)$/gi.test(a.name)?"image-type":"file-type",c=X.findCredential(this.layer.url);return'\x3cli class\x3d"'+
b+'"\x3e\x3ca class\x3d"jimu-ellipsis" target\x3d"_blank" href\x3d"'+(this.layer.url+"/"+f+"/attachments/"+a.id+(c?"?token\x3d"+c.token:""))+'"\x3e'+a.name+"\x3c/a\x3e\x3c/li\x3e"})),c="";0<a.length&&(c=" "+this.nls.files);c='\x3cdiv class\x3d"attachment-infos"\x3e\x3cdiv class\x3d"show-attachments-div"\x3e\x3cspan class\x3d"show-attachments"\x3e'+a.length+c+'\x3c/span\x3e\x3c/div\x3e\x3cdiv class\x3d"attachment-popup"\x3e\x3cdiv class\x3d"attachment-popup-header"\x3e\x3cspan\x3e'+b.length+"\x26nbsp;"+
this.nls.files+'\x3c/span\x3e\x3cspan class\x3d"close jimu-float-trailing"\x3e\x3c/span\x3e\x3c/div\x3e\x3cul class\x3d"attachment-popup-content"\x3e'+b.join("")+"\x3c/ul\x3e\x3c/div\x3e\x3c/div\x3e";c=h.toDom(c);0<a.length&&(a=u(".show-attachments-div",c)[0],h.addClass(a,"has-attachments"));e.appendChild(c);this.own(l(e,"click",d.hitch(this,function(a){a=a&&a.target;if(h.hasClass(a,"show-attachments-div")||h.hasClass(a,"show-attachments")||h.hasClass(a,"close")){a=this._visibleAttachmentPopup;var c=
u(".attachment-popup",e)[0];c&&0<b.length&&h.toggleClass(c,"show");h.hasClass(c,"show")?this._visibleAttachmentPopup=c:this._visibleAttachmentPopup=null;a&&a!==c&&h.toggleClass(a,"show")}})))}),d.hitch(this,function(a){console.error(a)}))});return a},createTable:function(a,b,c,e){if(this.grid)this.grid.set("store",b),this.grid.set("columns",a),this.grid.refresh();else{var f={};f.columns=a;f.store=b;f.keepScrollPosition=!0;f.pagingDelay=1E3;f.allowTextSelection=!0;f.deselectOnRefresh=!1;this.layer.objectIdField||
(f.minRowsPerPage=this.layer.maxRecordCount||1E3,f.maxRowsPerPage=this.layer.maxRecordCount||1E3,f.selectionMode="none");this.grid=new (z([F,G,H,I,J]))(f,h.create("div"));h.place(this.grid.domNode,this.domNode);this.grid.startup();this.tipNode&&h.destroy(this.tipNode);this.own(l(this.ownerDocument,"keydown",d.hitch(this,function(a){this.grid&&(this.grid.allowTextSelection&&a.shiftKey)&&this.grid._setAllowTextSelection(!1)})));this.own(l(this.ownerDocument,"keyup",d.hitch(this,function(){this.grid&&
!this.grid.allowTextSelection&&this.grid._setAllowTextSelection(!0)})));this.layer.objectIdField&&(this.own(l(this.grid,".dgrid-header .dgrid-cell:click",d.hitch(this,this._onHeaderClick))),this.own(l(this.grid,"dgrid-columnstatechange",d.hitch(this,this._onColumnStateChange))),this.own(l(this.grid,".selection-handle-column:click",d.hitch(this,this._onSelectionHandleClick))),this.own(l(this.grid,".dgrid-row:dblclick",d.hitch(this,this._onDblclickRow))),this.own(l(this.grid,"dgrid-sort",d.hitch(this,
function(a){this.emit("sort",a)}))),a=this.map.getLayer(this.layer.id),this.syncSelection&&a&&this.own(l(a,"click",d.hitch(this,this._onFeaturelayerClick))))}this.layer.objectIdField&&this.grid.set("sort",this.layer.objectIdField,!1);this.getParent()&&(a=u(".dgrid-scroller",this.grid.domNode)[0],f=u(".dgrid-header",this.grid.domNode)[0],b=h.getComputedStyle(a),f=h.getMarginBox(f),b=parseInt(b.marginTop,10),isFinite(b)&&(f&&b<f.h)&&h.setStyle(a,"marginTop",f.h+"px"));e?h.addClass(this.domNode,"auto-width"):
h.removeClass(this.domNode,"auto-width");this.footer?h.empty(this.footer):this.footer=h.create("div",{"class":"jimu-widget-attributetable-feature-table-footer"},this.domNode);c=h.create("div",{"class":"dgrid-status self-footer",innerHTML:c+"\x26nbsp;"+(this.layerInfo.isTable?this.nls.records:this.nls.features)+"\x26nbsp;"},this.footer);this.selectedRowsLabel=h.create("div",{"class":"dgrid-status self-footer",innerHTML:"0\x26nbsp;"+this.nls.selected+"\x26nbsp;",style:{display:this.layer.objectIdField?
"":"none"}},c,"after");c=h.getStyle(this.domNode,"height");this.changeHeight(c);this._requestStatus="fulfilled";this.tableCreated=!0;h.place(this.loading.domNode,this.grid.domNode);this.loading.hide()},getSelectedRowsData:function(){if(!this.grid)return null;var a=this.layer.objectIdField,b=this.grid.store,c=b._entityData||b.data,b=this.getSelectedRows();return m.map(b,d.hitch(this,function(b){for(var d=0,g=c.length;d<g;d++)if(c[d]&&c[d][a]===b)return c[d];return{}}))||[]},setSelectedNumber:function(){if(this.selectedRowsLabel&&
this.grid){var a=this.getSelectedRows(),b=0;if(this.grid.store instanceof s){var c=m.map(this.grid.store.data,function(a){return a[this.layer.objectIdField]},this);m.forEach(a,function(a){-1<c.indexOf(a)&&b++})}else b=a.length;this.selectedRowsLabel.innerHTML="\x26nbsp;\x26nbsp;"+b+" "+this.nls.selected+"\x26nbsp;\x26nbsp;"}},_setSelection:function(a){this._selectionResults=a=a||[];this.selectionManager.setSelection(this.layer,a)},_zoomToExtentByFeatures:function(a){return this.getExtent(a).then(d.hitch(this,
function(a){if(a&&this.domNode){var c=null;"point"===a.type?(c=15,c=-1<this.map.getMaxZoom()?this.map.getMaxZoom():0.1,c=this.map.centerAndZoom(a,c)):c=this.map.setExtent(a.expand(1.1));return c.then(function(){return a})}}))},_showMapInfoWindowByFeatures:function(a,b){if(b&&0!==b.length&&this.domNode){var c=this.map.infoWindow,e=this.layerInfo.isPopupEnabled()&&this.layerInfo.getInfoTemplate();if(c&&c.setFeatures&&1===b.length&&e){m.forEach(b,d.hitch(this,function(a){a._layer=this.layerInfo.layerObject;
a.setInfoTemplate(e)}));c.setFeatures(b);var f=null,f="point"===a.type?b[0].geometry:a.getCenter();c.show(f,{closetFirst:!0});this._dblClickResult=b[0];this.syncWithMapInfowindow(this._dblClickResult)}}},selectFeatures:function(a,b){b&&0<b.length?("rowclick"===a||"selectall"===a?this._setSelection(b):("zoom"===a||"row-dblclick"===a)&&this._zoomToExtentByFeatures(b).then(d.hitch(this,function(c){"row-dblclick"===a&&this.domNode&&this._showMapInfoWindowByFeatures(c,b)}),d.hitch(this,function(a){a&&
"Request canceled"!==a.message&&console.error(a)})),this.setSelectedNumber()):this._popupMessage(this.nls.dataNotAvailable)},syncWithMapInfowindow:function(a){var b=this.map.infoWindow,c=d.isArray(a)?a:[a];l.once(b,"hide",d.hitch(this,function(){e&&e.remove&&(e.remove(),e=null)}));var e=Y.after(b,"show",d.hitch(this,function(){var a=b.getSelectedFeature(),a=a&&c[0]===a,d=b.features.indexOf(c[0]);!a&&-1<d?b.select(d):this.domNode&&!a&&(e&&e.remove)&&(e.remove(),e=null)}))},getGraphicsFromLocalFeatureLayer:function(a){for(var b=
[],c,e,d=a.length,g=this.layer.graphics.length,h=this.layer.objectIdField,m=0;m<d;m++)for(var l=0;l<g;l++)if(c=this.layer.graphics[l].attributes[h]+"",e=a[m]+"",c===e){b.push(this.layer.graphics[l]);break}return b},getExtent:function(a){var b=new r,c,e,f=a.length;if(1===f&&a[0].geometry&&"point"===a[0].geometry.type)c=a[0].geometry;else{if(1===f&&!a[0].geometry)return b.reject(Error("AttributeTable.getExtent:: extent was not projected.")),b;for(var g=0;g<f;g++)a[g].geometry?"point"===a[g].geometry.type?
(e||(e=new V(a[g].geometry.spatialReference)),e.addPoint(a[g].geometry),g===f-1&&(c=e.getExtent())):c=c?c.union(a[g].geometry.getExtent()):a[g].geometry.getExtent():console.error("unable to get geometry of the reocord: ",a[g])}if(!c||!c.spatialReference)return b.reject(Error("AttributeTable.getExtent:: extent was not projected.")),b;a=this.map.spatialReference;c.spatialReference.equals(a)?b.resolve(c):(e=new U,e.geometries=[c],e.outSR=a,x.defaults.geometryService.project(e,d.hitch(this,function(a){this.domNode&&
(a&&a.length?b.resolve(a[0]):b.reject(Error("AttributeTable.getExtent:: extent was not projected.")))}),d.hitch(this,function(a){a||(a=Error("AttributeTable.getExtent:: extent was not projected."));b.reject(a)})));return b},_onFeaturelayerClick:function(a,b){if(this.actived){var c=d.getObject("graphic",!1,a),e=d.getObject("graphic.attributes",!1,a);e&&(c&&c._layer===this.layer)&&((c=this.map.infoWindow.getSelectedFeature())&&(c._layer===this.layer&&!b)&&this.map.infoWindow.hide(),e=e[this.layer.objectIdField],
this.showSelected&&this.toggleSelectedRecords(),this._getIndexOfIdInGrid(e).then(d.hitch(this,function(b){-1!==b&&(this.grid.scrollTo({x:0,y:this.grid.rowHeight*b}),this.map.infoWindow.features&&(b=this.map.infoWindow.features.indexOf(a.graphic),this.map.infoWindow.select(b)),l.once(this.map.infoWindow,"selection-change",d.hitch(this,function(){var b=this.map.infoWindow.getSelectedFeature(),c=d.getObject("_layer",!1,b);b===a.graphic||c!==this.layer||this._onFeaturelayerClick({graphic:b},!0)})),this.syncWithMapInfowindow(a.graphic))})))}},
_getIndexOfIdInGrid:function(a){var b=new r,c=-1,e=d.getObject("store.objectIds",!1,this.grid),c=null,c=this.grid.get("sort")[0];if(this._relatedQuery)return b.resolve(-1),b;if(this.grid.store instanceof s)a=this.grid.store.get(a),e=this.grid.store.data,a?c&&c.attribute&&n.isDefined(c.descending)?(e=d.clone(e),c=function(a,b){return function(c,d){return c[a]===d[a]?0:c[a]<d[a]?b?1:-1:b?-1:1}}(c.attribute,c.descending),e.sort(c),e=m.map(e,function(a){return a[this.layer.objectIdField]},this),c=e.indexOf(a[this.layer.objectIdField])):
c=e.indexOf(a):c=-1,b.resolve(c);else if(e&&0<e.length)c=e.indexOf(a),b.resolve(c);else{e=new q;e.returnGeometry=!1;e.where=this._getLayerFilterExpression()+" AND "+this.layer.objectIdField+" \x3c "+a;if(c&&(c.attribute!==this.layer.objectIdField||c.descending))return b.resolve(-1),b;this.matchingMap&&(!this._relatedQuery&&this._currentExtent)&&(e.geometry=this._currentExtent);(this._currentDef=this.layer.queryCount(e)).then(d.hitch(this,function(a){b.resolve(a)}),d.hitch(this,function(a){b.reject(a)}))}return b},
_zoomToSelected:function(){if(this.configedInfo&&this.tableCreated){var a=this.getSelectedRows();this._goToFeatures(a,"zoom")}},_goToFeatures:function(a,b){if(0!==a.length){var c=this.getGraphicsFromLocalFeatureLayer(a);this.isSupportQueryToServer()&&a.length!==c.length?this._queryFeaturesByIds(a,b):this.selectFeatures(b,c)}},_onDblclickRow:function(a){this.layerInfo&&this.layerInfo.isShowInMap()&&(a=[this.grid.row(a).id],this._goToFeatures(a,"row-dblclick"))},_queryFeaturesByIds:function(a,b){var c=
new q;c.objectIds=a;c.returnGeometry=!0;c.outSpatialReference=d.clone(this.map.spatialReference);c.outFields=["*"];var e=this.layer,f="esri.layers.CSVLayer"===e.declaredClass;e.url&&!f?(new t(e.url)).execute(c,d.hitch(this,function(a){this.selectFeatures(b,a.features)}),d.hitch(this,this._errorSelectFeatures)):e.selectFeatures(c,B.SELECTION_NEW,d.hitch(this,this.selectFeatures,b),d.hitch(this,this._errorSelectFeatures))},_onHeaderClick:function(a){var b=this.grid.cell(a);this._showColumnMenu(b.column,
b,a.target,{x:a.pageX,y:a.pageY})},_showColumnMenu:function(a,b,c,e){var f=d.getObject("_cache",!1,a);if(f){var g=new K({});h.addClass(g.domNode,"jimu-widget-attributetable-feature-menu");var k=this;if(f.sortable){var n=["iconSortAscending","iconSortDescending"];m.forEach([this.nls.sortAsc,this.nls.sortDes],function(b,c){var d=new p({label:b,iconClass:n[c],baseClass:"menuItemClass",onClick:function(){0===c?k.grid.set("sort",a.field,!1):1===c&&k.grid.set("sort",a.field,!0)}});g.addChild(d)})}f.statistics&&
(f=new p({label:this.nls.statistics,iconClass:"iconTableStatistics",baseClass:"menuItemClass",onClick:d.hitch(this,function(){var b={layer:this.layer,filterExpression:this._getLayerFilterExpression(),fieldNames:[a.field]};this.matchingMap&&(b.geometry=this._currentExtent);if(this.showSelected){var c=this._getSelectedIds();b.filterExpression+=" AND "+this.layer.objectIdField+" IN ("+c.join()+")"}else this.queryByStoreObjectIds&&0<this.queryByStoreObjectIds.length&&(b.filterExpression+=" AND "+this.layer.objectIdField+
" IN ("+this.queryByStoreObjectIds.join()+")");this.fieldStatistics=new $;this.fieldStatistics.showContentAsPopup(b)})}),g.addChild(f));f=g.getChildren();g.startup();g._openMyself({target:c,delegatedTarget:b,iframe:null,coords:e});this.own(l(g,"Close",d.hitch(this,function(){var a=this.get("columnMenu");a&&(a.destroyRecursive(),this.set("columnMenu",null))})));this.set("columnMenu",g);1>f.length&&l.emit(g,"Close")}},_onColumnStateChange:function(a){if(a&&a.grid&&a.grid.columns){var b=0,c;for(c in a.grid.columns)a.grid.columns[c].hidden||
b++;20+100*b-1<h.getMarginBox(this.domNode).w?h.addClass(this.domNode,"auto-width"):h.removeClass(this.domNode,"auto-width")}},_onSelectionHandleClick:function(){var a=this._getSelectedIds();this.selectionRows=a;this._closePopup();this.layerInfo.isTable||(0<a.length?this._goToFeatures(a,"rowclick"):this._setSelection([]));this.setSelectedNumber();this.emit("row-click",{table:this,selectedIds:a})},_onExtentChange:function(a){var b=d.getObject("delta.x",!1,a),c=d.getObject("delta.y",!1,a);a=this._clickMap&&
!a.levelChange?isFinite(b)&&isFinite(c)&&(0<Math.abs(b)||0<Math.abs(c)):!0;this._clickMap=!1;a&&this.matchingMap&&(this.actived&&this.layerInfo&&!this.layerInfo.isTable)&&this.startQuery(this.queryByStoreObjectIds)},_getLayerFilterExpression:function(){var a=this.layerInfo.getFilter();return a?a:"1\x3d1"},_getOutFieldsFromLayerInfos:function(a){var b=this.configedInfo.layer.fields,c=[];b&&m.forEach(b,d.hitch(this,function(b){n.isDefined(b.show)||(b.show=!0);if(b.name===a&&("esriFieldTypeOID"===b.type||
"esriFieldTypeInteger"===b.type||!b.type))b._pk=!0;(b.show||b._pk)&&c.push(b)}));return c},_processExecuteFields:function(a,b){if(a&&0<a.length){var c=[];if(!b.length)return a;for(var e=0,f=b.length;e<f;e++)for(var g=0;g<a.length;g++)if(b[e].name===a[g].name&&(b[e].type===a[g].type||!b[e].type))a[g]=d.mixin(a[g],b[e]),c.push(a[g]);return c}return b},_getSelectedIds:function(){var a=[],b=this.grid.selection,c;for(c in b)b[c]&&(isFinite(c)?a.push(parseInt(c,10)):a.push(c));return a},_errorSelectFeatures:function(a){console.error(a)},
_popupMessage:function(a){var b=new v({message:a,buttons:[{label:this.nls.ok,onClick:d.hitch(this,function(){b.close()})}]});this.loading.hide()}})});