// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on esri/geometry/geometryEngine esri/geometry/Polyline esri/geometry/webMercatorUtils esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query jimu/CSVUtils".split(" "),function(A,n,u,l,g,h,B,q,v,C,w,x,D,y,z,E,F,G,H){return A("ProximityInfo",null,{constructor:function(b,
c,a){this.tab=b;this.container=c;this.parent=a;this.graphicsLayer=this.buffer=this.incident=this.featureLayer=null;this.specialFields={}},updateForIncident:function(b,c,a){if(this.featureLayer)this.processIncident(b,c,a);else if(0<this.tab.tabLayers.length){var d=new D(this.tab.tabLayers[0].url);q(d,"load",n.hitch(this,function(){d.capabilities&&-1<d.capabilities.indexOf("Query")?(this.featureLayer=d,this.processIncident(b,c,a)):this._processError()}));q(this.parent.opLayers,"layerInfosFilterChanged",
n.hitch(this,this._layerFilterChanged))}},_layerFilterChanged:function(b){if(!(null===this.featureLayer||null===this.incident||null===this.buffer||null===this.graphicsLayer)){var c=this.tab.tabLayers[0].id;l.forEach(b,n.hitch(this,function(a){c===a.id&&this.processIncident(this.incident,this.buffer,this.graphicsLayer)}))}},processIncident:function(b,c,a){this.container.innerHTML="";g.add(this.container,"loading");var d=[];this.incident=b;this.buffer=c;this.graphicsLayer=a;this.graphicsLayer.clear();
var f=this.tab.tabLayers[0].id,e="";this.parent.opLayers.traversal(function(a){if(f===a.id&&a.getFilter())return e=a.getFilter(),!0});a=new G;a.returnGeometry=!0;a.geometry=c.geometry;a.where=e;a.outFields=this._getFields(this.featureLayer);a.outSpatialReference=this.parent.map.spatialReference;this.featureLayer.queryFeatures(a,n.hitch(this,function(a){var c=this._getFields(this.featureLayer);a=a.features;if(0<a.length)for(var f=0;f<a.length;f++){for(var e=a[f],g={DISTANCE:this._getDistance(b.geometry,
e.geometry)},h=0;h<c.length;h++)g[c[h]]=e.attributes[c[h]];e.attributes=g;d.push(e)}this._processResults(d)}),n.hitch(this,this._processError))},_processError:function(){this.container.innerHTML="";g.remove(this.container,"loading");this.container.innerHTML=this.parent.nls.noFeaturesFound},_processResults:function(b){this.container.innerHTML="";g.remove(this.container,"loading");this.graphicsLayer.clear();if(0===b.length)this.container.innerHTML=this.parent.nls.noFeaturesFound;else{b.sort(this._compareDistance);
var c=h.create("div",{id:"tpc",style:"width:"+220*(b.length+1)+"px;"},this.container);g.add(c,"IMT_tabPanelContent");var a=h.create("div",{},c);g.add(a,"IMTcol");a=h.create("div",{innerHTML:this.parent.nls.downloadCSV},a);g.add(a,"btnExport");q(a,"click",n.hitch(this,this._exportToCSV,b));for(var a=this.parent.nls[this.parent.config.distanceUnits],d=0;d<b.length;d++){var f=d+1,e=b[d],k=e.geometry,l=k;"point"!==k.type&&(l=k.getExtent().getCenter());var e=e.attributes,p=a+": "+Math.round(100*e.DISTANCE)/
100,k="",m=0,r;for(r in e)"DISTANCE"!==r&&3>m&&(k+=this._getFieldValue(r,e[r])+"\x3cbr/\x3e",m+=1);m=h.create("div",{id:"Feature_"+f},c);g.add(m,"IMTcolRec");var s=h.create("div",{},m);g.add(s,"IMTcolRecBar");var t=h.create("div",{innerHTML:f},s);g.add(t,"IMTcolRecNum");B.set(t,"backgroundColor",this.parent.config.color);q(t,"click",n.hitch(this,this._zoomToLocation,l));p=h.create("div",{innerHTML:p},s);g.add(p,"IMTcolDistance");this.parent.config.enableRouting&&(p=h.create("div",{},s),g.add(p,"IMTcolDir"),
q(p,"click",n.hitch(this,this._routeToIncident,l)));k=h.create("div",{innerHTML:k},m);g.add(k,"IMTcolInfo");k=new z(z.STYLE_SOLID,new u.fromString(this.parent.config.color),1);k=new y(y.STYLE_CIRCLE,24,k,new u.fromString(this.parent.config.color));m=new E;m.family="Arial";m.size="12px";f=new F(f,m,"#ffffff");f.setOffset(0,-4);this.graphicsLayer.add(new x(l,k,e));this.graphicsLayer.add(new x(l,f,e))}}},_exportToCSV:function(b){if(0===b.length)return!1;var c=this.tab.layers,a=[],d=[];l.forEach(b,function(b){a.push(b.attributes)});
for(var f in a[0])d.push(f);H.exportCSV(c,a,d)},_getFields:function(b){var c=[];if(this.tab.advConfig&&this.tab.advConfig.fields&&0<this.tab.advConfig.fields.length)l.forEach(this.tab.advConfig.fields,function(a){c.push(a.expression)});else{var a;a=b.infoTemplate?b.infoTemplate.info.fieldInfos:b.fields;for(var d=0;d<a.length;d++){var f=a[d];"undefined"!==typeof f.visible?f.visible&&c.push(f.fieldName):c.push(f.name)}}var e={};l.forEach(b.fields,function(a){if("esriFieldTypeDate"===a.type||a.domain)e[a.name]=
a});this.specialFields=e;return c},_getFieldValue:function(b,c){var a=c;if(this.specialFields[b]){var d=this.specialFields[b];"esriFieldTypeDate"===d.type?a=(new Date(c)).toLocaleString():l.some(d.domain.codedValues,function(b){if(b.code===c)return a=b.name,!0})}return a},_getDistance:function(b,c){var a=0;4326===b.spatialReference.wkid&&(b=w.geographicToWebMercator(b));a="point"===b.type?b:b.getExtent().getCenter();4326===c.spatialReference.wkid&&(c=w.geographicToWebMercator(c));var d="point"===
c.type?c:c.getExtent().getCenter(),f=this.parent.config.distanceUnits,e=new C(a.spatialReference);e.addPath([a,d]);a=a.spatialReference.isWebMercator()?v.geodesicLength(e,9001):v.planarLength(e,9001);switch(f){case "miles":a*=6.21371E-4;break;case "kilometers":a*=0.0010;break;case "feet":a*=3.28084;break;case "yards":a*=1.09361;break;case "nauticalMiles":a*=5.39957E-4}return a},_compareDistance:function(b,c){return b.attributes.DISTANCE<c.attributes.DISTANCE?-1:b.attributes.DISTANCE>c.attributes.DISTANCE?
1:0},_zoomToLocation:function(b){this.parent.zoomToLocation(b)},_routeToIncident:function(b){this.parent.routeToIncident(b)}})});