// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/lang dojo/dom-class dojo/dom-geometry dojo/dom-style esri/tasks/query esri/geometry/geometryEngine ./CSVUtils jimu/utils".split(" "),function(h,s,m,n,p,C,l,A,u){function B(a){return function(b,e){return b.attributes[a]<e.attributes[a]?-1:b.attributes[a]>e.attributes[a]?1:0}}return{getFields:function(a,b,e,d){var c=this.getSkipFields(a),f=[];if(!e&&b.advStat&&b.advStat.stats&&b.advStat.stats.outFields&&0<b.advStat.stats.outFields.length)h.forEach(b.advStat.stats.outFields,
function(a){f.push(a.expression)});else{if(a.infoTemplate)b=a.infoTemplate.info.fieldInfos;else if(0<d.map.itemInfo.itemData.operationalLayers.length){d=d.map.itemInfo.itemData.operationalLayers;b=null;var g=0;a:for(;g<d.length;g++){var k=d[g];if("ArcGISMapServiceLayer"===k.layerType&&"undefined"!==typeof k.layers)for(var t=0;t<k.layers.length;t++){var q=k.layers[t];if(q.id===a.layerId&&q.popupInfo){b=q.popupInfo.fieldInfos;break a}}}b||(b=a.fields)}else b=a.fields;if(b)for(d=0;d<b.length;d++)g=b[d],
!e&&"undefined"!==typeof g.visible?g.visible&&-1===c.indexOf(g.fieldName)&&f.push(g.fieldName):(g=g.name?g.name:g.fieldName,-1===c.indexOf(g)&&f.push(g))}a=this.getSpecialFields(a);return{dateFields:a.dateFields,specialFields:a.specialFields,fields:3<f.length&&!e?f.slice(0,3):f,allFields:f}},getField:function(a,b){for(var e=0;e<a.length;e++){var d=a[e];if(d.name===b||d.alias===b)return d}},getFieldValue:function(a,b,e,d,c){var f=b;e[a]&&(e=e[a],"esriFieldTypeDate"===e.type?("undefined"!==d[a]?(a=
d[a],c=void 0!==typeof a?{dateFormat:a}:{dateFormat:c}):c={dateFormat:c},f=u.fieldFormatter.getFormattedDate(new Date(b),c)):h.some(e.domain.codedValues,function(a){if(a.code===b)return f=a.name,!0}));return f},getSkipFields:function(a){var b=[];if(a.fields)for(var e=0;e<a.fields.length;e++){var d=a.fields[e];d&&d.type&&d.name&&"esriFieldTypeGeometry"===d.type&&b.push(d.name)}a.globalIdField&&""!==a.globalIdField&&b.push(a.globalIdField);a.objectIdField&&""!==a.objectIdField&&b.push(a.objectIdField);
return b},getSpecialFields:function(a){var b={},e=[];a.fields&&h.forEach(a.fields,s.hitch(this,function(d){if("esriFieldTypeDate"===d.type||d.domain){if("esriFieldTypeDate"===d.type&&a.infoTemplate)for(var c in a.infoTemplate._fieldsMap)"undefined"!==typeof a.infoTemplate._fieldsMap[c].fieldName&&(a.infoTemplate._fieldsMap[c].fieldName===d.name&&"undefined"!==typeof a.infoTemplate._fieldsMap[c].format.dateFormat)&&(e[d.name]=a.infoTemplate._fieldsMap[c].format.dateFormat);b[d.name]=d}}));return{specialFields:b,
dateFields:e}},getSummaryFields:function(){},getDisplayFields:function(a){var b;"undefined"!==typeof a.advStat&&"undefined"!==typeof a.advStat.stats&&"undefined"!==typeof a.advStat.stats.outFields?b=a.advStat.stats.outFields:(b=[],0<a.tabLayers.length&&h.forEach(a.tabLayers,s.hitch(this,function(a){"undefined"!==typeof a.popupInfo?h.forEach(a.popupInfo.fieldInfos,s.hitch(this,function(a){if(a.visible){var c={value:0};c.expression=a.fieldName;c.label=a.label;b.push(c)}})):a.infoTemplate?h.forEach(a.infoTemplate.info.fieldInfos,
s.hitch(this,function(a){if(a.visible){var c={value:0};c.expression=a.fieldName;c.label=a.label;b.push(c)}})):h.forEach((a.layerObject?a.layerObject:a).fields,s.hitch(this,function(a){var c={value:0};c.expression=a.name;c.label=a.alias;b.push(c)}))})));return b},exportToCSV:function(a,b,e,d,c){if(0===a.length)return!1;var f=c.baseLabel,g=[],k=[];"proximity"===c.type&&a.sort(this.compareDistance);var t;"undefined"===typeof b.altKey?t=b:(t=!1,e=c.csvAllFields);h.forEach(a,function(a){("proximity"===
c.type||"closest"===c.type)&&delete a.attributes.DISTANCE;g.push(a.attributes)});if("summary"===c.type||"grouped"===c.type)if(!0===c.csvAllFields||"true"===c.csvAllFields)for(var q in g[0])k.push(q);else for(a=0;a<c.summaryFields.length;a++)k.push(c.summaryFields[a].field);else for(var m in g[0])k.push(m);a=c.layer;q=a.fields;if(a&&a.loaded&&q||t){m=this.getSkipFields(a);var r={};if(c.opLayers&&c.opLayers._layerInfos){var l=c.opLayers.getLayerInfoById(a.id);l&&(r.popupInfo=l.getPopupInfo())}var l=
[],p=0;for(;p<k.length;p++){var n=k[p];if(-1===m.indexOf(n)){var u=!1,x,y=0;b:for(;y<q.length;y++)if(x=q[y],x.name===n){u=!0;break b}u?l.push(x):l.push({name:n,alias:n,show:!0,type:"esriFieldTypeString"})}}r.datas=g;r.fromClient=!1;r.withGeometry=!1;r.outFields=l;r.formatDate=!0;r.formatCodedValue=!0;r.formatNumber=!1;var v=[],w=[];if(!b&&e&&"undefined"!==typeof d)switch(c.type){case "proximity":v.push(c.nlsCount);w.push(d);break;case "closest":var z=0;h.forEach(d,s.hitch(this,function(a){0===z&&
(h.forEach(a,function(a){v.push(a.label)}),z+=1);var b=[];h.forEach(a,function(a){b.push(a.value)});w.push(b)}));break;case "summary":h.forEach(d,s.hitch(this,function(a){var b=a.info.replace("\x3cbr/\x3e",""),d=!1,e=0;a:for(;e<c.calcFields.length;e++)if(b===c.calcFields[e].alias){d=!0;break a}d&&(v.push(b),w.push(a.total))}));break;case "grouped":h.forEach(d,function(a){v.push(a.info.replace("\x3cbr/\x3e",""));w.push(a.total)})}if(t)return{summaryLayer:a,details:l};A.exportCSVFromFeatureLayer(f,
a,r);return{summaryLayer:a,details:{appendColumns:v,appendDatas:w,name:f,type:c.nlsValue}}}A.exportCSV(f,g,k)},isURL:function(a){return/(https?:\/\/|ftp:)/g.test(a)},isEmail:function(a){return/\S+@\S+\.\S+/.test(a)},queryTabCount:function(){},performQuery:function(){},getGeoms:function(a){for(var b=[],e=[],d=0;d<a.length;d++){var c=a[d].geometry?a[d].geometry:a[d];if("polygon"===c.type&&-1===b.indexOf(d)){for(var f=0;f<a.length;f++)if(f!==d&&-1===b.indexOf(f)){var g=a[f].geometry?a[f].geometry:a[f];
"polygon"===g.type?l.intersects(c,g)&&(b.push(f),c=l.union(c,g)):b.push(f)}e.push(c)}}return e},createDefArray:function(a,b){for(var e=[],d=0;d<a.length;d++){var c=a[d],f=new C;f.returnGeometry=!1;f.geometry=b;"undefined"!==typeof c.queryCount?e.push(c.queryCount(f)):"undefined"!==typeof c.queryIds?e.push(c.queryIds(f)):"undefined"!==typeof c.queryFeatures&&e.push(c.queryFeatures(f))}return e},updateTabCount:function(a,b,e,d,c){var f="undefined"!==typeof c&&0<c?!0:!1;c=n.position(b).w;"undefined"!==
typeof a&&0===a?(m.remove(b,"noFeatures"),m.remove(b,"noFeaturesActive"),m.add(b,f?"noFeaturesActive":"noFeatures")):(f&&m.contains(b,"noFeatures")&&m.remove(b,"noFeatures"),f&&m.contains(b,"noFeaturesActive")&&m.remove(b,"noFeaturesActive"));e&&(a="undefined"!==typeof a?d+" ("+u.localizeNumber(a).toString()+")":d,b.innerHTML=a);e=n.position(b).w;a=0;var g;e>c?(g=!0,a=e-c):c>e&&(g=!1,a=c-e);c=n.position(b.parentNode).w;if(0<c){g=g?c+a:c-a;p.set(b.parentNode,"width",g+"px");b=b.parentNode.parentNode;
c=b.parentNode;var k;if(c&&c.children&&0<c.children.length)for(a=0;a<c.children.length;a++)if(e=c.children[a],-1<e.className.indexOf("SA_panelRight")){k=e;break}k&&b&&(g>n.position(c).w?(p.set(b,"right","58px"),p.set(k,"display","block")):(p.set(b,"right","24px"),p.set(k,"display","none")))}},getSum:function(a,b){var e=0;h.forEach(a,function(a){e+=a.attributes[b]});return e},getMin:function(a,b){a.sort(B(b));return a[0].attributes[b]},getMax:function(a,b){a.sort(B(b));a.reverse();return a[0].attributes[b]},
getArea:function(a,b,e,d){var c=0;e=s.clone(e);e.miles=109413;e.kilometers=109414;e.feet=109405;e.meters=109404;e.yards=109442;e.nauticalMiles=109409;var f=e[d];h.forEach(a,function(a){for(var d=0;d<b.length;d++){var e=l.intersect(a.geometry,b[d]);null!==e&&(c+=l.geodesicArea(e,f))}});return c},getLength:function(a,b,e,d){var c=0,f=e[d];h.forEach(a,function(a){for(var d=0;d<b.length;d++){var e=l.intersect(a.geometry,b[d]);null!==e&&(c+=l.geodesicLength(e,f))}});return c},getDistance:function(a,b,
e){var d=0,d=l.distance(a,b,9001);switch(e){case "miles":d*=6.21371E-4;break;case "kilometers":d*=0.0010;break;case "feet":d*=3.28084;break;case "yards":d*=1.09361;break;case "nauticalMiles":d*=5.39957E-4}return d},compareDistance:function(a,b){return a.attributes.DISTANCE<b.attributes.DISTANCE?-1:a.attributes.DISTANCE>b.attributes.DISTANCE?1:0}}});