// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on jimu/utils esri/geometry/geometryEngine esri/graphic esri/Color esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query ./analysisUtils".split(" "),function(L,r,G,M,A,D,n,q,N,H,B,O,I,E,P,y,J,K,Q,R,S,t){return L("ClosestInfo",null,
{featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,constructor:function(a,b,d){this.tab=a;this.container=b;this.parent=d;this.graphicsLayer=this.incident=null;this.map=d.map;this.specialFields={};this.dateFields={};this.config=d.config;this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers},queryTabCount:function(a,b,d,e){this.incidentCount=a.length;var k=this.parent.config.distanceSettings[this.parent.config.distanceUnits],c=this.parent.config.maxDistance;
b=[];for(var l=0;l<a.length;l++)b.push(I.buffer(a[l].geometry,c,k));var f=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(f=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var h;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryFields=this._getFields(this.summaryLayer),h=new y(this.summaryLayer.url),h.infoTemplate=
this.tab.tabLayers[0].infoTemplate,f=[h],this.tab.tabLayers=f,this._performQuery(a,b,d,e,f)):this.loading||(h=new y(this.tab.tabLayers[0].url),this.loading=!0,B(h,"load",r.hitch(this,function(){this.summaryLayer=h;this.summaryFields=this._getFields(this.summaryLayer);for(var c=this.tab.tabLayers[0].url.split("MapServer/")[1],g=this.parent.map.itemInfo.itemData.operationalLayers,p=0;p<g.length;p++){var u=g[p];if("undefined"!==typeof u.layerObject&&u.layerObject.infoTemplates&&(u=u.layerObject.infoTemplates[c])){h.infoTemplate=
u.infoTemplate;break}}f=[h];this.tab.tabLayers=f;this.loading=!1;this._performQuery(a,b,d,e,f)})))}this.mapServiceLayer||this._performQuery(a,b,d,e,f)},_performQuery:function(a,b,d,e,k){var c=[],l,f;this.summaryGeoms=b;if(0<b.length)for(a=0;a<b.length;a++)c=b[a],f=t.createDefArray(k,c),l=0===a?c=f:c=l.concat(f);(new A(c)).then(r.hitch(this,function(a){for(var b=0,g=0;g<a.length;g++){var c=a[g][1];isNaN(c)?c&&c.features?0<c.features.length&&(b+=1):c&&"undefined"!==typeof c.length&&0<c.length&&(b+=
1):0<c&&(b+=1)}this.updateTabCount(b,d,e)}))},updateTabCount:function(a,b,d){this.featureCount=0===parseInt(a,10)?0:a;t.updateTabCount(this.featureCount,b,d,this.baseLabel,this.incidentCount)},updateForIncident:function(a,b,d,e,k,c){this.incidentCount=a.length;this.allFields="undefined"!==typeof k&&"undefined"!==typeof c?k?!0:c:!1;var l="undefined"!==typeof e,f;M.forEach(this.tab.tabLayers,r.hitch(this,function(c){if("undefined"!==typeof c.empty&&c.url){var k=new y(c.url);B(k,"load",r.hitch(this,
function(){this.tab.tabLayers=[k];l?(f=new D,this.processIncident(a,b,d,e).then(r.hitch(this,function(a){f.resolve(a)}),r.hitch(this,function(a){console.error(a);f.reject(a)}))):this.processIncident(a,b,d,e)}))}else l?(f=new D,this.processIncident(a,b,d,e).then(r.hitch(this,function(a){f.resolve(a)}),r.hitch(this,function(a){console.error(a);f.reject(a)}))):this.processIncident(a,b,d,e)}));if(l)return f},processIncident:function(a,b,d,e){this.incidents=a;var k,c="undefined"!==typeof e;c?k=new D:(this.container.innerHTML=
"",n.add(this.container,"loading"));var l=[];e=this.parent.config.distanceSettings[this.parent.config.distanceUnits];for(var f=[],h=0;h<a.length;h++){var q=a[h].geometry,g=I.buffer(q,b,e);f.push({geometry:q,buffer:g})}(this.graphicsLayer=d)&&this.graphicsLayer.clear();a=[];b=this.tab.tabLayers[0];var p=this._getFields(b);for(d=0;d<f.length;d++)e=new S,e.returnGeometry=!0,e.geometry=f[d].buffer,e.outFields="true"===this.parent.config.csvAllFields||!0===this.parent.config.csvAllFields?["*"]:p,"undefined"!==
typeof b.queryFeatures&&a.push(b.queryFeatures(e));(new A(a)).then(r.hitch(this,function(a){for(var b=0;b<a.length;b++)if(a[b][0]){var d=a[b][1].features,e=[],g=f[b].geometry;if(d&&0<d.length){for(var h=0;h<d.length;h++){var n=new E(d[h].toJson()),m=n.geometry,s=g;"point"!==g.type&&(s=g.getExtent().getCenter());for(var m=t.getDistance(s,m,this.parent.config.distanceUnits),s={DISTANCE:m},q=0;q<p.length;q++)s[p[q]]=n.attributes[p[q]];!0===this.config.csvAllFields||"true"===this.config.csvAllFields?
n.attributes.DISTANCE=m:n.attributes=s;e.push(n)}e.sort(t.compareDistance);l.push(e[0])}}else a[b][1]&&a[b][1].message&&console.log(a[b][1].message);l.sort(t.compareDistance);c?this._processResults(l,!0).then(r.hitch(this,function(a){k.resolve(a)})):this._processResults(l)}),r.hitch(this,function(a){console.error(a);k.reject(a)}));if(c)return k},_processResults:function(a,b){var d,e,k=a&&0<a.length;if(k&&"point"!==a[0].geometry.type)for(var c=a.length-1;0<=c;c--)"undefined"===typeof a[c].geometry.getExtent()&&
a.splice(c,1);b?d=new D:(this.container.innerHTML="",n.remove(this.container,"loading"),k&&(e=q.create("div",{"class":"SAT_tabPanelContent"},this.container),c=q.create("div",{},e),n.add(c,"SATcolExport"),n.add(c,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder"),c=q.create("div",{title:this.parent.nls.downloadCSV},c),n.add(c,"btnExport"),B(c,"click",r.hitch(this,this._exportToCSV,a))));var c=this.parent.nls[this.parent.config.distanceUnits],l=[],f=220;if(k)for(var h=0;h<a.length;h++){var C=
h+1,g=a[h],p=g.geometry,u=p;"point"!==p.type&&(u=p.getExtent().getCenter());var p=g.attributes,y;"point"===this.incidents[0].geometry.type&&(y=Math.round(100*p.DISTANCE)/100+" "+c+" ("+this.parent.nls.approximate+")");var w="",v=0,x=[],z;for(z in p)if("DISTANCE"!==z&&3>v&&"undefined"!==typeof this.displayFields)for(var F=0;F<this.displayFields.length;F++)if(this.displayFields[F].expression===z){var m=t.getFieldValue(z,p[z],this.specialFields,this.dateFields,"longMonthDayYear"),m="undefined"!==typeof m&&
null!==m?O.stripHTML(m.toString()):"",s;if(g._layer&&g._layer.fields){var A=t.getField(g._layer.fields,z);A&&(s=A.alias)}if("undefined"===typeof s||s in[""," ",null,void 0])s=z;t.isURL(m)?m='\x3ca href\x3d"'+m+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+s+"\x3c/a\x3e":t.isEmail(m)&&(m='\x3ca href\x3d"mailto:'+m+'" style\x3d"color: inherit;"\x3e'+s+"\x3c/a\x3e");w+=m+"\x3cbr/\x3e";v+=1;x.push({value:-1<m.indexOf(",")?m.replace(",",""):m,label:s})}l.push(x);b||(g=q.create("div",{},e),n.add(g,
"SATcolRec"),n.add(g,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder"),v=q.create("div",{},g),n.add(v,"SATcolRecBar"),x=q.create("div",{innerHTML:C},v),n.add(x,"SATcolRecNum"),H.set(x,"backgroundColor",this.parent.config.activeColor),B(x,"click",r.hitch(this,this._zoomToLocation,u)),y&&(x=q.create("div",{innerHTML:y},v),n.add(x,"SATcolDistance")),this.parent.config.enableRouting&&(v=q.create("div",{title:this.parent.nls.get_directions},v),n.add(v,"SATcolDir"),B(v,"click",r.hitch(this,this._routeToIncident,
u))),w=q.create("div",{"class":"SATcolWrap",innerHTML:w},g),n.add(w,"SATcolInfo"),f+=N.position(g).w,w=new K(K.STYLE_SOLID,new G.fromRgb(this.parent.config.activeMapGraphicColor),1),w=new J(J.STYLE_CIRCLE,24,w,new G.fromRgb(this.parent.config.activeMapGraphicColor)),g=new Q,g.family="Arial",g.size="12px",C=new R(C,g,new P(this.parent.config.fontColor)),C.setOffset(0,-4),this.graphicsLayer.add(new E(u,w,p)),this.graphicsLayer.add(new E(u,C,p)))}if(!b&&k)H.set(e,"width",f);else if(k)return d.resolve({graphics:a,
analysisResults:l,context:this}),d},_exportToCSV:function(a,b,d,e){a=t.exportToCSV(a,b,d,e,{type:"closest",baseLabel:this.baseLabel,csvAllFields:this.parent.config.csvAllFields,layer:this.tab.tabLayers[0],opLayers:this.parent.opLayers,nlsValue:this.parent.nls.closest,nlsCount:this.parent.nls.count});this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){a=t.getFields(a,this.tab,this.allFields,this.parent);this.dateFields=a.dateFields;this.specialFields=a.specialFields;this.displayFields=
t.getDisplayFields(this.tab);return a.fields},_zoomToLocation:function(a){this.parent.zoomToLocation(a)},_routeToIncident:function(a){this.parent.routeToIncident(a)}})});