// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/lang esri/tasks/QueryTask esri/tasks/query".split(" "),function(f,s,m,v,t,r,n,x,y,z){function w(b){var c=s.clone(b.attributes);if((b=b.geometry)&&"point"===b.type)"x"in c?c._x=b.x:c.x=b.x,"y"in c?c._y=b.y:c.y=b.y;return c}f.exportCSV=function(b,c,a,d,l){return f._createCSVStr(c,a,d,l).then(function(a){return f._download(b+".csv",a)})};f.exportCalculatedResultsCSV=function(b,c){var a="",d=0;m.forEach(c,
function(l){a+=l.name+" ("+l.type+")\r\n";f._createCSVStr([],[],l.appendColumns,l.appendDatas).then(function(e){a+=e;d++;if(d===c.length)return f._download(b+".csv",a);a+="\r\n\r\n"})})};f.exportCSVFromFeatureLayer=function(b,c,a){a=a||{};return f._getExportData(c,{datas:a.datas,fromClient:a.fromClient,withGeometry:a.withGeometry,outFields:a.outFields,filterExpression:a.filterExpression}).then(function(d){return f._formattedData(c,d,{formatNumber:a.formatNumber,formatDate:a.formatDate,formatCodedValue:a.formatCodedValue,
popupInfo:a.popupInfo,appendColumns:a.appendColumns,appendDatas:a.appendDatas}).then(function(a){return f.exportCSV(b,a.datas,a.columns,a.appendColumns,a.appendDatas)})})};f.exportCSVByAttributes=function(b,c,a,d){d=s.mixin({},d);d.datas=a;return f.exportCSVFromFeatureLayer(b,c,d)};f.exportCSVByGraphics=function(b,c,a,d){a=m.map(a,function(a){return a.attributes});return f.exportCSVByAttributes(b,c,a,d)};f._createCSVStr=function(b,c,a,d){var f=new r,e="",g=0,q=0,h="",k="";try{if(c&&0<c.length){m.forEach(c,
function(a){e=e+h+a;h=","});for(var e=e+"\r\n",g=b.length,q=c.length,p=0;p<g;p++){for(var h="",u=0;u<q;u++)k=b[p][c[u]],!k&&"number"!==typeof k&&(k=""),k&&/[",\r\n]/g.test(k)&&(k='"'+k.replace(/(")/g,'""')+'"'),e=e+h+k,h=",";e+="\r\n"}}"undefined"!==typeof a&&"undefined"!==typeof d&&(0<a.length&&0<d.length)&&(h="",m.forEach(a,function(a){e=e+h+a;h=","}),h="",e+="\r\n",m.forEach(d,function(a){Array.isArray(a)?(m.forEach(a,function(a){e=e+h+a;h=","}),h="",e+="\r\n"):(e=e+h+a,h=",")}));f.resolve(e)}catch(n){console.error(n),
f.resolve("")}return f};f._isIE11=function(){return 11===n.has("ie")};f._isEdge=function(){return n.has("edge")};f._getDownloadUrl=function(b){return window.Blob&&window.URL&&window.URL.createObjectURL?(b=new Blob(["\ufeff"+b],{type:"text/csv"}),URL.createObjectURL(b)):"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(b)};f._download=function(b,c){var a=new r;try{if(t("ie")&&10>t("ie")){var d=window.top.open("about:blank","_blank");d.document.write("sep\x3d,\r\n"+c);d.document.close();
d.document.execCommand("SaveAs",!0,b);d.close()}else if(10===t("ie")||f._isIE11()||f._isEdge()){var l=new Blob(["\ufeff"+c],{type:"text/csv"});navigator.msSaveBlob(l,b)}else{var e=v.create("a",{href:f._getDownloadUrl(c),target:"_blank",download:b},document.body);if(t("safari")){var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);e.dispatchEvent(g)}else e.click();v.destroy(e)}a.resolve()}catch(q){a.reject(q)}return a};f._getExportData=function(b,c){var a=new r,d=null,l=c.datas,e=c.withGeometry,
d=c.outFields;if(!d||!d.length)d=b.fields;d=s.clone(d);if(e&&!(l&&0<l.length)){var g="",g=-1!==d.indexOf("x")?"_x":"x";d.push({name:g,alias:g,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});g=-1!==d.indexOf("y")?"_y":"y";d.push({name:g,alias:g,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"})}l&&0<l.length?a.resolve({data:l||[],outFields:d}):c.fromClient?(l=m.map(b.graphics,function(a){return e?w(a):s.clone(a)}),a.resolve({data:l||[],outFields:d})):
f._getExportDataFromServer(b,d,c).then(function(b){a.resolve({data:b||[],outFields:d})});return a};f._getExportDataFromServer=function(b,c,a){var d=new r;if("esri.layers.FeatureLayer"!==b.declaredClass)return d.resolve([]),d;var f=new y(b.url),e=new z;e.where=a.filterExpression||b.getDefinitionExpression&&b.getDefinitionExpression()||"1\x3d1";0<c.length?(b=m.map(c,function(a){return a.name}),e.outFields=b):e.outFields=["*"];e.returnGeometry=a.withGeometry;f.execute(e,function(a){a=m.map(a.features,
function(a){return w(a)});d.resolve(a)},function(a){console.error(a);d.resolve([])});return d};f._formattedData=function(b,c,a){var d=new r,l=[],e=c.data;c=c.outFields;for(var g=0,n=e.length;g<n;g++){for(var h={},k=0;k<c.length;k++){var p=c[k];h[p.alias||p.name]=f._getExportValue(e[g][p.name],p,b.objectIdField,b.typeIdField,e[g][b.typeIdField],b.types,a)}l.push(h)}b=m.map(c,function(a){return a.alias||a.name});d.resolve({datas:l,columns:b,appendColumns:a.appendColumns,appendDatas:a.appendDatas});
return d};f._getExportValue=function(b,c,a,d,f,e,g){function q(a){if(h&&x.isDefined(h.fieldInfos))for(var b=0,c=h.fieldInfos.length;b<c;b++){var d=h.fieldInfos[b];if(d.fieldName===a)return d.format}return null}var h=g.popupInfo,k=!!c.domain&&g.formatCodedValue;g="esriFieldTypeDate"===c.type&&g.formatDate;var p=a&&c.name===a;d=d&&c.name===d;return g?n.fieldFormatter.getFormattedDate(b,q(c.name)):d?n.fieldFormatter.getTypeName(b,e):k?n.fieldFormatter.getCodedValue(c.domain,b):!k&&!g&&!p&&!d?(k=null,
a&&e&&0<e.length&&(a=(a=m.filter(e,function(a){return a.id===f}))&&a[0])&&(a.domains&&a.domains[c.name]&&a.domains[c.name].codedValues)&&(k=n.fieldFormatter.getCodedValue(a.domains[c.name],b)),null!==k?k:b):b}});