// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/DeferredList dojo/Deferred dojo/_base/lang dojo/_base/Color dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/number dojo/on dojo/has dijit/form/Button jimu/dijit/Popup jimu/utils jimu/dijit/Message esri/config esri/geometry/geometryEngine esri/geometry/mathUtils esri/geometry/Point esri/geometry/webMercatorUtils esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query ./analysisUtils".split(" "),
function(A,B,u,v,t,m,D,E,q,r,F,G,C,w,H,I,J,x,y,K,L,M,N,O,P,s,Q,R,S,T,z,n){return A("GroupedCountInfo",[B],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],tabNum:null,popupFields:[],groupedResults:{},specialFields:null,dateFields:{},symbolField:null,graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,featureCount:0,incidentCount:0,displayCount:!1,allFields:!1,constructor:function(a,b,d){this.tab=a;this.container=b;this.parent=d;this.config=d.config;this.graphicsLayer=null;this.specialFields=
{};this.dateFields={};this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers},queryTabCount:function(a,b,d,g){this.displayCount=g;this.incidentCount=a.length;var f=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(f=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var c;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],
this.summaryFields=this._getFields(this.summaryLayer),c=new s(this.summaryLayer.url),c.infoTemplate=this.tab.tabLayers[0].infoTemplate,f=[c],this.tab.tabLayers=f,this._performQuery(a,b,d,g,f)):this.loading||(c=new s(this.tab.tabLayers[0].url),this.loading=!0,w(c,"load",m.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);for(var h=this.tab.tabLayers[0].url.split("MapServer/")[1],e=this.parent.map.itemInfo.itemData.operationalLayers,k=0;k<e.length;k++){var l=
e[k];if("undefined"!==typeof l.layerObject&&l.layerObject.infoTemplates&&(l=l.layerObject.infoTemplates[h])){c.infoTemplate=l.infoTemplate;break}}f=[c];this.tab.tabLayers=f;this.loading=!1;this._performQuery(a,b,d,g,f)})))}this.mapServiceLayer||this._performQuery(a,b,d,g,f)},_performQuery:function(a,b,d,g,f){var c=[],h,e;0<b.length?e=n.getGeoms(b):0<a.length&&(e=n.getGeoms(a));this.summaryGeoms=e;if(0<e.length)for(a=0;a<e.length;a++)c=e[a],b=n.createDefArray(f,c),h=0===a?c=b:c=h.concat(b);(new v(c)).then(m.hitch(this,
function(a){for(var b=0,c=0;c<a.length;c++){var e=a[c][1];isNaN(e)?e&&e.features?b+=e.features.length:e&&"undefined"!==typeof e.length&&(b+=e.length):b+=e}this.updateTabCount(b,d,g);this.queryOnLoad&&m.hitch(this,this._queryFeatures(this.summaryGeoms))}))},updateTabCount:function(a,b,d){this.displayCount=d;this.featureCount=a;n.updateTabCount(this.featureCount,b,d,this.baseLabel,this.incidentCount)},updateForIncident:function(a,b,d,g,f,c,h){this.incidentCount=a.length;this.allFields="undefined"!==
typeof c&&"undefined"!==typeof h?c?!0:h:!1;var e="undefined"!==typeof f,k;this.tabNum=g;e?k=new t:(this.container.innerHTML="",q.add(this.container,"loading"));this.summaryIds=[];this.summaryFeatures=[];this.groupedResults={};if(0<this.tab.tabLayers.length){var l=[];if(0<b.length)l=b;else for(b=0;b<a.length;b++)g=a[b].geometry?a[b].geometry:a[b],"polygon"===g.type&&l.push(g);var p;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],p=new s(this.summaryLayer.url),
p.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers[1]=p,this.summaryFields=this._getFields(this.tab.tabLayers[0]),e?this._queryFeatures(l,e).then(function(a){k.resolve(a)}):(this._initGraphicsLayer(d),m.hitch(this,this._queryFeatures(l,e)))):(p=new s(this.tab.tabLayers[0].url),w(p,"load",m.hitch(this,function(){this.summaryLayer=p;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=this.tab.tabLayers[0].url.split("MapServer/")[1],b=this.parent.map.itemInfo.itemData.operationalLayers,
c=0;c<b.length;c++){var h=b[c];if("undefined"!==typeof h.layerObject&&h.layerObject.infoTemplates&&(h=h.layerObject.infoTemplates[a])){p.infoTemplate=h.infoTemplate;break}}this.tab.tabLayers[1]=p;this.summaryFields=this._getFields(this.tab.tabLayers[1]);e?this._queryFeatures(l,e).then(function(a){k.resolve(a)}):(this._initGraphicsLayer(d),m.hitch(this,this._queryFeatures(l)))})));if(e)return k}},_initGraphicsLayer:function(a){null!==a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&
(this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol),null===this.specialFields&&n.getSpecialFields(this.summaryLayer)))},_queryFeatures:function(a,b){var d;b&&(d=new t);for(var g=[],f=new z,c=0;c<a.length;c++)f.geometry=a[c],g.push(this.summaryLayer.queryIds(f));(new v(g)).then(m.hitch(this,
function(a){for(var c,g,f=0;f<a.length;f++)a[f][0]&&(c=a[f][1],g=c=0===f?c:g.concat(c));c?(this.summaryIds=c,0<this.summaryIds.length?b?this._queryFeaturesByIds(b).then(function(a){d.resolve(a)}):this._queryFeaturesByIds():b||this._processResults()):b||this._processResults()}),m.hitch(this,function(a){console.error(a);new y({message:a})}));if(b)return d},_queryFeaturesByIds:function(a){var b,d=[];a&&(b=new t);var g=this.summaryLayer.maxRecordCount||1E3,f=this.summaryIds.slice(0,g);this.summaryIds.splice(0,
g);var c=new z,h=!1;u.some(this.summaryFields,m.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return h=!0}));a&&(h=!0);c.returnGeometry=h;var e=[];u.forEach(this.summaryFields,function(a){e.push(a.field)});this.symbolField&&e.push(this.symbolField);if(!0===this.config.csvAllFields||"true"===this.config.csvAllFields)c.outFields=["*"];else{if(0<this.popupFields.length)for(var k=0;k<this.popupFields.length;k++){var l=this.popupFields[k];-1===e.indexOf(l)&&e.push(l)}c.outFields=
e}c.objectIds=f;for(d.push(this.summaryLayer.queryFeatures(c));0<this.summaryIds.length;)f=this.summaryIds.slice(0,g),this.summaryIds.splice(0,g),c.objectIds=f,d.push(this.summaryLayer.queryFeatures(c));(new v(d)).then(m.hitch(this,function(c){for(var d=0;d<c.length;d++)if(c[d][0]){var e=c[d][1];e.features&&(this.summaryFeatures=this.summaryFeatures.concat(e.features))}a?this._processResults(a).then(m.hitch(this,function(a){this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing");
b.resolve(a)})):(this._processResults(),this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing"));this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing")}),m.hitch(this,function(a){console.error(a);new y({message:a})}));if(a)return b},_prepGroupedResults:function(){for(var a=0;a<this.summaryFeatures.length;a++){var b=this.summaryFeatures[a];if("undefined"!==typeof this.summaryFields&&0<this.summaryFields.length){var d=n.getFieldValue(this.summaryFields[0].field,
b.attributes[this.summaryFields[0].field],this.specialFields,this.dateFields,"longMonthDayYear"),d="undefined"!==typeof d&&null!==d?x.stripHTML(d.toString()):"";d in this.groupedResults?this.groupedResults[d].features.push(b):this.groupedResults[d]={features:[b]}}}},_prepResults:function(){for(var a in this.groupedResults){var b=this.summaryFields[0];b.total=this.groupedResults[a].features.length;this.groupedResults[a].total=b.total;this.groupedResults[a].type=b.type;this.groupedResults[a].label=
b.alias}},_processResults:function(a){this._prepGroupedResults();this._prepResults();var b=this.groupedResults,d=0,g,f;if(a)f=new t;else{this.container.innerHTML="";q.remove(this.container,"loading");if(0===Object.keys(this.groupedResults).length){this.container.innerHTML=this.parent.nls.noFeaturesFound;return}var c=Object.keys(this.groupedResults).length+1;g=r.create("div",{style:"width:"+220*c+"px;"},this.container);q.add(g,"SAT_tabPanelContent");c=r.create("div",{},g);q.add(c,"SATcolExport");q.add(c,
this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");c=r.create("div",{"data-dojo-attach-point":"SA_SAT_download",title:this.parent.nls.downloadCSV},c);q.add(c,[this.parent.isBlackTheme?"btnExportBlack":"btnExport","download"]);w(c,"click",m.hitch(this,this._exportToCSV,b))}var h=Object.keys(b).sort(),c=[];this.displayCount&&c.push({total:this.featureCount,a:void 0,info:this.parent.nls.count,c:void 0});for(var e in h){var d=h[e],k=b[d],l=x.stripHTML(d.toString()),d=d===this.parent.nls.area||
d===this.parent.nls.length?k.total:Math.round(k.total);isNaN(d)&&(d=0);var d=C.format(d),p="pre"===k.type?k.label.trim():l,l="pre"===k.type?l:k.label.trim(),k=""!==k.label?"colGroupedSummary":"colSummary";if(a)c.push({total:d,a:p,info:""===l?p:l,c:k});else{var n=r.create("div",{"class":"SATcol"},g);q.add(n,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var s=r.create("div",{style:"max-height: 45px;"},n);r.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",
innerHTML:p},s);r.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:l},s);r.create("div",{"class":k,innerHTML:d},n)}}b=[];e=null!==this.graphicsLayer;!a&&e&&(this.graphicsLayer.clear(),this.tab.tabLayers[1].clear());if(this.summaryFeatures)for(g=0;g<this.summaryFeatures.length;g++)h=this.summaryFeatures[g],this.lyrSymbol?h.symbol=this.lyrSymbol:this.graphicsLayer?this.graphicsLayer.renderer&&(d=this.graphicsLayer.renderer.getSymbol(h),h.symbol=d):this.summaryLayer.renderer&&
this.summaryLayer.renderer.getSymbol&&(h.symbol=this.summaryLayer.renderer.getSymbol(h)),!a&&e?(this.graphicsLayer.add(h),this.tab.tabLayers[1].add(h)):b.push(h);!a&&e&&(this.graphicsLayer.setVisibility(!0),this.parent._toggleTabLayersNew(this.tabNum),this.tab.retsore&&this.emit("summary-complete",{bubbles:!0,cancelable:!0,tab:this.tabNum}));if(a)return f.resolve({graphics:b,analysisResults:c,context:this}),f},_exportToCSV:function(a,b,d,g){a=n.exportToCSV(this.summaryFeatures,b,d,g,{type:"grouped",
baseLabel:this.baseLabel,csvAllFields:this.parent.config.csvAllFields,layer:this.summaryLayer,opLayers:this.parent.opLayers,nlsValue:this.parent.nls.groupedSummary,nlsCount:this.parent.nls.count,summaryFields:this.summaryFields});this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){var b=n.getSkipFields(a),d,g=[];if("undefined"!==typeof this.tab.advStat){var f=this.tab.advStat.stats,c;for(c in f)0<f[c].length&&u.forEach(f[c],function(a){var b={field:a.expression,alias:a.label+
"",type:c,total:0};d=a.expression;g.push(b)})}f=n.getSpecialFields(a);this.dateFields=f.dateFields;this.specialFields=f.specialFields;if(this.allFields)for(f=0;f<a.fields.length;f++){var h=a.fields[f];-1===b.indexOf(h.name)&&d!==h.name&&g.push({field:h.name,alias:h.alias,type:h.type})}return g}})});