// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on esri/graphic esri/Color esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query esri/geometry/geometryEngine jimu/utils ./analysisUtils".split(" "),function(J,l,D,A,E,y,s,q,K,F,B,G,L,C,H,I,M,N,O,v,P,r){return J("ProximityInfo",
null,{featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,constructor:function(a,c,h){this.tab=a;this.container=c;this.parent=h;this.graphicsLayer=this.incident=null;this.specialFields={};this.dateFields={};this.config=h.config;this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers},queryTabCount:function(a,c,h,g){this.incidentCount=a.length;var d=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(d=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&
this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var b;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryFields=this._getFields(this.summaryLayer),b=new C(this.summaryLayer.url),b.infoTemplate=this.tab.tabLayers[0].infoTemplate,d=[b],this.tab.tabLayers=d,this._performQuery(a,c,h,g,d)):this.loading||(b=new C(this.tab.tabLayers[0].url),this.loading=!0,B(b,"load",l.hitch(this,function(){this.summaryLayer=
b;this.summaryFields=this._getFields(this.summaryLayer);for(var d=this.tab.tabLayers[0].url.split("MapServer/")[1],e=this.parent.map.itemInfo.itemData.operationalLayers,k=0;k<e.length;k++){var m=e[k];if("undefined"!==typeof m.layerObject&&m.layerObject.infoTemplates&&(m=m.layerObject.infoTemplates[d])){b.infoTemplate=m.infoTemplate;break}}this.tab.tabLayers=[b];this.loading=!1;this._performQuery(a,c,h,g,this.tab.tabLayers)})))}this.mapServiceLayer||this._performQuery(a,c,h,g,d)},_performQuery:function(a,
c,h,g,d){var b=[],f,e;0<c.length?e=r.getGeoms(c):0<a.length&&(e=r.getGeoms(a));this.summaryGeoms=e;if(0<e.length)for(a=0;a<e.length;a++)b=e[a],c=r.createDefArray(d,b),f=0===a?b=c:b=f.concat(c);(new E(b)).then(l.hitch(this,function(a){for(var b=0,d=0;d<a.length;d++){var c=a[d][1];isNaN(c)?c&&c.features?b+=c.features.length:c&&"undefined"!==typeof c.length&&(b+=c.length):b+=c}this.updateTabCount(b,h,g)}))},updateTabCount:function(a,c,h){this.featureCount=a;r.updateTabCount(this.featureCount,c,h,this.baseLabel,
this.incidentCount)},updateForIncident:function(a,c,h,g,d,b){this.incidentCount=a.length;this.allFields="undefined"!==typeof d&&"undefined"!==typeof b?d?!0:b:!1;var f="undefined"!==typeof g,e;A.forEach(this.tab.tabLayers,l.hitch(this,function(b){if("undefined"!==typeof b.empty&&b.url){var d=new C(b.url);B(d,"load",l.hitch(this,function(){this.tab.tabLayers=[d];f?(e=new y,this.processIncident(a,c,h,g).then(l.hitch(this,function(a){e.resolve(a)}),l.hitch(this,function(a){console.error(a);e.reject(a)}))):
this.processIncident(a,c,h,g)}))}else f?(e=new y,this.processIncident(a,c,h,g).then(l.hitch(this,function(a){e.resolve(a)}),l.hitch(this,function(a){console.error(a);e.reject(a)}))):this.processIncident(a,c,h,g)}));if(f)return e},processIncident:function(a,c,h,g){this.incidents=a;var d=[],b;if(0===c.length)for(var f=0;f<a.length;f++)b=a[f],b=b.geometry?b.geometry:b,"polygon"===b.type?(c.push(b),d.push({geometry:b,buffer:b})):d.push({geometry:void 0,buffer:void 0});else for(f=0;f<a.length;f++){b=a[f];
var e=c[f].geometry?c[f].geometry:c[f];b=b.geometry?b.geometry:b;d.push({geometry:b,buffer:e})}if(0!==c.length){for(a=0;a<d.length;a++)if(c=d[a].buffer,"undefined"!==typeof c)for(b=0;b<d.length;b++)if(b!==a&&(f=d[b].buffer,"undefined"!==typeof f&&v.overlaps(c,f))){d[a].buffer=v.difference(c,f);d[b].buffer=v.difference(f,c);f=v.union(f,c);f=v.difference(f,d[a].buffer);f=v.difference(f,d[b].buffer);if(Array.isArray(d[a].geometry)){if(Array.isArray(d[b].geometry))for(e=0;e<d[b].geometry.length;e++)d[a].geometry.push(d[b].geometry[e]);
else d[a].geometry.push(d[b].geometry);e=d[a].geometry}else if(e=[],e.push(d[a].geometry),Array.isArray(d[b].geometry))for(var k=0;k<d[b].geometry.length;k++)e.push(d[b].geometry[k]);else e.push(d[b].geometry);d.push({geometry:e,buffer:f})}var m,q="undefined"!==typeof g;q?m=new y:(this.container.innerHTML="",s.add(this.container,"loading"));var p=[];this.graphicsLayer=h;h=this.tab.tabLayers[0];var n=this._getFields(h);g=[];for(a=0;a<d.length;a++)c=new O,c.returnGeometry=!0,c.geometry=d[a].buffer,
c.outFields="true"===this.parent.config.csvAllFields||!0===this.parent.config.csvAllFields?["*"]:n,"undefined"!==typeof h.queryFeatures&&g.push(h.queryFeatures(c));(new E(g)).then(l.hitch(this,function(a){for(var b=0;b<a.length;b++){var c=a[b][1];if(c&&c.features)for(var c=c.features,e=d[b].geometry,f=0;f<c.length;f++){var g=c[f],h=g.geometry,t;if(Array.isArray(e)){var l;for(t=0;t<e.length;t++){var k=e[t];"point"!==k.type&&(k=e[t].getExtent().getCenter());k=r.getDistance(k,h,this.parent.config.distanceUnits);
if("undefined"===typeof l||k<l)l=k}t=l;h={DISTANCE:l}}else t=e,"point"!==e.type&&(t=e.getExtent().getCenter()),t=r.getDistance(t,h,this.parent.config.distanceUnits),h={DISTANCE:t};for(k=0;k<n.length;k++)h[n[k]]=g.attributes[n[k]];!0===this.config.csvAllFields||"true"===this.config.csvAllFields?g.attributes.DISTANCE=t:g.attributes=h;p.push(g)}}p.sort(r.compareDistance);q?m.resolve({graphics:p,analysisResults:p.length,context:this}):this._processResults(p)}),l.hitch(this,function(a){console.error(a);
m.reject(a)}));if(q)return m}},_processResults:function(a){this.container.innerHTML="";s.remove(this.container,"loading");this.graphicsLayer.clear();if("point"!==a[0].geometry.type)for(var c=a.length-1;0<=c;c--)"undefined"===typeof a[c].geometry.getExtent()&&a.splice(c,1);var c=q.create("div",{"class":"SAT_tabPanelContent"},this.container),h=this.parent.nls[this.parent.config.distanceUnits],g=q.create("div",{},c);s.add(g,"SATcolExport");s.add(g,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");
g=q.create("div",{title:this.parent.nls.downloadCSV},g);s.add(g,"btnExport");B(g,"click",l.hitch(this,this._exportToCSV,a));var d;"undefined"!==typeof this.tab.advStat&&"undefined"!==typeof this.tab.advStat.stats&&"undefined"!==typeof this.tab.advStat.stats.outFields?d=this.tab.advStat.stats.outFields:(d=[],0<this.tab.tabLayers.length&&A.forEach(this.tab.tabLayers,l.hitch(this,function(a){"undefined"!==typeof a.popupInfo?A.forEach(a.popupInfo.fieldInfos,l.hitch(this,function(a){if(a.visible){var b=
{value:0};b.expression=a.fieldName;b.label=a.label;d.push(b)}})):a.infoTemplate?A.forEach(a.infoTemplate.info.fieldInfos,l.hitch(this,function(a){if(a.visible){var b={value:0};b.expression=a.fieldName;b.label=a.label;d.push(b)}})):A.forEach((a.layerObject?a.layerObject:a).fields,l.hitch(this,function(a){var b={value:0};b.expression=a.name;b.label=a.alias;d.push(b)}))})));for(var g=220,b=0;b<a.length;b++){var f=b+1,e=a[b],k=e.geometry,m=k;"point"!==k.type&&(m=k.getExtent().getCenter());var k=e.attributes,
v;"point"===this.incidents[0].geometry.type&&(v=Math.round(100*k.DISTANCE)/100+" "+h+" ("+this.parent.nls.approximate+")");var p="",n=0,x;for(x in k)if("DISTANCE"!==x&&3>n&&"undefined"!==typeof d)for(var w=0;w<d.length;w++)if(d[w].expression===x){var u=r.getFieldValue(x,k[x],this.specialFields,this.dateFields,"longMonthDayYear"),u="undefined"!==typeof u&&null!==u?P.stripHTML(u.toString()):"",z;if(e._layer&&e._layer.fields){var y=r.getField(e._layer.fields,x);y&&(z=y.alias)}if("undefined"===typeof z||
z in[""," ",null,void 0])z=x;r.isURL(u)?u='\x3ca href\x3d"'+u+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+z+"\x3c/a\x3e":r.isEmail(u)&&(u='\x3ca href\x3d"mailto:'+u+'" style\x3d"color: inherit;"\x3e'+z+"\x3c/a\x3e");p+=u+"\x3cbr/\x3e";n+=1}e=q.create("div",{},c);s.add(e,"SATcolRec");s.add(e,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");n=q.create("div",{},e);s.add(n,"SATcolRecBar");w=q.create("div",{innerHTML:f},n);s.add(w,"SATcolRecNum");F.set(w,"backgroundColor",this.parent.config.activeColor);
B(w,"click",l.hitch(this,this._zoomToLocation,m));v&&(w=q.create("div",{innerHTML:v},n),s.add(w,"SATcolDistance"));this.parent.config.enableRouting&&(n=q.create("div",{title:this.parent.nls.get_directions},n),s.add(n,"SATcolDir"),B(n,"click",l.hitch(this,this._routeToIncident,m)));p=q.create("div",{"class":"SATcolWrap",innerHTML:p},e);s.add(p,"SATcolInfo");g+=K.position(e).w;p=new I(I.STYLE_SOLID,new D.fromString(this.parent.config.activeMapGraphicColor),1);p=new H(H.STYLE_CIRCLE,24,p,new D.fromString(this.parent.config.activeMapGraphicColor));
e=new M;e.family="Arial";e.size="12px";f=new N(f,e,new L(this.parent.config.fontColor));f.setOffset(0,-4);this.graphicsLayer.add(new G(m,p,k));this.graphicsLayer.add(new G(m,f,k))}F.set(c,"width",g+"px")},_exportToCSV:function(a,c,h,g){a=r.exportToCSV(a,c,h,g,{type:"proximity",baseLabel:this.baseLabel,csvAllFields:this.parent.config.csvAllFields,layer:this.tab.tabLayers[0],opLayers:this.parent.opLayers,nlsValue:this.parent.nls.proximity,nlsCount:this.parent.nls.count});this.summaryLayer=a.summaryLayer;
return a.details},_getFields:function(a){a=r.getFields(a,this.tab,this.allFields,this.parent);this.dateFields=a.dateFields;this.specialFields=a.specialFields;return a.fields},_zoomToLocation:function(a){this.parent.zoomToLocation(a)},_routeToIncident:function(a){this.parent.routeToIncident(a)}})});