// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/DeferredList dojo/Deferred dojo/_base/lang dojo/_base/Color dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/number dojo/on dojo/has dijit/form/Button jimu/dijit/Popup jimu/utils jimu/dijit/Message esri/config esri/geometry/geometryEngine esri/geometry/mathUtils esri/geometry/Point esri/geometry/webMercatorUtils esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query ./analysisUtils".split(" "),
function(z,A,u,v,s,m,D,E,p,r,F,G,B,w,H,I,J,C,x,K,L,M,N,O,P,t,Q,R,S,T,y,n){return z("SummaryInfo",[A],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],tabNum:null,symbolField:null,graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,allFields:!1,constructor:function(a,g,e){this.tab=a;this.container=g;this.parent=e;this.config=e.config;this.graphicsLayer=null;this.baseLabel=""!==a.label?a.label:a.layerTitle?
a.layerTitle:a.layers},queryTabCount:function(a,g,e,c){this.incidentCount=a.length;var h=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(h=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var b;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryFields=this._getFields(this.summaryLayer),b=new t(this.summaryLayer.url),
b.infoTemplate=this.tab.tabLayers[0].infoTemplate,h=[b],this.tab.tabLayers=h,this._performQuery(a,g,e,c,h)):this.loading||(b=new t(this.tab.tabLayers[0].url),this.loading=!0,w(b,"load",m.hitch(this,function(){this.summaryLayer=b;this.summaryFields=this._getFields(this.summaryLayer);for(var d=this.tab.tabLayers[0].url.split("MapServer/")[1],f=this.parent.map.itemInfo.itemData.operationalLayers,l=0;l<f.length;l++){var k=f[l];if("undefined"!==typeof k.layerObject)if(k.layerObject.infoTemplates){if(k=
k.layerObject.infoTemplates[d]){b.infoTemplate=k.infoTemplate;break}}else if(k.layerObject.infoTemplate){b.infoTemplate=k.layerObject.infoTemplate;break}}h=[b];this.tab.tabLayers=h;this.loading=!1;this._performQuery(a,g,e,c,h)})))}this.mapServiceLayer||this._performQuery(a,g,e,c,h)},_performQuery:function(a,g,e,c,h){var b=[],d,f;0<g.length?f=n.getGeoms(g):0<a.length&&(f=n.getGeoms(a));this.summaryGeoms=f;if(0<f.length)for(a=0;a<f.length;a++)b=f[a],g=n.createDefArray(h,b),d=0===a?b=g:b=d.concat(g);
(new v(b)).then(m.hitch(this,function(a){for(var b=0,f=0;f<a.length;f++){var d=a[f][1];isNaN(d)?d&&d.features?b+=d.features.length:d&&"undefined"!==typeof d.length&&(b+=d.length):b+=d}this.updateTabCount(b,e,c);this.queryOnLoad&&m.hitch(this,this._queryFeatures(this.summaryGeoms))}))},updateTabCount:function(a,g,e){this.featureCount=a;n.updateTabCount(this.featureCount,g,e,this.baseLabel,this.incidentCount)},updateForIncident:function(a,g,e,c,h,b,d){this.incidentCount=a.length;this.allFields="undefined"!==
typeof b&&"undefined"!==typeof d?b?!0:d:!1;var f="undefined"!==typeof h,l;this.tabNum=c;f?l=new s:(this.container.innerHTML="",p.add(this.container,"loading"));this.summaryIds=[];this.summaryFeatures=[];if(0<this.tab.tabLayers.length){var k=this.summaryGeoms,q;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],q=new t(this.summaryLayer.url),q.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers[1]=q,this.summaryFields=this._getFields(this.tab.tabLayers[0]),
f?this._queryFeatures(k,f).then(function(a){l.resolve(a)}):(this._initGraphicsLayer(e),m.hitch(this,this._queryFeatures(k)))):(q=new t(this.tab.tabLayers[0].url),w(q,"load",m.hitch(this,function(){this.summaryLayer=q;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=this.tab.tabLayers[0].url.split("MapServer/")[1],b=this.parent.map.itemInfo.itemData.operationalLayers,c=0;c<b.length;c++){var d=b[c];if("undefined"!==typeof d.layerObject&&d.layerObject.infoTemplates&&(d=d.layerObject.infoTemplates[a])){q.infoTemplate=
d.infoTemplate;break}}this.tab.tabLayers[1]=q;this.summaryFields=this._getFields(this.tab.tabLayers[1]);f?this._queryFeatures(k,f).then(function(a){l.resolve(a)}):(this._initGraphicsLayer(e),m.hitch(this,this._queryFeatures(k)))})));if(f)return l}},_initGraphicsLayer:function(a){null!==a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?
this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol))},_queryFeatures:function(a,g){var e;g&&(e=new s);for(var c=[],h=new y,b=0;b<a.length;b++)h.geometry=a[b],c.push(this.summaryLayer.queryIds(h));(new v(c)).then(m.hitch(this,function(a){for(var b,c,k=0;k<a.length;k++)a[k][0]&&(b=a[k][1],c=b=0===k?b:c.concat(b));b?(this.summaryIds=b,0<this.summaryIds.length?g?this._queryFeaturesByIds(g).then(function(a){e.resolve(a)}):this._queryFeaturesByIds():g||this._processResults()):
g||this._processResults()}),m.hitch(this,function(a){console.error(a);new x({message:a})}));if(g)return e},_queryFeaturesByIds:function(a){var g,e=[];a&&(g=new s);var c=this.summaryLayer.maxRecordCount||1E3,h=this.summaryIds.slice(0,c);this.summaryIds.splice(0,c);var b=new y,d=!1;u.some(this.summaryFields,m.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return d=!0}));a&&(d=!0);b.returnGeometry=d;var f=[];u.forEach(this.summaryFields,function(a){f.push(a.field)});
this.symbolField&&f.push(this.symbolField);b.outFields=!0===this.config.csvAllFields||"true"===this.config.csvAllFields?["*"]:f;b.objectIds=h;for(e.push(this.summaryLayer.queryFeatures(b));0<this.summaryIds.length;)h=this.summaryIds.slice(0,c),this.summaryIds.splice(0,c),b.objectIds=h,e.push(this.summaryLayer.queryFeatures(b));(new v(e)).then(m.hitch(this,function(b){for(var c=0;c<b.length;c++)if(b[c][0]){var d=b[c][1];d.features&&(this.summaryFeatures=this.summaryFeatures.concat(d.features))}a?this._processResults(a).then(m.hitch(this,
function(a){this.SA_SAT_download&&p.replace(this.SA_SAT_download,"download","processing");g.resolve(a)})):(this._processResults(),this.SA_SAT_download&&p.replace(this.SA_SAT_download,"download","processing"));this.SA_SAT_download&&p.replace(this.SA_SAT_download,"download","processing")}),m.hitch(this,function(a){console.error(a);new x({message:a})}));if(a)return g},_prepResults:function(){for(var a=0;a<this.summaryFields.length;a++){var g=this.summaryFields[a],e=g.field,c=g.total;switch(g.type){case "count":c=
this.summaryFeatures.length;break;case "area":c=n.getArea(this.summaryFeatures,this.summaryGeoms,this.config.distanceSettings,this.config.distanceUnits);break;case "length":c=n.getLength(this.summaryFeatures,this.summaryGeoms,this.config.distanceSettings,this.config.distanceUnits);break;case "sum":c=n.getSum(this.summaryFeatures,e);break;case "avg":c=n.getSum(this.summaryFeatures,e)/this.summaryFeatures.length;break;case "min":c=n.getMin(this.summaryFeatures,e);break;case "max":c=n.getMax(this.summaryFeatures,
e)}g.total=c}},_processResults:function(a){this._prepResults();var g,e=this.summaryFields,c=0,h;if(a)g=new s;else{this.container.innerHTML="";p.remove(this.container,"loading");if(0===this.summaryFeatures.length){this.container.innerHTML=this.parent.nls.noFeaturesFound;return}h=r.create("div",{style:"width:"+220*(e.length+1)+"px;"},this.container);p.add(h,"SAT_tabPanelContent");var b=r.create("div",{},h);p.add(b,"SATcolExport");p.add(b,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");
b=r.create("div",{"data-dojo-attach-point":"SA_SAT_download",title:this.parent.nls.downloadCSV},b);p.add(b,[this.parent.isBlackTheme?"btnExportBlack":"btnExport","download"]);w(b,"click",m.hitch(this,this._exportToCSV,e))}for(var b=[],d=0;d<e.length;d++){var f=e[d],l=C.stripHTML(f.alias?f.alias:"")+"\x3cbr/\x3e",c=f.alias===this.parent.nls.area||f.alias===this.parent.nls.length?f.total:Math.round(f.total);isNaN(c)&&(c=0);f=B.format(c);if(a)b.push({num:f,info:l,total:c});else{c=r.create("div",{"class":"SATcol"},
h);p.add(c,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var k=r.create("div",{style:"max-height: 60px;"},c);r.create("div",{"class":" SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:l},k);r.create("div",{"class":" colSummary",innerHTML:f},c)}}e=[];h=null!==this.graphicsLayer;!a&&h&&(this.graphicsLayer.clear(),this.tab.tabLayers[1].clear());if(this.summaryFeatures)for(d=0;d<this.summaryFeatures.length;d++)l=this.summaryFeatures[d],this.lyrSymbol?l.symbol=this.lyrSymbol:
h&&this.graphicsLayer.renderer?(f=this.graphicsLayer.renderer.getSymbol(l),l.symbol=f):this.summaryLayer.renderer&&this.summaryLayer.renderer.getSymbol&&(l.symbol=this.summaryLayer.renderer.getSymbol(l)),!a&&h?(this.graphicsLayer.add(l),this.tab.tabLayers[1].add(l)):e.push(l);!a&&h&&(this.graphicsLayer.setVisibility(!0),this.parent._toggleTabLayersNew(this.tabNum),this.tab.restore&&this.emit("summary-complete",{bubbles:!0,cancelable:!0,tab:this.tabNum}));if(a)return g.resolve({graphics:e,analysisResults:b,
context:this}),g},_exportToCSV:function(a,g,e,c){a=n.exportToCSV(this.summaryFeatures,g,e,c,{type:"summary",baseLabel:this.baseLabel,csvAllFields:this.parent.config.csvAllFields,layer:this.summaryLayer,opLayers:this.parent.opLayers,nlsValue:this.parent.nls.summary,nlsCount:this.parent.nls.count,summaryFields:this.summaryFields,calcFields:this.calcFields});this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){var g=n.getSkipFields(a),e=[];if("undefined"!==typeof this.tab.advStat){var c=
this.tab.advStat.stats,h;for(h in c)0<c[h].length&&u.forEach(c[h],function(a){e.push({field:a.expression,alias:a.label+"",type:h,total:0})})}else{if(a.infoTemplate)c=a.infoTemplate.info.fieldInfos;else if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var b=this.tab.tabLayers[0].url.split("MapServer/")[1],d=this.parent.map.itemInfo.itemData.operationalLayers,c=null,f=0;f<d.length;f++){var l=d[f];if(l.layerObject.infoTemplates&&(l=l.layerObject.infoTemplates[b])){c=l.infoTemplate.info.fieldInfos;
break}}else c=a.fields;c||(c=a.fields);for(b=0;b<c.length;b++)if(d=c[b],"undefined"!==typeof a.fields){var f=a.fields[b].type,k;if(d.name!==a.objectIdField&&("esriFieldTypeDouble"===f||"esriFieldTypeInteger"===f||"esriFieldTypeSmallInteger"===f))"undefined"!==typeof d.visible?d.visible&&(k={field:d.fieldName,alias:d.label,type:"sum",total:0}):k={field:d.name,alias:d.alias,type:"sum",total:0},k&&-1===g.indexOf(k.field)&&e.push(k),k=null}}this.calcFields=m.clone(e);if(this.allFields){c=0;for(;c<a.fields.length;c++){k=
a.fields[c];b=!0;d=0;b:for(;d<e.length;d++)if(k.name===e[d].field){b=!1;break b}-1===g.indexOf(k.name)&&b&&e.push({field:k.name,alias:k.alias,type:k.type})}}return e}})});