// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/Deferred ./utils dijit/_TemplatedMixin dijit/_WidgetBase esri/undoManager esri/OperationBase esri/graphic esri/tasks/query esri/tasks/QueryTask esri/tasks/RelationshipQuery esri/layers/FeatureLayer esri/dijit/AttributeInspector jimu/dijit/LoadingIndicator jimu/LayerInfos/LayerInfos".split(" "),function(p,e,k,d,m,l,n,s,t,u,v,w,q,r,x,y,z,A,B){var g=p([t,s],{baseClass:"related-records-editor",templateString:"\x3cdiv\x3e\x3cdiv class\x3d'operation-box' data-dojo-attach-point\x3d'operationBox'\x3e\x3cdiv class\x3d'previos-btn feature-action' data-dojo-attach-point\x3d'previouBtn'data-dojo-attach-event\x3d'click:_onPreviouBtnClick'\x3e\x3c/div\x3e\x3cdiv class\x3d'operation-title' data-dojo-attach-point\x3d'operationTitle'\x3e\x3c/div\x3e\x3cdiv class\x3d'add-new-btn' data-dojo-attach-point\x3d'addNewBtn'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'content-box' data-dojo-attach-point\x3d'contentBox'\x3e\x3c/div\x3e\x3c/div\x3e",
editorATI:null,originalFeature:null,originalLayer:null,originalJimuLayerInfo:null,layerInfosObj:null,undoManager:null,refDomNode:null,_temporaryData:null,tableInfosParam:null,postCreate:function(){this._init();d.place(this.domNode,this.refDomNode,"after");window.isRTL?d.addClass(this.previouBtn,"icon-arrow-forward"):d.addClass(this.previouBtn,"icon-arrow-back");this.loading=(new A({hidden:!0})).placeAt(this.domNode);this._clearPage();this.showFirstPage({feature:this.originalFeature,oriJimuLayerInfo:this.originalJimuLayerInfo})},
_init:function(){this.refDomNode=this.editorATI.domNode;this.originalLayer=this.originalFeature.getLayer();this.layerInfosObj=B.getInstanceSync();this.originalJimuLayerInfo=this.layerInfosObj.getLayerOrTableInfoById(this.originalLayer.id);this.undoManager=new u;this._temporaryData={eventHandles:[],dijits:[]}},destroy:function(){this._clearPage();this.inherited(arguments)},_getRelatedTableInfoArray:function(a){var b=new l,c=[];a.getRelatedTableInfoArray("esriRelRoleOrigin").then(e.hitch(this,function(a){k.forEach(a,
function(a){this._findTableInfoFromTableInfosParam(a)&&c.push(a)},this);b.resolve(c)}));return b},_getRelatedRecordsByQuery:function(a){var b=new l,c=new q,C=new r(a.destJimuLayerInfo.getUrl()),d=a.destJimuLayerInfo.layerObject.relationships.keyField,f=a.oriJimuLayerInfo.layerObject.objectIdField;c.where=d?d+" \x3d "+a.feature.attributes[d]:f+" \x3d "+a.feature.attributes[f];c.outFields=["*"];C.execute(c,e.hitch(this,function(a){b.resolve(a)}));return b},_getRelatedRecordsByRelatedQuery:function(a){var b=
new l,c=new x,d=this._getOriRelationshipByDestLayer(a);c.outFields=["*"];c.relationshipId=d.id;var h=a.feature.attributes[a.oriJimuLayerInfo.layerObject.objectIdField];c.objectIds=[h];a.oriJimuLayerInfo.layerObject.queryRelatedFeatures(c,e.hitch(this,function(a){(a=a[h]&&a[h].features)?b.resolve(a):b.resolve([])}),e.hitch(this,function(){b.resolve([])}));return b},_getOriRelationshipByDestLayer:function(a){var b=null;k.some(a.oriJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===
a.destJimuLayerInfo.layerObject.layerId)return b=c,!0},this);return b},_getDestRelationshipByDestLayer:function(a){var b=null;k.some(a.destJimuLayerInfo.layerObject.relationships,function(c){if(c.relatedTableId===a.oriJimuLayerInfo.layerObject.layerId)return b=c,!0},this);return b},_createATI:function(a){var b=null,c=this._findTableInfoFromTableInfosParam(a.destJimuLayerInfo);c&&(b=new g.ATI({layerInfos:[c],hideNavButtons:!0},d.create("div")),b.startup(),this._temporaryData.dijits.push(b));c=m(b,
"delete",e.hitch(this,this._onDeleteBtnClick,a));this._temporaryData.eventHandles.push(c);c=m(b,"attribute-change",e.hitch(this,this._onAttributeChange,a));this._temporaryData.eventHandles.push(c);return b},_findTableInfoFromTableInfosParam:function(a){var b=null;k.some(this.tableInfosParam,function(c){if(c.featureLayer.id===a.id)return b=c,!0},this);return b},_addNewRelatedRecord:function(a){var b=new l,c={},d=a.destJimuLayerInfo.layerObject,h=this._getOriRelationshipByDestLayer(a),f=this._getDestRelationshipByDestLayer(a);
k.forEach(d.fields,function(a){"esriFieldTypeDate"===a.type&&(c[a.name]=(new Date).valueOf())},this);h.keyField&&f.keyField&&(h=n.ignoreCaseToGetFieldKey(a.oriJimuLayerInfo.layerObject,h.keyField),f=n.ignoreCaseToGetFieldKey(a.destJimuLayerInfo.layerObject,f.keyField),h&&f&&(c[f]=a.feature.attributes[h]));var g=new w(null,null,c,null);d.applyEdits([g],null,null,e.hitch(this,function(a){var c=a[0];if(c.success&&c.objectId){a=new q;var f=new r(d.url);a.where=d.objectIdField+" \x3d "+c.objectId;a.outFields=
["*"];f.execute(a,e.hitch(this,function(a){(a=a.features[0])?b.resolve(a):(g.attributes[d.objectIdField]=c.objectId,b.resolve(g))}),e.hitch(this,function(){b.reject()}))}else b.reject()}),e.hitch(this,function(){b.reject()}));return b},_deleteRelatedRecord:function(a){var b=new l;a.destJimuLayerInfo.layerObject.applyEdits(null,null,[a.relatedFeature],e.hitch(this,function(){b.resolve()}),e.hitch(this,function(){b.reject()}));return b},_updateRelatedRecord:function(a,b){var c=new l,d=a.destJimuLayerInfo.layerObject,
g=a.relatedFeature;g.attributes[b.fieldName]=b.fieldValue;d.applyEdits(null,[g],null,e.hitch(this,function(){c.resolve()}),e.hitch(this,function(){c.reject()}));return c},_getDisplayTitleOfRelatedRecord:function(a,b){var c=n.getAttrByFieldKey(b,a.destJimuLayerInfo.layerObject.displayField||a.destJimuLayerInfo.layerObject.objectIdField);if(c){var d=n.ignoreCaseToGetFieldObject(a.destJimuLayerInfo.layerObject,a.destJimuLayerInfo.layerObject.displayField);d&&(d.type&&"esriFieldTypeDate"===d.type)&&(c=
n.getLocaleDateTime(c))}else c="";return c},showRelatedRecords:function(a){this._changeRefDomNode();var b=e.getObject("_wabProperties.originalLayerName",!1,a.destJimuLayerInfo.layerObject)||a.destJimuLayerInfo.title;this._setOperationTitle(b);this._clearPage();this.loading.show();this._getRelatedRecordsByRelatedQuery(a).then(e.hitch(this,function(b){this._showAddNewBtn(a);0<b.length?this._setTitle(window.jimuNls.popup.relatedRecords):this._setTitle(window.jimuNls.popup.noRelatedRecotds,"font-normal");
k.forEach(b,function(b,c){var f=this._getDisplayTitleOfRelatedRecord(a,b),f=d.create("div",{"class":"item record-item "+(0===c%2?"oddLine":"evenLine"),innerHTML:f},this.contentBox),f=m(f,"click",e.hitch(this,function(){this._addOperation(g.OPERATION_SHOW_RELATED_RECORDS,a);this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,b))}));this._temporaryData.eventHandles.push(f)},this);this.loading.hide()}))},showInspector:function(a){this._changeRefDomNode();var b=
(e.getObject("_wabProperties.originalLayerName",!1,a.destJimuLayerInfo.layerObject)||a.destJimuLayerInfo.title)+": "+this._getDisplayTitleOfRelatedRecord(a,a.relatedFeature);this._setOperationTitle(b);this._clearPage();this.loading.show();(b=this._createATI(a))&&d.place(b.domNode,this.contentBox);var b=a.destJimuLayerInfo.layerObject.objectIdField,c=new q;c.where=b+" \x3d "+a.relatedFeature.attributes[b];a.destJimuLayerInfo.layerObject.selectFeatures(c,y.SELECTION_NEW,e.hitch(this,function(){this.loading.hide()}));
this.showRelatedTables(this._createOperationData(a.relatedFeature,a.destJimuLayerInfo,null,null),a)},showRelatedTables:function(a,b){this._getRelatedTableInfoArray(a.oriJimuLayerInfo).then(e.hitch(this,function(c){0<c.length&&this._setTitle(window.jimuNls.popup.relatedTables);k.forEach(c,function(c,h){var f=d.create("div",{"class":"item table-item "+(0===h%2?"oddLine":"evenLine"),innerHTML:c.title},this.contentBox),f=m(f,"click",e.hitch(this,function(){c.getLayerObject().then(e.hitch(this,function(){b?
this._addOperation(g.OPERATION_SHOW_INSPECTOR,b):this._addOperation(g.OPERATION_FIRST,a);this.showRelatedRecords(this._createOperationData(a.feature,a.oriJimuLayerInfo,c,null))}))}));this._temporaryData.eventHandles.push(f)},this)}))},showFirstPage:function(a){this._clearPage();this._revertRefDomNode();this.showRelatedTables(a)},_onAddNewBtnClick:function(a){this.loading.show();this._addNewRelatedRecord(a).then(e.hitch(this,function(b){this.loading.hide();this._addOperation(g.OPERATION_SHOW_RELATED_RECORDS,
a);this.showInspector(this._createOperationData(a.feature,a.oriJimuLayerInfo,a.destJimuLayerInfo,b))}),e.hitch(this,function(){this.loading.hide()}))},_onDeleteBtnClick:function(a){this.loading.show();this._deleteRelatedRecord(a).then(e.hitch(this,function(){this.loading.hide();this._onPreviouBtnClick()}),e.hitch(this,function(){this.loading.hide()}))},_onAttributeChange:function(a,b){this.loading.show();this._updateRelatedRecord(a,b).then(e.hitch(this,function(){this.loading.hide()}),e.hitch(this,
function(){this.loading.hide()}))},_createOperationData:function(a,b,c,d){return{feature:a,oriJimuLayerInfo:b,destJimuLayerInfo:c,relatedFeature:d}},_addOperation:function(a,b){this.undoManager.add(new g.Operation(a,b,this))},_onPreviouBtnClick:function(){this.undoManager.undo()},_clearPage:function(){d.empty(this.contentBox);d.setStyle(this.addNewBtn,"display","none");k.forEach(this._temporaryData.eventHandles,function(a){a&&a.remove&&a.remove()},this);this._temporaryData.eventHandles=[];k.forEach(this._temporaryData.dijits,
function(a){a&&a.destroy&&a.destroy()},this);this._temporaryData.dijits=[]},_changeRefDomNode:function(){d.setStyle(this.refDomNode,"display","none");d.setStyle(this.operationBox,"display","block");d.addClass(this.domNode,"fix-height-mode");this.previouBtn.title=window.jimuNls.common.back;this.addNewBtn.title=window.jimuNls.common.newText;this.undoManager.peekUndo()?d.setStyle(this.previouBtn,"display","block"):d.setStyle(this.previouBtn,"display","none")},_revertRefDomNode:function(){d.setStyle(this.refDomNode,
"display","block");d.setStyle(this.operationBox,"display","none");d.removeClass(this.domNode,"fix-height-mode")},_showAddNewBtn:function(a){var b=a.destJimuLayerInfo.layerObject;"Table"===b.type&&(b.getEditCapabilities&&b.getEditCapabilities().canCreate)&&(d.setStyle(this.addNewBtn,"display","block"),a=m(this.addNewBtn,"click",e.hitch(this,this._onAddNewBtnClick,a)),this._temporaryData.eventHandles.push(a))},_setTitle:function(a,b){a&&d.create("div",{"class":"title-box "+(b?b:""),innerHTML:a},this.contentBox)},
_setOperationTitle:function(a){d.setAttr(this.operationTitle,"innerHTML",a);d.setAttr(this.operationTitle,"title",a)}});g.Operation=p([v],{constructor:function(a,b,c){this.operationName=a;this.operationData=b;this.relatedRecordsEditor=c},performUndo:function(){switch(this.operationName){case g.OPERATION_SHOW_RELATED_TABLES:return this.relatedRecordsEditor.showRelatedTables(this.operationData);case g.OPERATION_SHOW_RELATED_RECORDS:return this.relatedRecordsEditor.showRelatedRecords(this.operationData);
case g.OPERATION_SHOW_INSPECTOR:return this.relatedRecordsEditor.showInspector(this.operationData);default:return this.relatedRecordsEditor.showFirstPage(this.operationData)}}});g.ATI=p([z],{constructor:function(){this._aiConnects=[];this._selection=[];this._toolTips=[]}});e.mixin(g,{OPERATION_SHOW_RELATED_TABLES:"showRelatedTables",OPERATION_SHOW_RELATED_RECORDS:"showRelatedRecords",OPERATION_SHOW_INSPECTOR:"showInspector",OPERATION_FIRST:"first"});return g});