// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/AddData/search/templates/AddFromFilePane.html":'\x3cdiv class\x3d"secondary-pane add-file-pane"\x3e\r\n\r\n  \x3cdiv class\x3d"generalize-options"\x3e\r\n    \x3cdiv data-dojo-type\x3d"jimu/dijit/CheckBox"\r\n      data-dojo-attach-point\x3d"generalizeCheckBox"\r\n      data-dojo-props\x3d"checked:true,label:\'${i18n.addFromFile.generalizeOn}\'"\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\r\n  \x3cdiv class\x3d"browse-or-drop"\x3e\r\n    \x3cdiv class\x3d"drop-container" data-dojo-attach-point\x3d"dropContainer"\x3e\r\n      \x3cdiv class\x3d"drop-area" data-dojo-attach-point\x3d"dropArea"\x3e\r\n        \x3cdiv class\x3d"supported-file-types" data-dojo-attach-point\x3d"supportedFileTypes"\x3e\x3c/div\x3e\r\n        \x3cdiv class\x3d"or"\x3e${i18n.addFromFile.dropOrBrowse}\x3c/div\x3e\r\n        \x3cform class\x3d"file-form" enctype\x3d"multipart/form-data" method\x3d"post"\r\n          data-dojo-attach-point\x3d"fileForm"\x3e\r\n          \x3clabel for\x3d"${id}_file" class\x3d"jimu-btn"\r\n            data-dojo-attach-point\x3d"uploadLabel"\x3e${i18n.addFromFile.browse}\x3c/label\x3e\r\n          \x3cinput id\x3d"${id}_file" name\x3d"file" type\x3d"file" style\x3d"display:none"\r\n            data-dojo-attach-point\x3d"fileNode" /\x3e\r\n        \x3c/form\x3e\r\n        \x3ca href\x3d"#" class\x3d"drop-area-hint" data-dojo-attach-point\x3d"hintButton"\x3e\r\n          \x3ci class\x3d"esri-icon-question"\x3e\x3c/i\x3e\r\n        \x3c/a\x3e\r\n        \x3cspan class\x3d"upload-arrow"\x3e\x3c/span\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/on dojo/Deferred dojo/dom-class dijit/Viewport dojo/sniff dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./templates/AddFromFilePane.html dojo/i18n!../nls/strings ./LayerLoader ./util esri/request esri/layers/FeatureLayer esri/geometry/scaleUtils jimu/dijit/Message jimu/dijit/CheckBox".split(" "),function(s,n,q,g,t,k,u,v,w,x,y,z,f,A,l,r,B,C,p){return s([w,x,y],{i18n:f,templateString:z,wabWidget:null,
maxRecordCount:1E3,maxRecordThreshold:1E5,SHAPETYPE_ICONS:[{type:"shapefile",url:"images/filetypes/zip.svg"},{type:"csv",url:"images/filetypes/csv.svg"},{type:"gpx",url:"images/filetypes/gpx.svg"},{type:"geojson",url:"images/filetypes/geojson.svg"}],postCreate:function(){this.inherited(arguments);this.own(u.on("resize",this.resize()))},destroy:function(){this.inherited(arguments)},startup:function(){if(!this._started){this.inherited(arguments);var a=this,b=this.dropArea,c,e=this.wabWidget.config;
if(e.addFromFile)try{c=Number(e.addFromFile.maxRecordCount),"number"===typeof c&&!isNaN(c)&&(c=Math.floor(c),1<=c&&c<=this.maxRecordThreshold&&(this.maxRecordCount=c))}catch(d){console.warn("Error setting AddFromFile.maxRecordCount:"),console.warn(d)}if(f.addFromFile.types)try{for(var m in f.addFromFile.types)this._createFileTypeImage(m)}catch(l){console.warn("Error reading support file types:"),console.warn(l)}this.own(g(this.fileNode,"change",function(){if(!a._getBusy()){a._setBusy(!0);var h=a._getFileInfo();
h.ok&&a._execute(h)}}));this.own(g(this.uploadLabel,"click",function(h){a._getBusy()&&(h.preventDefault(),h.stopPropagation())}));this.own(g(b,"dragenter",function(h){h.preventDefault();a._getBusy()||(k.add(b,"hit"),a._setStatus(""))}));this.own(g(b,"dragleave",function(a){a.preventDefault();k.remove(b,"hit")}));this.own(g(b,"dragover",function(a){a.preventDefault()}));this.own(g(b,"drop",function(h){h.preventDefault();h.stopPropagation();a._getBusy()||(a._setBusy(!0),h=a._getFileInfo(h),h.ok&&a._execute(h))}));
c=this.wabWidget.domNode;this.own(g(c,"dragenter",function(a){a.preventDefault()}));this.own(g(c,"dragleave",function(a){a.preventDefault()}));this.own(g(c,"dragover",function(a){a.preventDefault()}));this.own(g(c,"drop",function(a){a.preventDefault()}));this.own(g(this.hintButton,"click",n.hitch(this,function(a){a.preventDefault();a='\x3cdiv class\x3d"intro"\x3e\x3clabel\x3e'+f.addFromFile.intro+"\x3c/label\x3e\x3cul\x3e\x3cli\x3e"+f.addFromFile.types.Shapefile+"\x3c/li\x3e\x3cli\x3e"+f.addFromFile.types.CSV+
"\x3c/li\x3e\x3cli\x3e"+f.addFromFile.types.GPX+"\x3c/li\x3e\x3cli\x3e"+f.addFromFile.types.GeoJSON+'\x3c/li\x3e\x3cli\x3e\x3cspan class\x3d"note"\x3e'+f.addFromFile.maxFeaturesAllowedPattern.replace("{count}",this.maxRecordCount)+"\x3c/span\x3e\x3c/li\x3e\x3c/ul\x3e\x3c/div\x3e";new p({message:a})})))}},_addFeatures:function(a,b){var c,e=[],d=a.map,m=0,g=new A;b.layers&&(m=b.layers.length);q.forEach(b.layers,function(b){b=new B(b,{id:g._generateLayerId(),outFields:["*"]});b.xtnAddData=!0;b.graphics&&
(a.numFeatures+=b.graphics.length);0===m?b.name=a.baseFileName:"string"!==typeof b.name||0===b.name.length?b.name=a.baseFileName:0!==b.name.indexOf(a.baseFileName)&&(b.name=f.addFromFile.layerNamePattern.replace("{filename}",a.baseFileName).replace("{name}",b.name));g._setFeatureLayerInfoTemplate(b,null,null);b.fullExtent&&(c=c?c.union(b.fullExtent):b.fullExtent);e.push(b)});0<e.length&&(d.addLayers(e),c&&d.setExtent(c.expand(1.25),!0))},_analyze:function(a,b){if("csv"!==a.fileType.toLowerCase()){var c=
new t;c.resolve(null);return c}var c=a.sharingUrl+"/content/features/analyze",e={f:"json",filetype:a.fileType.toLowerCase()},c=r({url:c,content:e,form:b,handleAs:"json"});c.then(function(b){b&&b.publishParameters&&(a.publishParameters=b.publishParameters)});return c},_createFileTypeImage:function(a){var b=window.isRTL;q.some(this.SHAPETYPE_ICONS,n.hitch(this,function(c,e){if(a.toLowerCase()===c.type){var d=document.createElement("IMG");d.src=this.wabWidget.folderUrl+c.url;d.alt=a;0===e?d.className+=
" "+(b?"last":"first")+"-type-icon":1===e?d.className+=" second-"+(b?"last":"first")+"-type-icon":e===this.SHAPETYPE_ICONS.length-2?d.className+=" second-"+(b?"first":"last")+"-type-icon":e===this.SHAPETYPE_ICONS.length-1&&(d.className+=" "+(b?"first":"last")+"-type-icon");this.supportedFileTypes.appendChild(d)}}))},_execute:function(a){this._setBusy(!0);var b=a.fileName;this._setStatus(f.addFromFile.addingPattern.replace("{filename}",b));var c=this,e=new FormData;e.append("file",a.file);var d={map:this.wabWidget.map,
sharingUrl:this.wabWidget.getSharingUrl(),baseFileName:a.baseFileName,fileName:a.fileName,fileType:a.fileType,generalize:!!this.generalizeCheckBox.getValue(),publishParameters:{},numFeatures:0};c._analyze(d,e).then(function(){return c._generateFeatures(d,e)}).then(function(a){c._addFeatures(d,a.featureCollection);c._setBusy(!1);c._setStatus(f.addFromFile.featureCountPattern.replace("{filename}",b).replace("{count}",d.numFeatures))}).otherwise(function(a){c._setBusy(!1);c._setStatus(f.addFromFile.addFailedPattern.replace("{filename}",
b));console.warn("Error generating features.");console.warn(a);a&&("string"===typeof a.message&&0<a.message.length)&&new p({titleLabel:f._widgetLabel,message:a.message})})},_generateFeatures:function(a,b){var c=a.sharingUrl+"/content/features/generate";a.publishParameters=a.publishParameters||{};var e=n.mixin(a.publishParameters,{name:a.baseFileName,targetSR:a.map.spatialReference,maxRecordCount:this.maxRecordCount,enforceInputFileSizeLimit:!0,enforceOutputJsonSizeLimit:!0});if(a.generalize){var d=
C.getExtentForScale(a.map,4E4).getWidth()/a.map.width;e.generalize=!0;e.maxAllowableOffset=d;for(var d=d/10,f=0;1>d;)d*=10,f++;e.reducePrecision=!0;e.numberOfDigitsAfterDecimal=f}e={f:"json",filetype:a.fileType.toLowerCase(),publishParameters:window.JSON.stringify(e)};return r({url:c,content:e,form:b,handleAs:"json"})},_getBaseFileName:function(a){v("ie")&&(a=a.split("\\"),a=a[a.length-1]);a=a.split(".");return a=a[0].replace("c:\\fakepath\\","")},_getBusy:function(){return k.contains(this.uploadLabel,
"disabled")},_getFileInfo:function(a){var b={ok:!1,file:null,fileName:null,fileType:null};if((a=a?a.dataTransfer.files:this.fileNode.files)&&1===a.length)if(b.file=a=a[0],b.fileName=a.name,l.endsWith(a.name,".zip"))b.ok=!0,b.fileType="Shapefile";else if(l.endsWith(a.name,".csv"))b.ok=!0,b.fileType="CSV";else if(l.endsWith(a.name,".gpx"))b.ok=!0,b.fileType="GPX";else if(l.endsWith(a.name,".geojson")||l.endsWith(a.name,".geo.json"))b.ok=!0,b.fileType="GeoJSON";if(b.ok)b.baseFileName=this._getBaseFileName(b.fileName);
else{a=f.addFromFile.invalidType;"string"===typeof b.fileName&&0<b.fileName.length&&(a=f.addFromFile.invalidTypePattern.replace("{filename}",b.fileName));this._setBusy(!1);this._setStatus(a);var c=document.createElement("div");c.appendChild(document.createTextNode(a));new p({titleLabel:f._widgetLabel,message:c})}return b},resize:function(){},_setBusy:function(a){a?(k.add(this.uploadLabel,"disabled"),k.add(this.dropArea,["hit","disabled"])):(k.remove(this.uploadLabel,"disabled"),k.remove(this.dropArea,
["hit","disabled"]))},_setStatus:function(a){this.wabWidget&&this.wabWidget._setStatus(a)}})});