// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/promise/all dojo/Deferred dojo/json dojo/i18n!../nls/strings ./util esri/lang esri/request esri/arcgis/utils esri/layers/ArcGISDynamicMapServiceLayer esri/layers/ArcGISImageServiceLayer esri/layers/ArcGISTiledMapServiceLayer esri/layers/FeatureLayer esri/layers/ImageServiceParameters esri/layers/KMLLayer esri/layers/MosaicRule esri/layers/RasterFunction esri/layers/VectorTileLayer esri/layers/WMSLayer esri/dijit/PopupTemplate esri/InfoTemplate esri/renderers/jsonUtils jimu/utils".split(" "),
function(t,u,k,v,h,p,q,w,f,m,x,y,z,A,r,B,C,D,E,F,G,s,H,I,J){return t(null,{item:null,itemUrl:null,map:null,serviceUrl:null,constructor:function(a){u.mixin(this,a)},addItem:function(a,b){var c=new h;this.map=b;this.item=a;this.itemUrl=this._checkMixedContent(a.itemUrl);this.serviceUrl=this._checkMixedContent(a.url);if("Feature Service"===a.type)return this._addFeatureService();if("Image Service"===a.type)return this._addImageService();if("KML"===a.type)return this._addKML();if("Map Service"===a.type)return this._addMapService();
if("Vector Tile Service"===a.type)return this._addVectorTileService();if("WMS"===a.type)return this._addWMS();console.warn("Unsupported item type: ",a.type);c.resolve(null);return c},_addFeatureService:function(){var a=this,b=new h,c=this.serviceUrl,e=this.item,d={},l=null,n=[],g=[];a._readItemJsonData().then(function(b){(d=b||{})&&(d.layers&&0<d.layers.length)&&k.forEach(d.layers,function(a){"undefined"!==typeof a.id&&null!==a.id&&(null===l&&(l=[]),l.push(a.id))});return a._readRestInfo(c)}).then(function(b){b&&
"string"===typeof b.type&&"Feature Layer"===b.type?(b=new r(c,{id:a._generateLayerId(),outFields:["*"]}),n.push(a._waitForLayer(b))):b&&(b.layers&&0<b.layers.length)&&k.forEach(b.layers,function(b){var d=!0;null!==l&&0<l.length&&(d=k.some(l,function(a){return a===b.id}));d&&(d=new r(c+"/"+b.id,{id:a._generateLayerId(),outFields:["*"]}),n.push(a._waitForLayer(d)))});return v(n)}).then(function(a){k.forEach(a,function(a){g.push(a)});g.reverse();return g}).then(function(){k.forEach(g,function(b){var c=
a._processFeatureLayer(b,e,d);b.arcgisProps={title:c.title};b._titleForLegend=c.title;f.isDefined(b.title)||(b.title=c.title);a._addLayer(b)})}).then(function(){b.resolve(g)}).otherwise(function(a){b.reject(a)});return b},_addImageService:function(){var a=this,b=new h;a._readItemJsonData().then(function(b){return a._newImageServiceLayer(b||{})}).then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(a){b.reject(a)});return b},_addKML:function(){var a=this,b=new h;a._newKMLLayer().then(function(c){c&&
(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(a){b.reject(a)});return b},_addMapService:function(){var a=this,b=new h;a._readItemJsonData().then(function(b){return a._newMapServiceLayer(b||{})}).then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(a){b.reject(a)});return b},_addVectorTileService:function(){var a=this,b=new h;a._newVectorTileLayer().then(function(c){a._addLayer(c);b.resolve(c)}).otherwise(function(a){b.reject(a)});return b},_addWMS:function(){var a=
this,b=new h;a._readItemJsonData().then(function(b){return a._newWMSLayer(b||{})}).then(function(c){c&&(c.title=a.item.title);a._addLayer(c);b.resolve(c)}).otherwise(function(a){b.reject(a)});return b},_addLayer:function(a){var b=this.item;a&&(a.xtnItemId=b.id,a.xtnAddData=!0,!a.arcgisProps&&b&&(a.arcgisProps={title:b.title},a._titleForLegend=b.title),f.isDefined(a.title)||(a.title=b.title),this.map.addLayer(a))},_checkMixedContent:function(a){return w.checkMixedContent(a)},_checkUrl:function(a){return x._checkUrl(a)},
_checkVectorTileUrl:function(a,b){var c=new h;if(-1!==a.indexOf(".json",a.length-5))return b.styleUrl=a,c.resolve(a),c;var e={url:null,content:{},handleAs:"json",callbackParamName:"callback"};this.itemUrl?(e.url=this.itemUrl+"/resources/styles/root.json",m(e,{}).then(function(){b.styleUrl=e.url;c.resolve(e.url)}).otherwise(function(){e.url=a+"/resources/styles/root.json";m(e,{}).then(function(){b.styleUrl=e.url;c.resolve(e.url)}).otherwise(function(){b.url=a;c.resolve(a)})})):(e.url=a+"/resources/styles/root.json",
m(e,{}).then(function(){b.styleUrl=e.url;c.resolve(e.url)}).otherwise(function(){b.url=a;c.resolve(a)}));return c},_generateLayerId:function(){return this._generateLayerIds(1)[0]},_generateLayerIds:function(a){var b,c=[];for(b=0;b<a;b++)c.push(this._generateRandomId());return c},_generateRandomId:function(){var a=null,a="function"===typeof Date.now?Date.now():(new Date).getTime(),b=(""+Math.random()).replace("0.","r");return(a+""+b).replace(/-/g,"")},_makeFeatureLayerTitle:function(a,b,c){var e,d,
l;try{if(b&&c&&b===c||b&&c&&(e=c.indexOf(b),0===e&&(d=c.substring(e+b.length+1),13<=d.length&&(l=/^\d+$/,l.test(d)))))return b}catch(f){}return a.replace("{serviceName}",b).replace("{layerName}",c)},_newImageServiceLayer:function(a){var b=new h,c=this._generateLayerId(),e=this.serviceUrl,d={mapLayerId:c,bandIds:null,format:null,compressionQuality:null,opacity:1,visibility:!0};f.isDefined(a.visibility)&&!1===a.visibility&&(d.visibility=!1);f.isDefined(a.opacity)&&(d.opacity=a.opacity);f.isDefined(a.minScale)&&
!f.isDefined(d.minScale)&&(d.minScale=a.minScale);f.isDefined(a.maxScale)&&!f.isDefined(d.maxScale)&&(d.maxScale=a.maxScale);f.isDefined(a.refreshInterval)&&!f.isDefined(d.refreshInterval)&&(d.refreshInterval=a.refreshInterval);a.popupInfo&&(!d.popupInfo&&!d.disablePopup)&&(d.popupInfo=a.popupInfo);a.renderingRule&&!d.renderingRule&&(d.renderingRule=a.renderingRule,a.renderingRule.functionName&&(d.renderingRule.rasterFunction=a.renderingRule.functionName));a.bandIds&&!d.bandIds&&(d.bandIds=a.bandIds);
a.mosaicRule&&!d.mosaicRule&&(d.mosaicRule=a.mosaicRule);a.format&&!d.format&&(d.format=a.format);f.isDefined(a.compressionQuality)&&!f.isDefined(d.compressionQuality)&&(d.compressionQuality=a.compressionQuality);if(a.layerDefinition&&a.layerDefinition.definitionExpression&&(!f.isDefined(d.layerDefinition)||!f.isDefined(d.layerDefinition.definitionExpression)))d.layerDefinition=d.layerDefinition||{},d.layerDefinition.definitionExpression=a.layerDefinition.definitionExpression;a=new B;null!==d.bandIds&&
(a.bandIds=d.bandIds);null!==d.format&&(a.format=d.format,null!==d.compressionQuality&&(a.compressionQuality=d.compressionQuality));d.renderingRule&&d.renderingRule.rasterFunction&&(c=new E(d.renderingRule),a.renderingRule=c);d.mosaicRule&&(c=new D(d.mosaicRule),a.mosaicRule=c);f.isDefined(d.noData)&&(a.noData=d.noData);f.isDefined(d.noDataInterpretation)&&(a.noDataInterpretation=d.noDataInterpretation);f.isDefined(d.interpolation)&&(a.interpolation=d.interpolation);a={imageServiceParameters:a,opacity:d.opacity,
visible:d.visibility};f.isDefined(d.mapLayerId)&&(a.id=d.mapLayerId);f.isDefined(d.minScale)&&(a.minScale=d.minScale);f.isDefined(d.maxScale)&&(a.maxScale=d.maxScale);f.isDefined(d.refreshInterval)&&(a.refreshInterval=d.refreshInterval);f.isDefined(d.resourceInfo)&&(a.resourceInfo=d.resourceInfo);e=new z(this._checkUrl(e),a);this._waitForLayer(e).then(function(a){d.layerDefinition&&d.layerDefinition.definitionExpression&&a.setDefinitionExpression(d.layerDefinition.definitionExpression,!0);b.resolve(a)},
function(a){b.reject(a)});return b},_newInfoTemplate:function(a,b){if(a)try{return new s({description:a.description,title:a.title,showAttachments:a.showAttachments,fieldInfos:a.fieldInfos,mediaInfos:a.mediaInfos})}catch(c){console.error(c)}var e=new H;f.isDefined(b)&&e.setTitle(b);return e},_newKMLLayer:function(){var a={id:this._generateLayerId()},a=new C(this.serviceUrl,a);return this._waitForLayer(a)},_newMapServiceLayer:function(a){var b=this,c=new h,e=this.serviceUrl,d=this._generateLayerId();
m({url:e,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{}).then(function(f){var n=null,n={id:d},n=f.tileInfo?new A(e,n):new y(e,n);b._waitForLayer(n).then(function(d){var e=null;k.forEach(d.layerInfos,function(d){var c=null;a&&k.some(a.layers,function(a){if(d.id===a.id)return c=a,!0});var f=null;c&&c.popupInfo&&(f=c.popupInfo);f&&(null===e&&(e={}),e[d.id]={infoTemplate:b._newInfoTemplate(f,d.name)})});null===d.infoTemplates&&e&&(d.infoTemplates=e);c.resolve(d)},function(a){c.reject(a)})},
function(a){c.reject(a)});return c},_newPopupInfo:function(a,b){if(a&&a.fields){var c={title:a.name,fieldInfos:[],description:null,showAttachments:!0,mediaInfos:[]};"string"===typeof b&&0<b.length&&(c.title=b);k.forEach(a.fields,function(a){var b=J.getDefaultPortalFieldInfo(a);b.visible=!0;b.isEditable=a.editable;c.fieldInfos.push(b)});return c}return null},_newVectorTileLayer:function(){var a=this,b=new h,c={},e=this.serviceUrl,d=this._generateLayerId();"string"===typeof e&&0<e.length?this._checkVectorTileUrl(e,
c).then(function(c){"string"===typeof c&&0<c.length?(c=a._checkMixedContent(c),c=new F(c,{id:d,opacity:1,visible:!0}),a._waitForLayer(c).then(function(a){b.resolve(a)},function(a){b.reject(a)})):b.resolve(null)},function(a){b.reject(a)}):b.resolve(null);return b},_newWMSLayer:function(){var a={id:this._generateLayerId()},a=new G(this.serviceUrl,a),b=this,a=this._waitForLayer(a);a.then(function(a){b._setWMSVisibleLayers(a)});return a},_processFeatureLayer:function(a,b,c){var e=this,d=q.search.featureLayerTitlePattern,
l=null;c&&c.layers&&0<c.layers.length?k.some(c.layers,function(c){var g,h,k,m=!1;if(c.id===a.layerId){c.popupInfo&&(g=c.popupInfo,g=p.parse(p.stringify(g)),g=new s(g),a.setInfoTemplate(g),m=!0);f.isDefined(c.showLabels)&&a.setShowLabels(c.showLabels);f.isDefined(c.refreshInterval)&&a.setRefreshInterval(c.refreshInterval);f.isDefined(c.showLegend)&&console.log("");f.isDefined(c.timeAnimation)&&!1===c.timeAnimation&&console.log("");if(g=c.layerDefinition)g.definitionExpression&&a.setDefinitionExpression(g.definitionExpression),
g.displayField&&a.displayField(g.displayField),g.drawingInfo&&(g.drawingInfo.renderer&&(h=p.parse(p.stringify(g.drawingInfo.renderer)),k=I.fromJson(h),h.type&&"classBreaks"===h.type&&(k.isMaxInclusive=!0),a.setRenderer(k)),f.isDefined(g.drawingInfo.transparency)&&a.setOpacity(1-g.drawingInfo.transparency/100)),f.isDefined(g.minScale)&&a.setMinScale(g.minScale),f.isDefined(g.maxScale)&&a.setMaxScale(g.maxScale),f.isDefined(g.defaultVisibility)&&!1===g.defaultVisibility&&a.setVisibility(!1);m||e._setFeatureLayerInfoTemplate(a,
c.popupInfo);l={url:a.url,id:a.id,itemId:b.id,title:e._makeFeatureLayerTitle(d,b.title,a.name)};return!0}}):(l={url:a.url,id:a.id,itemId:b.id,title:e._makeFeatureLayerTitle(d,b.title,a.name)},e._setFeatureLayerInfoTemplate(a,null,l.title));return l},_readItemJsonData:function(){return m({url:this.itemUrl+"/data",content:{f:"json"},handleAs:"json"},{})},_readRestInfo:function(a){return m({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"},{})},_setFeatureLayerInfoTemplate:function(a,
b,c){b||(b=this._newPopupInfo(a,c));b=this._newInfoTemplate(b,c);a.setInfoTemplate(b)},_setWMSVisibleLayers:function(a){var b=[];a&&(k.some(a.layerInfos,function(a){if("string"===typeof a.name&&0<a.name.length)if(10>b.length)b.push(a.name);else return!0}),10>=b.length&&a.setVisibleLayers(b))},_waitForLayer:function(a){var b=new h,c=[];if(a.loaded)return b.resolve(a),b;if(a.loadError)return b.reject(a.loadError),b;var e=function(){k.forEach(c,function(a){a.remove()})};c.push(a.on("load",function(a){e();
b.resolve(a.layer)}));c.push(a.on("error",function(a){e();a=a.error;try{a.message&&-1!==a.message.indexOf("Unable to complete")?(console.warn("layerAccessError",a),b.reject(Error(q.search.layerInaccessible))):b.reject(a)}catch(c){b.reject(a)}}));return b}})});