// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["./BaseVersionManager","./utils"],function(l,m){function k(){this.versions=[{version:"1.0",description:"The version embedded in portal 10.3 final.",upgrader:function(a){return a},compatible:!0},{version:"1.1",description:"The version embedded in online3.6, and used in developer edition 1.0.",upgrader:function(a){if(a.widgetOnScreen&&a.widgetOnScreen.panel&&("themes/FoldableTheme/panels/TitlePanel/Panel"===a.widgetOnScreen.panel.uri||"jimu/BaseWidgetPanel"===a.widgetOnScreen.panel.uri))a.widgetOnScreen.panel.uri=
"jimu/PreloadWidgetIconPanel";return a},compatible:!0},{version:"1.2",description:"The version embedded in online3.7.",upgrader:function(a){var b=0;if(a.widgetOnScreen&&a.widgetOnScreen.widgets){for(var c=!1,b=0;b<a.widgetOnScreen.widgets.length;b++)"widgets/Splash/Widget"===a.widgetOnScreen.widgets[b].uri&&(c=!0);c||a.widgetOnScreen.widgets.push({uri:"widgets/Splash/Widget",visible:!1,positionRelativeTo:"browser",version:"1.2"});c=!1;for(b=0;b<a.widgetOnScreen.widgets.length;b++)"widgets/TimeSlider/Widget"===
a.widgetOnScreen.widgets[b].uri&&(c=!0);c||a.widgetOnScreen.widgets.push({uri:"widgets/TimeSlider/Widget",visible:!1,position:{bottom:55,left:7},version:"1.2"});c=!1;for(b=0;b<a.widgetOnScreen.widgets.length;b++)"widgets/Swipe/Widget"===a.widgetOnScreen.widgets[b].uri&&(c=!0);c||a.widgetOnScreen.widgets.push({uri:"widgets/Swipe/Widget",visible:!1,position:{top:145,left:7},version:"1.2"})}return a},compatible:!0},{version:"1.3",description:"The version embedded in online3.8 \x26 online3.9.",upgrader:function(a){(function(b){m.visitElement(b,
function(a){a.positionRelativeTo&&(a.position?a.position.relativeTo=a.positionRelativeTo:a.position={relativeTo:a.positionRelativeTo},a.panel&&(a.panel.position?a.panel.position.relativeTo=a.panel.positionRelativeTo:a.panel.position={relativeTo:a.panel.positionRelativeTo}))});var a=b.widgetOnScreen;a&&(a.panel&&a.panel.positionRelativeTo)&&(a.panel.position?a.panel.position.relativeTo=a.panel.positionRelativeTo:a.panel.position={relativeTo:a.panel.positionRelativeTo});if((a=b.widgetPool)&&a.panel&&
a.panel.positionRelativeTo)a.panel.position?a.panel.position.relativeTo=a.panel.positionRelativeTo:a.panel.position={relativeTo:a.panel.positionRelativeTo}})(a);a.widgetOnScreen&&(a.widgetOnScreen.panel&&"jimu/PreloadWidgetIconPanel"===a.widgetOnScreen.panel.uri)&&(a.widgetOnScreen.panel.uri="jimu/OnScreenWidgetPanel");(function(a){if(a.widgetOnScreen&&a.widgetOnScreen.widgets&&a.theme&&"FoldableTheme"===a.theme.name){var c=null,d=null;if(c=a.widgetOnScreen.widgets[4])void 0!==c.position.top?(c={position:{left:205,
top:45}},d={position:{left:255,top:45}}):(c={position:{left:205,bottom:55}},d={position:{left:255,bottom:55}}),a.widgetOnScreen.widgets.splice(7,0,c,d)}})(a);(function(){for(var b=0,c=0,d=!1,b=0;b<a.widgetOnScreen.widgets.length;b++)if("widgets/Geocoder/Widget"===a.widgetOnScreen.widgets[b].uri){d=!0;break}for(var f=!1,c=0;c<a.widgetOnScreen.widgets.length;c++)if("widgets/Search/Widget"===a.widgetOnScreen.widgets[c].uri){f=!0;break}!f&&d&&(b=a.widgetOnScreen.widgets[b],b.uri="widgets/Search/Widget",
b.name="Search")})(a);(function(a){for(var c=0,c=a.widgetOnScreen.widgets.length-1;0<=c;c--){var d=a.widgetOnScreen.widgets[c];if("widgets/Swipe/Widget"===d.uri&&!d.closeable&&(a.widgetOnScreen.widgets.splice(c,1),!1!==d.visible)){d.closeable=!0;var f;a:{for(f=f=0;f<a.widgetOnScreen.widgets.length;f++)if(!a.widgetOnScreen.widgets[f].uri)break a;f=-1}0<=f&&(d.position=a.widgetOnScreen.widgets[f].position,a.widgetOnScreen.widgets[f]=d)}"widgets/TimeSlider/Widget"===d.uri&&(!1===d.visible?a.widgetOnScreen.widgets.splice(c,
1):d.closeable=!0)}})(a);a.widgetOnScreen.widgets.push({uri:"widgets/ZoomSlider/Widget",position:{top:5,left:7},version:"1.3"});a.loadingPage||(a.loadingPage={backgroundColor:"#508dca",backgroundImage:{visible:!1},loadingGif:{visible:!0,uri:"configs/loading/images/predefined_loading_1.gif",width:58,height:58}});return a},compatible:!0},{version:"1.4",description:"The version embedded in online3.10.",upgrader:function(a){if(a.theme){var b=a.theme.name;if(("FoldableTheme"===b||"JewelryBoxTheme"===b)&&
a.widgetOnScreen){var c=a.widgetOnScreen.widgets;if(c&&0<c.length)for(var b="themes/"+b+"/widgets/HeaderController/Widget",d=null,f=0;f<c.length;f++)if((d=c[f])&&d.uri===b&&d.position&&310===d.position.paddingRight)d.position.paddingRight=275}}return a},compatible:!0},{version:"2.0beta",description:"The version for Developer Edition beta 2.0.",upgrader:function(a){a.keepAppState=!0;return a},compatible:!0},{version:"2.0",description:"The version for Online 4.1.",upgrader:function(a){return a},compatible:!0},
{version:"2.0.1",description:"The version for Developer Edition 2.0.",upgrader:function(a){return a},compatible:!0},{version:"2.1",description:"The version for Online 4.2.",upgrader:function(a){return a},compatible:!0},{version:"2.2",description:"The version for Online 4.3.",upgrader:function(a){return a},compatible:!0},{version:"2.3",description:"The version for Online 4.4.",upgrader:function(a){function b(a,c){if(!a||!c)return!1;for(var d in c)if(c.hasOwnProperty(d))if("object"===typeof c[d]){if(!b(a[d],
c[d]))return!1}else if(a[d]!==c[d])return!1;return!0}function c(a){function c(){var d=b(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),e=b(a[12],{position:{top:10,right:195}});return d&&e}function d(){var c=b(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,bottom:45}}),e=b(a[12],{position:{left:15,top:233}});return c&&e}function h(){var c=b(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),d=b(a[12],{position:{right:15,top:195}});return c&&d}(function(){var c=
b(a[3],{uri:"widgets/MyLocation/Widget",position:{left:15,top:120}}),d=b(a[12],{position:{left:240,top:53}});return c&&d})()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,top:159},version:"2.3"}):c()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,top:159},version:"2.3"}):d()?a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,bottom:195},version:"2.3"}):h()&&a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:15,
top:159},version:"2.3"})}function d(a){function c(){var d=b(a[9],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}),e=b(a[2],{uri:"widgets/Search/Widget",position:{left:55,top:5}}),g=b(a[4],{position:{left:7,bottom:70}});return d&&e&&g}function d(){var c=b(a[9],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}),e=b(a[2],{uri:"widgets/Search/Widget",position:{right:2,top:2,relativeTo:"browser"}}),g=b(a[4],{position:{left:7,bottom:70}});return c&&e&&g}(function(){var c=b(a[9],{uri:"widgets/MyLocation/Widget",
position:{left:7,top:110}}),d=b(a[2],{uri:"widgets/Search/Widget",position:{left:55,top:5}}),e=b(a[4],{position:{left:55,top:45}});return c&&d&&e}()||c()||d())&&a.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:148,left:7},version:"2.3"})}(function(a,e,g){a=a.theme&&a.theme.name;if("FoldableTheme"===a)if(b(e[11],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}}))e.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:150,left:7},version:"2.3"});else if(b(e[11],
{uri:"widgets/MyLocation/Widget",position:{left:12,bottom:164}}))e.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:12,bottom:203},version:"2.3"}),g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{right:12,top:211},version:"2.3"});else{if(b(e[11],{uri:"widgets/MyLocation/Widget",position:{left:164,bottom:14}})){e.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:203,bottom:14,height:30},version:"2.3"});for(a=0;a<e.length;a++){var h=e[a];b(h,{uri:"widgets/Scalebar/Widget",
position:{left:220,bottom:5}})&&(h.position.left=288);b(h,{uri:"widgets/Coordinate/Widget",position:{left:395,bottom:5}})&&(h.position.left=463)}g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:209,left:12},version:"2.3"})}}else if("BillboardTheme"===a)c(e);else if("BoxTheme"===a)e.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:10,top:131},version:"2.3"});else if("JewelryBoxTheme"===a)d(e);else if("LaunchpadTheme"===a){if(b(e[6],{uri:"widgets/MyLocation/Widget",
position:{left:25,top:215}})||b(e[6],{uri:"widgets/MyLocation/Widget",position:{left:25,top:215}}))e.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:255,left:25},version:"2.3"}),g&&g.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{right:10,bottom:238},version:"2.3"})}else"PlateauTheme"===a?(b(e[6],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}})&&e.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:149,left:7},version:2.3}),b(e[6],{uri:"widgets/MyLocation/Widget",
position:{left:12,bottom:164}})&&e.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{left:12,bottom:201},version:2.3})):"TabTheme"===a&&b(e[11],{uri:"widgets/MyLocation/Widget",position:{left:7,top:110}})&&e.push({uri:"widgets/ExtentNavigate/Widget",visible:!1,position:{top:149,left:7},version:"2.3"})})(a,a.widgetOnScreen.widgets,a.mobileLayout&&a.mobileLayout.widgetOnScreen&&a.mobileLayout.widgetOnScreen.widgets);return a},compatible:!0}];this.isCompatible=function(a,b){for(var c=this.getVersionIndex(a),
d=this.getVersionIndex(b),c=c+1;c<=d;c++)if(!1===this.versions[c].compatible)return!1;return!0}}k.prototype=new l;return k.prototype.constructor=k});