// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["./basePortalUrlUtils"],function(l){function g(a,b){function c(b,c){var f,h,e,d,g="widgetOnScreen"===b;if(a[b]){if(a[b].groups)for(f=0;f<a[b].groups.length;f++)if(e=a[b].groups[f],c(e,{index:f,isWidget:!1,groupId:e.id,isThemeWidget:!1,isOnScreen:g}),a[b].groups[f].widgets)for(h=0;h<a[b].groups[f].widgets.length;h++)d=a[b].groups[f].widgets[h],c(d,{index:h,isWidget:!0,groupId:e.id,isThemeWidget:d.uri&&-1<d.uri.indexOf("themes/"+a.theme.name),isOnScreen:g});if(a[b].widgets)for(f=0;f<a[b].widgets.length;f++)d=
a[b].widgets[f],c(a[b].widgets[f],{index:f,isWidget:!0,groupId:b,isThemeWidget:d.uri&&-1<d.uri.indexOf("themes/"+a.theme.name),isOnScreen:g})}}c("widgetOnScreen",b);c("widgetPool",b)}var e={},k="inPanel hasLocale hasStyle hasConfig hasUIFile hasSettingPage hasSettingUIFile hasSettingLocale hasSettingStyle keepConfigAfterMapSwitched isController hasVersionManager isThemeWidget supportMultiInstance".split(" ");e.visitElement=g;e.getConfigElementById=function(a,b){var c;if("map"===b)return a.map;g(a,
function(a){if(a.id===b)return c=a,!0});return c};e.getConfigElementByLabel=function(a,b){var c;if("map"===b)return a.map;g(a,function(a){if(a.label||a.name===b)return c=a,!0});return c};e.getConfigElementsByName=function(a,b){var c=[];if("map"===b)return[a.map];g(a,function(a){a.name===b&&c.push(a)});return c};e.getWidgetNameFromUri=function(a){a=a.split("/");a.pop();return a.pop()};e.getAmdFolderFromUri=function(a){a=a.split("/");a.pop();return a.join("/")+"/"};e.widgetProperties=k;e.processWidgetProperties=
function(a){"undefined"===typeof a.properties.isController&&(a.properties.isController=!1);"undefined"===typeof a.properties.isThemeWidget&&(a.properties.isThemeWidget=!1);"undefined"===typeof a.properties.hasVersionManager&&(a.properties.hasVersionManager=!1);k.forEach(function(b){"undefined"===typeof a.properties[b]&&(a.properties[b]=!0)})};e.getControllerWidgets=function(a){var b=[];a.visitElement(function(a){a.isController&&b.push(a)});return b};e.addI18NLabelToManifest=function(a,b,c){function e(b,
c){c[g]&&(a.i18nLabels[b]=c[g]);"theme"===a.category&&(a.layouts&&a.layouts.forEach(function(d){a["i18nLabels_layout_"+d.name]||(a["i18nLabels_layout_"+d.name]={});a["i18nLabels_layout_"+d.name][b]=c["_layout_"+d.name]}),a.styles&&a.styles.forEach(function(d){a["i18nLabels_style_"+d.name]||(a["i18nLabels_style_"+d.name]={});a["i18nLabels_style_"+d.name][b]=c["_style_"+d.name]}));"widget"===a.category&&a.featureActions&&a.featureActions.forEach(function(d){a["i18nLabels_featureAction_"+d.name]||(a["i18nLabels_featureAction_"+
d.name]={});a["i18nLabels_featureAction_"+d.name][b]=c["_featureAction_"+d.name]})}a.i18nLabels={};var g="widget"===a.category?"_widgetLabel":"_themeLabel";b&&(b.root&&b.root[g])&&(a.i18nLabels.defaultLabel=b.root[g],"theme"===a.category&&(a.layouts&&a.layouts.forEach(function(c){a["i18nLabels_layout_"+c.name]={};a["i18nLabels_layout_"+c.name].defaultLabel=b.root["_layout_"+c.name]}),a.styles&&a.styles.forEach(function(c){a["i18nLabels_style_"+c.name]={};a["i18nLabels_style_"+c.name].defaultLabel=
b.root["_style_"+c.name]})),"widget"===a.category&&a.featureActions&&a.featureActions.forEach(function(c){a["i18nLabels_featureAction_"+c.name]={};a["i18nLabels_featureAction_"+c.name].defaultLabel=b.root["_featureAction_"+c.name]}));for(var f in c)e(f,c[f])};e.isHostedService=function(a){var b=l.getServerByUrl(a)+"/[^/]+/[^/]+/rest/services";return RegExp(b,"gi").test(a)};return e});